# Linear Regression

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('df_merged.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20926 entries, 0 to 20925
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20926 non-null  int64
 1   player_name   20926 non-null  object
 2   games         20926 non-null  int64
 3   time          20926 non-null  int64
 4   goals         20926 non-null  int64
 5   xG            20926 non-null  float64
 6   assists       20926 non-null  int64
 7   xA            20926 non-null  float64
 8   shots         20926 non-null  int64
 9   key_passes    20926 non-null  int64
 10  yellow_cards  20926 non-null  int64
 11  red_cards     20926 non-null  int64
 12  position      20926 non-null  object
 13  team_title    20926 non-null  object
 14  npg           20926 non-null  int64
 15  npxG          20926 non-null  float64
 16  xGChain       20926 non-null  float64
 17  xGBuildup     20926 non-null  float64
 18  league        20926 non-null  object
 19  season        20926 non-null  int64
dtypes: float64(5), int64(11), object(4)
memory usage: 3.2+ MB

# Data bn tanishuv

In [4]:
df.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league,season
0,1513,Mauro Icardi,36,2897,22,20.040535,6,4.607650,121,34,4,0,F S,Inter,18,16.234041,23.242989,4.910617,ASerie,1415
1,1955,Luca Toni,38,3228,22,21.204769,2,2.914252,125,27,3,0,F S,Verona,18,16.636976,18.810562,3.106042,ASerie,1415
2,3848,Carlos Tévez,32,2594,20,13.372144,7,5.016580,114,61,6,0,F M S,Juventus,18,10.327029,20.007632,8.907537,ASerie,1415
3,1293,Gonzalo Higuaín,37,2786,18,21.097412,7,4.082174,113,49,5,0,F S,Napoli,15,15.768320,22.711577,4.917353,ASerie,1415
4,2014,Jérémy Menez,33,2713,16,10.936869,4,4.379692,78,46,3,1,F M S,AC Milan,8,4.846598,13.755916,6.889687,ASerie,1415

In [7]:
df.drop(columns=['id','player_name'],axis=1,inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20926 entries, 0 to 20925
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   games         20926 non-null  int64
 1   time          20926 non-null  int64
 2   goals         20926 non-null  int64
 3   xG            20926 non-null  float64
 4   assists       20926 non-null  int64
 5   xA            20926 non-null  float64
 6   shots         20926 non-null  int64
 7   key_passes    20926 non-null  int64
 8   yellow_cards  20926 non-null  int64
 9   red_cards     20926 non-null  int64
 10  position      20926 non-null  object
 11  team_title    20926 non-null  object
 12  npg           20926 non-null  int64
 13  npxG          20926 non-null  float64
 14  xGChain       20926 non-null  float64
 15  xGBuildup     20926 non-null  float64
 16  league        20926 non-null  object
 17  season        20926 non-null  int64
dtypes: float64(5), int64(10), object(3)
memory usage: 2.9+ MB

# Data Preprocessing

In [9]:
df.isnull().sum()

games           0
time            0
goals           0
xG              0
assists         0
xA              0
shots           0
key_passes      0
yellow_cards    0
red_cards       0
position        0
team_title      0
npg             0
npxG            0
xGChain         0
xGBuildup       0
league          0
season          0
dtype: int64

In [10]:
#encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20926 entries, 0 to 20925
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   games                 20926 non-null  int64
 1   time                  20926 non-null  int64
 2   goals                 20926 non-null  int64
 3   xG                    20926 non-null  float64
 4   assists               20926 non-null  int64
 5   xA                    20926 non-null  float64
 6   shots                 20926 non-null  int64
 7   key_passes            20926 non-null  int64
 8   yellow_cards          20926 non-null  int64
 9   red_cards             20926 non-null  int64
 10  position              20926 non-null  int32
 11  team_title            20926 non-null  int32
 12  npg                   20926 non-null  int64
 13  npxG                  20926 non-null  float64
 14  xGChain               20926 non-null  float64
 15  xGBuildup             20926 non-null  float64
 16  season                20926 non-null  int64
 17  league_ASerie         20926 non-null  int32
 18  league_BundesLiga     20926 non-null  int32
 19  league_LaLiga         20926 non-null  int32
 20  league_League1        20926 non-null  int32
 21  league_PremierLeague  20926 non-null  int32
dtypes: float64(5), int32(7), int64(10)
memory usage: 3.0 MB

In [13]:
# Scaling

In [14]:
df.head()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,...,npg,npxG,xGChain,xGBuildup,season,league_ASerie,league_BundesLiga,league_LaLiga,league_League1,league_PremierLeague
0,36,2897,22,20.040535,6,4.607650,121,34,4,0,...,18,16.234041,23.242989,4.910617,1415,1,0,0,0,0
1,38,3228,22,21.204769,2,2.914252,125,27,3,0,...,18,16.636976,18.810562,3.106042,1415,1,0,0,0,0
2,32,2594,20,13.372144,7,5.016580,114,61,6,0,...,18,10.327029,20.007632,8.907537,1415,1,0,0,0,0
3,37,2786,18,21.097412,7,4.082174,113,49,5,0,...,15,15.768320,22.711577,4.917353,1415,1,0,0,0,0
4,33,2713,16,10.936869,4,4.379692,78,46,3,1,...,8,4.846598,13.755916,6.889687,1415,1,0,0,0,0

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [16]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('goals')

In [17]:
num_col

Index(['games', 'time', 'xG', 'assists', 'xA', 'shots', 'key_passes',
       'yellow_cards', 'red_cards', 'npg', 'npxG', 'xGChain', 'xGBuildup',
       'season'],
      dtype='object')

In [18]:
df[num_col]=scaler.fit_transform(df[num_col])

In [19]:
df.head()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,...,npg,npxG,xGChain,xGBuildup,season,league_ASerie,league_BundesLiga,league_LaLiga,league_League1,league_PremierLeague
0,0.945946,0.847031,22,0.509824,0.30,0.223448,0.533040,0.232877,0.235294,0.0,...,0.473684,0.505454,0.424501,0.175011,0.0,1,0,0,0,0
1,1.000000,0.943843,22,0.539441,0.10,0.141326,0.550661,0.184932,0.176471,0.0,...,0.473684,0.518000,0.343549,0.110697,0.0,1,0,0,0,0
2,0.837838,0.758409,20,0.340182,0.35,0.243279,0.502203,0.417808,0.352941,0.0,...,0.473684,0.321537,0.365412,0.317459,0.0,1,0,0,0,0
3,0.972973,0.814566,18,0.536710,0.35,0.197965,0.497797,0.335616,0.294118,0.0,...,0.394737,0.490954,0.414796,0.175251,0.0,1,0,0,0,0
4,0.864865,0.793214,16,0.278230,0.20,0.212393,0.343612,0.315068,0.176471,0.2,...,0.210526,0.150901,0.251233,0.245544,0.0,1,0,0,0,0

# Model Selection

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
lr=LinearRegression()

In [22]:
lr

LinearRegression()

# Training

In [23]:
x=df.drop('goals',axis=1)

In [24]:
y=df['goals']

In [25]:
from sklearn.model_selection  import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [27]:
lr.fit(x_train,y_train)

LinearRegression()

# Prediction

In [28]:
y_pred=lr.predict(x_test)

In [ ]:
# y_pred[0]
y_pred

0.00999732410227432

# Evaluation

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [33]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [35]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 0.05535187461342919
mse: 0.033754929074375724
r2: 0.997098134305895