### Scaling

In [88]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler, LabelEncoder

In [89]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_10/global_student_migration.csv')

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   student_id                 5000 non-null   object
 1   origin_country             5000 non-null   object
 2   destination_country        5000 non-null   object
 3   destination_city           5000 non-null   object
 4   university_name            5000 non-null   object
 5   course_name                5000 non-null   object
 6   field_of_study             5000 non-null   object
 7   year_of_enrollment         5000 non-null   int64
 8   scholarship_received       5000 non-null   object
 9   enrollment_reason          5000 non-null   object
 10  graduation_year            5000 non-null   int64
 11  placement_status           5000 non-null   object
 12  placement_country          2509 non-null   object
 13  placement_company          2509 non-null   object
 14  starting_salary_usd        5000 non-null   int64
 15  gpa_or_score               5000 non-null   float64
 16  visa_status                5000 non-null   object
 17  post_graduation_visa       5000 non-null   object
 18  language_proficiency_test  4018 non-null   object
 19  test_score                 5000 non-null   float64
dtypes: float64(2), int64(3), object(15)
memory usage: 781.4+ KB

In [91]:
df.isna().sum()

student_id                      0
origin_country                  0
destination_country             0
destination_city                0
university_name                 0
course_name                     0
field_of_study                  0
year_of_enrollment              0
scholarship_received            0
enrollment_reason               0
graduation_year                 0
placement_status                0
placement_country            2491
placement_company            2491
starting_salary_usd             0
gpa_or_score                    0
visa_status                     0
post_graduation_visa            0
language_proficiency_test     982
test_score                      0
dtype: int64

| Code             | Purpose                      | Works On           | Notes                             |
| ---------------- | ---------------------------- | ------------------ | --------------------------------- |
| `fillna(mean)`   | Replace missing with average | int, float         | Sensitive to outliers             |
| `fillna(mode)`   | Replace with most frequent   | object, int, float | Good for categories               |
| `fillna(median)` | Replace with middle value    | int, float         | Robust to outliers                |
| `fillna(value)`  | Replace with constant        | any                | Manual default fill               |
| `drop(axis=1)`   | Drop column                  | column name        | Removes unwanted or empty columns |
| `dropna()`       | Drop rows with missing       | entire row         | Use carefully on large datasets   |

### Filling missing values

In [92]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype =='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

In [93]:
df.isna().sum()

student_id                   0
origin_country               0
destination_country          0
destination_city             0
university_name              0
course_name                  0
field_of_study               0
year_of_enrollment           0
scholarship_received         0
enrollment_reason            0
graduation_year              0
placement_status             0
placement_country            0
placement_company            0
starting_salary_usd          0
gpa_or_score                 0
visa_status                  0
post_graduation_visa         0
language_proficiency_test    0
test_score                   0
dtype: int64

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   student_id                 5000 non-null   object
 1   origin_country             5000 non-null   object
 2   destination_country        5000 non-null   object
 3   destination_city           5000 non-null   object
 4   university_name            5000 non-null   object
 5   course_name                5000 non-null   object
 6   field_of_study             5000 non-null   object
 7   year_of_enrollment         5000 non-null   int64
 8   scholarship_received       5000 non-null   object
 9   enrollment_reason          5000 non-null   object
 10  graduation_year            5000 non-null   int64
 11  placement_status           5000 non-null   object
 12  placement_country          5000 non-null   object
 13  placement_company          5000 non-null   object
 14  starting_salary_usd        5000 non-null   int64
 15  gpa_or_score               5000 non-null   float64
 16  visa_status                5000 non-null   object
 17  post_graduation_visa       5000 non-null   object
 18  language_proficiency_test  5000 non-null   object
 19  test_score                 5000 non-null   float64
dtypes: float64(2), int64(3), object(15)
memory usage: 781.4+ KB

| Encoding Type          | Description                                                          | Use Case Scenarios                                                                      | Pros                                                       | Cons                                                                                             |
| ---------------------- | -------------------------------------------------------------------- | --------------------------------------------------------------------------------------- | ---------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| **One-Hot Encoding**   | Converts categories into binary vectors (one 1 and the rest 0)       | - Nominal variables (no order)<br>- Low cardinality (few unique values)                 | - Simple<br>- No ordinal assumptions<br>- Widely supported | - High dimensionality if many categories<br>- Not suitable for tree models without preprocessing |
| **Label Encoding**     | Assigns each category a unique integer                               | - Ordinal variables with true order<br>- Tree-based models                              | - Fast<br>- Memory-efficient                               | - Implies ordinal relationships even if not present<br>- Misleading for linear models            |
| **Frequency Encoding** | Replaces category with frequency of its occurrence                   | - High-cardinality features<br>- Tree-based models                                      | - Simple<br>- Preserves distribution information           | - Can introduce noise if frequencies are similar<br>- Not interpretable                          |
| **Ordinal Encoding**   | Assigns integers based on meaningful order of categories             | - Ordinal features (e.g. low, medium, high)                                             | - Captures order<br>- Simple                               | - Not suitable for nominal features<br>- Assumes linearity of order                              |
| **Target Encoding**    | Replaces category with the mean of target variable for that category | - High cardinality<br>- Useful in classification/regression (target leakage controlled) | - Captures target signal<br>- Compact                      | - Can cause overfitting<br>- Must be regularized or cross-validated                              |

df=pd.get_dummies(df,columns=['Bathrooms'],prefix='bath_num',dtype=int)   # one-hot encoding



df['Status'] = encoder.fit_transform(df['Status'])                        # Label encoding



df['Bedroom_freq']=df['Bedrooms'].map(df['Bedrooms'].value_counts())      # Frequency encoding


target_encoding = df.groupby('City')['Days on Market'].mean()
df['City_Encoded'] = df['City'].map(target_encoding)                      # target_encoding



property_mapping={
    'Apartment':0,
    'Condo':1,
    'Townhouse':2,
    'Single Family':3,
    'Multi-Family':4
}

df['property_ordinal'] = df['Property Type'].map(property_mapping)       # ordinal_encoding

# LABEL ENCODER

In [95]:
encoder = LabelEncoder()
df['student_id'] = encoder.fit_transform(df['student_id'])
df['origin_country'] = encoder.fit_transform(df['origin_country'])
df['destination_country'] = encoder.fit_transform(df['destination_country'])
df['destination_city'] = encoder.fit_transform(df['destination_city'])
df['university_name'] = encoder.fit_transform(df['university_name'])
df['course_name'] = encoder.fit_transform(df['course_name'])
df['field_of_study'] = encoder.fit_transform(df['field_of_study'])
df['placement_country'] = encoder.fit_transform(df['placement_country'])
df['post_graduation_visa'] = encoder.fit_transform(df['post_graduation_visa'])

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   student_id                 5000 non-null   int32
 1   origin_country             5000 non-null   int32
 2   destination_country        5000 non-null   int32
 3   destination_city           5000 non-null   int32
 4   university_name            5000 non-null   int32
 5   course_name                5000 non-null   int32
 6   field_of_study             5000 non-null   int32
 7   year_of_enrollment         5000 non-null   int64
 8   scholarship_received       5000 non-null   object
 9   enrollment_reason          5000 non-null   object
 10  graduation_year            5000 non-null   int64
 11  placement_status           5000 non-null   object
 12  placement_country          5000 non-null   int32
 13  placement_company          5000 non-null   object
 14  starting_salary_usd        5000 non-null   int64
 15  gpa_or_score               5000 non-null   float64
 16  visa_status                5000 non-null   object
 17  post_graduation_visa       5000 non-null   int32
 18  language_proficiency_test  5000 non-null   object
 19  test_score                 5000 non-null   float64
dtypes: float64(2), int32(9), int64(3), object(6)
memory usage: 605.6+ KB

In [97]:
df.sample(5)

,student_id,origin_country,destination_country,destination_city,university_name,course_name,field_of_study,year_of_enrollment,scholarship_received,enrollment_reason,graduation_year,placement_status,placement_country,placement_company,starting_salary_usd,gpa_or_score,visa_status,post_graduation_visa,language_proficiency_test,test_score
4471,4471,0,6,23,70,3,7,2023,Yes,Higher Ranking,2026,Placed,6,Microsoft,103739,2.85,Student Visa,2,IELTS,6.5
4845,4845,2,1,49,73,9,1,2020,Yes,Political Stability,2023,Not Placed,8,Microsoft,0,3.20,J1,1,TOEFL,8.4
4751,4751,4,6,23,61,5,6,2019,Yes,Scholarship,2022,Not Placed,8,Microsoft,0,2.76,Study Permit,1,PTE,5.2
2968,2968,9,2,34,21,12,7,2022,Yes,Political Stability,2023,Not Placed,8,Microsoft,0,3.21,J1,4,Duolingo,5.1
3439,3439,5,1,22,58,10,0,2020,No,Quality of Life,2022,Not Placed,8,Microsoft,0,2.61,Student Visa,4,PTE,6.5

In [98]:
df['scholarship_received'].value_counts()

scholarship_received
Yes    2577
No     2423
Name: count, dtype: int64

In [99]:
df['placement_status'].value_counts()

placement_status
Placed        2509
Not Placed    2491
Name: count, dtype: int64

# ONE-HOT ENCODING

In [100]:
df=pd.get_dummies(df,columns=['scholarship_received'],prefix='scholarship',dtype=int)
df=pd.get_dummies(df,columns=['placement_status'],prefix='placement',dtype=int)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   student_id                 5000 non-null   int32
 1   origin_country             5000 non-null   int32
 2   destination_country        5000 non-null   int32
 3   destination_city           5000 non-null   int32
 4   university_name            5000 non-null   int32
 5   course_name                5000 non-null   int32
 6   field_of_study             5000 non-null   int32
 7   year_of_enrollment         5000 non-null   int64
 8   enrollment_reason          5000 non-null   object
 9   graduation_year            5000 non-null   int64
 10  placement_country          5000 non-null   int32
 11  placement_company          5000 non-null   object
 12  starting_salary_usd        5000 non-null   int64
 13  gpa_or_score               5000 non-null   float64
 14  visa_status                5000 non-null   object
 15  post_graduation_visa       5000 non-null   int32
 16  language_proficiency_test  5000 non-null   object
 17  test_score                 5000 non-null   float64
 18  scholarship_No             5000 non-null   int32
 19  scholarship_Yes            5000 non-null   int32
 20  placement_Not Placed       5000 non-null   int32
 21  placement_Placed           5000 non-null   int32
dtypes: float64(2), int32(13), int64(3), object(4)
memory usage: 605.6+ KB

In [102]:
df.sample()

,student_id,origin_country,destination_country,destination_city,university_name,course_name,field_of_study,year_of_enrollment,enrollment_reason,graduation_year,...,starting_salary_usd,gpa_or_score,visa_status,post_graduation_visa,language_proficiency_test,test_score,scholarship_No,scholarship_Yes,placement_Not Placed,placement_Placed
1452,1452,2,7,12,25,4,1,2019,Job Opportunities,2022,...,0,2.85,Schengen Student Visa,4,Duolingo,0.0,1,0,1,0

In [103]:
df['enrollment_reason'].value_counts()

enrollment_reason
Quality of Life        1015
Higher Ranking         1004
Scholarship            1001
Job Opportunities       991
Political Stability     989
Name: count, dtype: int64

In [104]:
df['language_proficiency_test'].value_counts()

language_proficiency_test
Duolingo    2012
IELTS       1005
PTE          999
TOEFL        984
Name: count, dtype: int64

In [105]:
df['visa_status'].value_counts()

visa_status
Schengen Student Visa    863
Tier 4                   853
J1                       848
Student Visa             817
Study Permit             811
F1                       808
Name: count, dtype: int64

# FREQUENCY ENCODING

In [106]:
df['enrollment_reason_freq']=df['enrollment_reason'].map(df['enrollment_reason'].value_counts())
df['language_proficiency_test_freq']=df['language_proficiency_test'].map(df['language_proficiency_test'].value_counts())
df['visa_status_freq']=df['visa_status'].map(df['visa_status'].value_counts())
df['placement_company_freq'] = df['placement_company'].map(df['placement_company'].value_counts())

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   student_id                      5000 non-null   int32
 1   origin_country                  5000 non-null   int32
 2   destination_country             5000 non-null   int32
 3   destination_city                5000 non-null   int32
 4   university_name                 5000 non-null   int32
 5   course_name                     5000 non-null   int32
 6   field_of_study                  5000 non-null   int32
 7   year_of_enrollment              5000 non-null   int64
 8   enrollment_reason               5000 non-null   object
 9   graduation_year                 5000 non-null   int64
 10  placement_country               5000 non-null   int32
 11  placement_company               5000 non-null   object
 12  starting_salary_usd             5000 non-null   int64
 13  gpa_or_score                    5000 non-null   float64
 14  visa_status                     5000 non-null   object
 15  post_graduation_visa            5000 non-null   int32
 16  language_proficiency_test       5000 non-null   object
 17  test_score                      5000 non-null   float64
 18  scholarship_No                  5000 non-null   int32
 19  scholarship_Yes                 5000 non-null   int32
 20  placement_Not Placed            5000 non-null   int32
 21  placement_Placed                5000 non-null   int32
 22  enrollment_reason_freq          5000 non-null   int64
 23  language_proficiency_test_freq  5000 non-null   int64
 24  visa_status_freq                5000 non-null   int64
 25  placement_company_freq          5000 non-null   int64
dtypes: float64(2), int32(13), int64(7), object(4)
memory usage: 761.8+ KB

In [108]:
df.columns

Index(['student_id', 'origin_country', 'destination_country',
       'destination_city', 'university_name', 'course_name', 'field_of_study',
       'year_of_enrollment', 'enrollment_reason', 'graduation_year',
       'placement_country', 'placement_company', 'starting_salary_usd',
       'gpa_or_score', 'visa_status', 'post_graduation_visa',
       'language_proficiency_test', 'test_score', 'scholarship_No',
       'scholarship_Yes', 'placement_Not Placed', 'placement_Placed',
       'enrollment_reason_freq', 'language_proficiency_test_freq',
       'visa_status_freq', 'placement_company_freq'],
      dtype='object')

In [109]:
df.drop(columns='visa_status', axis=1, inplace=True)
df.drop(columns='language_proficiency_test', axis=1, inplace=True) 
df.drop(columns='enrollment_reason', axis=1, inplace=True)
df.drop(columns='placement_company', axis=1, inplace=True)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   student_id                      5000 non-null   int32
 1   origin_country                  5000 non-null   int32
 2   destination_country             5000 non-null   int32
 3   destination_city                5000 non-null   int32
 4   university_name                 5000 non-null   int32
 5   course_name                     5000 non-null   int32
 6   field_of_study                  5000 non-null   int32
 7   year_of_enrollment              5000 non-null   int64
 8   graduation_year                 5000 non-null   int64
 9   placement_country               5000 non-null   int32
 10  starting_salary_usd             5000 non-null   int64
 11  gpa_or_score                    5000 non-null   float64
 12  post_graduation_visa            5000 non-null   int32
 13  test_score                      5000 non-null   float64
 14  scholarship_No                  5000 non-null   int32
 15  scholarship_Yes                 5000 non-null   int32
 16  placement_Not Placed            5000 non-null   int32
 17  placement_Placed                5000 non-null   int32
 18  enrollment_reason_freq          5000 non-null   int64
 19  language_proficiency_test_freq  5000 non-null   int64
 20  visa_status_freq                5000 non-null   int64
 21  placement_company_freq          5000 non-null   int64
dtypes: float64(2), int32(13), int64(7)
memory usage: 605.6 KB

# SCALING

| **Scaler**         | **What it Does**                                                            | **Formula**                                                       | **Sensitive to Outliers?** | **When to Use**                                                               |
| ------------------ | --------------------------------------------------------------------------- | ----------------------------------------------------------------- | -------------------------- | ----------------------------------------------------------------------------- |
| **StandardScaler** | Standardizes features by removing the mean and scaling to unit variance     | $z = \frac{x - \mu}{\sigma}$                                      | Yes                        | When data is normally distributed or has no extreme outliers                  |
| **MinMaxScaler**   | Scales features to a fixed range, usually \[0, 1]                           | $x' = \frac{x - x_{\text{min}}}{x_{\text{max}} - x_{\text{min}}}$ | Yes                        | When you want all features to be within the same range, e.g., neural networks |
| **RobustScaler**   | Scales features using statistics that are robust to outliers (median & IQR) | $x' = \frac{x - \text{median}}{\text{IQR}}$, where IQR = Q3 - Q1  | No                         | When data contains many outliers                                              |

In [116]:
num_col=df.select_dtypes(include=['int64','float64','int32']).columns.tolist()

In [117]:
num_col

['student_id',
 'origin_country',
 'destination_country',
 'destination_city',
 'university_name',
 'course_name',
 'field_of_study',
 'year_of_enrollment',
 'graduation_year',
 'placement_country',
 'starting_salary_usd',
 'gpa_or_score',
 'post_graduation_visa',
 'test_score',
 'scholarship_No',
 'scholarship_Yes',
 'placement_Not Placed',
 'placement_Placed',
 'enrollment_reason_freq',
 'language_proficiency_test_freq',
 'visa_status_freq',
 'placement_company_freq']

In [118]:
df.sample(5)

,student_id,origin_country,destination_country,destination_city,university_name,course_name,field_of_study,year_of_enrollment,graduation_year,placement_country,...,post_graduation_visa,test_score,scholarship_No,scholarship_Yes,placement_Not Placed,placement_Placed,enrollment_reason_freq,language_proficiency_test_freq,visa_status_freq,placement_company_freq
320,320,1,2,3,41,8,6,2019,2021,8,...,3,5.2,0,1,1,0,989,999,808,2711
1885,1885,0,4,13,6,4,2,2019,2022,8,...,1,8.0,1,0,1,0,989,999,811,2711
3965,3965,4,8,27,16,5,5,2023,2026,8,...,4,6.9,0,1,1,0,991,984,853,2711
2210,2210,2,7,12,57,11,1,2021,2024,7,...,4,5.0,0,1,0,1,1001,984,811,203
1469,1469,1,3,47,30,2,4,2020,2022,3,...,1,6.2,0,1,0,1,1015,999,863,203

In [119]:
standard=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [120]:
df[num_col]=standard.fit_transform(df[num_col])

In [121]:
df.head()

,student_id,origin_country,destination_country,destination_city,university_name,course_name,field_of_study,year_of_enrollment,graduation_year,placement_country,...,post_graduation_visa,test_score,scholarship_No,scholarship_Yes,placement_Not Placed,placement_Placed,enrollment_reason_freq,language_proficiency_test_freq,visa_status_freq,placement_company_freq
0,-1.731704,-1.211156,0.156131,0.546263,-0.636863,-0.708753,-0.225659,-0.007743,0.594816,-0.469313,...,1.403819,0.729030,1.031289,-1.031289,-0.996406,0.996406,0.414428,-0.844751,0.869250,0.918868
1,-1.731012,1.230128,-0.892669,-1.667623,-0.081935,-0.940766,0.210988,1.400121,0.594816,-1.591714,...,-0.694774,0.762660,-0.969660,0.969660,-0.996406,0.996406,-0.963042,-0.814644,-1.043312,-1.078823
2,-1.730319,-0.164891,-1.591869,1.791573,0.750457,0.683325,-1.535601,-1.415608,-1.827566,0.653088,...,-1.394305,-1.894106,1.031289,-1.031289,1.003607,-1.003607,0.096550,1.218529,-1.179923,0.918868
3,-1.729626,0.881373,1.204932,-1.390888,0.704213,-0.476740,1.520929,-0.007743,-0.010780,0.653088,...,0.004757,-1.894106,-0.969660,0.969660,-0.996406,0.996406,1.579980,1.218529,1.324622,-1.085195
4,-1.728933,0.532618,-0.892669,1.445654,1.397873,-1.172779,0.210988,-0.711676,-1.221971,-1.591714,...,-0.694774,0.863550,-0.969660,0.969660,-0.996406,0.996406,-1.174961,-0.814644,1.324622,-1.094754

In [122]:
df[num_col] = minmax.fit_transform(df[num_col])

In [123]:
df.head()

,student_id,origin_country,destination_country,destination_city,university_name,course_name,field_of_study,year_of_enrollment,graduation_year,placement_country,...,post_graduation_visa,test_score,scholarship_No,scholarship_Yes,placement_Not Placed,placement_Placed,enrollment_reason_freq,language_proficiency_test_freq,visa_status_freq,placement_company_freq
0,0.0000,0.111111,0.555556,0.64,0.315068,0.285714,0.428571,0.50,0.666667,0.555556,...,1.00,0.866667,1.0,0.0,0.0,1.0,0.576923,0.000000,0.818182,1.000000
1,0.0002,0.888889,0.222222,0.00,0.479452,0.214286,0.571429,1.00,0.666667,0.222222,...,0.25,0.877778,0.0,1.0,0.0,1.0,0.076923,0.014591,0.054545,0.008696
2,0.0004,0.444444,0.000000,1.00,0.726027,0.714286,0.000000,0.00,0.000000,0.888889,...,0.00,0.000000,1.0,0.0,1.0,0.0,0.461538,1.000000,0.000000,1.000000
3,0.0006,0.777778,0.888889,0.08,0.712329,0.357143,1.000000,0.50,0.500000,0.888889,...,0.50,0.000000,0.0,1.0,0.0,1.0,1.000000,1.000000,1.000000,0.005534
4,0.0008,0.666667,0.222222,0.90,0.917808,0.142857,0.571429,0.25,0.166667,0.222222,...,0.25,0.911111,0.0,1.0,0.0,1.0,0.000000,0.014591,1.000000,0.000791

In [124]:
df[num_col] = robust.fit_transform(df[num_col])

In [125]:
df.head()

,student_id,origin_country,destination_country,destination_city,university_name,course_name,field_of_study,year_of_enrollment,graduation_year,placement_country,...,post_graduation_visa,test_score,scholarship_No,scholarship_Yes,placement_Not Placed,placement_Placed,enrollment_reason_freq,language_proficiency_test_freq,visa_status_freq,placement_company_freq
0,-1.0000,-0.6,0.0,0.347826,-0.342105,-0.375,-0.125,0.0,0.5,-1.0,...,1.0,0.52,1.0,-1.0,0.0,0.0,0.230769,-0.020731,0.119048,0.000000
1,-0.9996,0.8,-0.6,-1.043478,-0.026316,-0.500,0.125,1.0,0.5,-2.0,...,-0.5,0.56,0.0,0.0,0.0,0.0,-0.769231,-0.005923,-0.880952,-0.994449
2,-0.9992,0.0,-1.0,1.130435,0.447368,0.375,-0.875,-1.0,-1.5,0.0,...,-1.0,-2.60,1.0,-1.0,1.0,-1.0,0.000000,0.994077,-0.952381,0.000000
3,-0.9988,0.6,0.6,-0.869565,0.421053,-0.250,0.875,0.0,0.0,0.0,...,0.0,-2.60,0.0,0.0,0.0,0.0,1.076923,0.994077,0.357143,-0.997621
4,-0.9984,0.4,-0.6,0.913043,0.815789,-0.625,0.125,-0.5,-1.0,-2.0,...,-0.5,0.68,0.0,0.0,0.0,0.0,-0.923077,-0.005923,0.357143,-1.002379