In [1]:
import pandas as pd
df=pd.read_csv('train.csv')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
 12  Degree       891 non-null    object
dtypes: float64(7), object(6)
memory usage: 90.6+ KB

In [37]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
 12  Degree       891 non-null    object
dtypes: float64(7), object(6)
memory usage: 90.6+ KB

In [39]:
# Encoding+ For loop
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [40]:
df.nunique()

PassengerId    888
Survived         3
Pclass           4
Name           876
Gender           2
Age             89
SibSp            8
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
Degree           3
dtype: int64

In [41]:
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=6:
            dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
            df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PassengerId      891 non-null    float64
 1   Survived         891 non-null    float64
 2   Pclass           891 non-null    float64
 3   Name             891 non-null    int32
 4   Age              891 non-null    float64
 5   SibSp            891 non-null    float64
 6   Parch            891 non-null    float64
 7   Ticket           891 non-null    int32
 8   Fare             891 non-null    float64
 9   Cabin            891 non-null    int32
 10  Gender_female    891 non-null    int32
 11  Gender_male      891 non-null    int32
 12  Embarked_C       891 non-null    int32
 13  Embarked_Q       891 non-null    int32
 14  Embarked_S       891 non-null    int32
 15  Degree_Bachelor  891 non-null    int32
 16  Degree_Master    891 non-null    int32
 17  Degree_PhD       891 non-null    int32
dtypes: float64(7), int32(11)
memory usage: 87.1 KB

# Scaling

In [43]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
standart=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [46]:
num_col=df.select_dtypes(include=['float64','int32']).columns.tolist()

In [47]:
num_col

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Gender_female',
 'Gender_male',
 'Embarked_C',
 'Embarked_Q',
 'Embarked_S',
 'Degree_Bachelor',
 'Degree_Master',
 'Degree_PhD']

In [48]:
#StandardScaler
df[num_col]=standart.fit_transform(df[num_col])

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PassengerId      891 non-null    float64
 1   Survived         891 non-null    float64
 2   Pclass           891 non-null    float64
 3   Name             891 non-null    float64
 4   Age              891 non-null    float64
 5   SibSp            891 non-null    float64
 6   Parch            891 non-null    float64
 7   Ticket           891 non-null    float64
 8   Fare             891 non-null    float64
 9   Cabin            891 non-null    float64
 10  Gender_female    891 non-null    float64
 11  Gender_male      891 non-null    float64
 12  Embarked_C       891 non-null    float64
 13  Embarked_Q       891 non-null    float64
 14  Embarked_S       891 non-null    float64
 15  Degree_Bachelor  891 non-null    float64
 16  Degree_Master    891 non-null    float64
 17  Degree_PhD       891 non-null    float64
dtypes: float64(18)
memory usage: 125.4 KB

In [50]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Gender_female,Gender_male,Embarked_C,Embarked_Q,Embarked_S,Degree_Bachelor,Degree_Master,Degree_PhD
0,-1.749298,-0.790625,0.828626,-1.257424,-0.596567,0.435235,-0.473674,0.918966,-0.502445,-0.281881,-0.732261,0.732261,-0.482043,-0.307562,0.615838,0.047431,-0.033520,-0.03352
1,-1.745384,1.273397,-1.565780,-0.938335,0.637418,0.435235,-0.473674,1.282625,0.786845,1.161545,1.365632,-1.365632,2.074505,-0.307562,-1.623803,0.047431,-0.033520,-0.03352
2,-1.741471,1.273397,0.828626,-0.315722,-0.288071,-0.475458,-0.473674,1.646283,-0.488854,-0.281881,1.365632,-1.365632,-0.482043,-0.307562,0.615838,0.047431,-0.033520,-0.03352
3,-1.737557,1.273397,-1.565780,-0.627029,0.406046,0.435235,-0.473674,-1.442322,0.420730,0.057748,1.365632,-1.365632,-0.482043,-0.307562,0.615838,0.047431,-0.033520,-0.03352
4,-1.733643,-0.790625,0.828626,-1.615427,0.406046,-0.475458,-0.473674,0.664904,-0.486337,-0.281881,-0.732261,0.732261,-0.482043,-0.307562,0.615838,-21.083169,29.832868,-0.03352

In [51]:
#Minmax
df[num_col]=minmax.fit_transform(df[num_col])

In [52]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Gender_female,Gender_male,Embarked_C,Embarked_Q,Embarked_S,Degree_Bachelor,Degree_Master,Degree_PhD
0,0.000000,0.0,1.0,0.122286,0.271174,0.125,0.0,0.769118,0.014151,0.321918,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
1,0.001124,1.0,0.0,0.216000,0.472229,0.125,0.0,0.876471,0.139136,0.554795,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.002247,1.0,1.0,0.398857,0.321438,0.000,0.0,0.983824,0.015469,0.321918,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.003371,1.0,0.0,0.307429,0.434531,0.125,0.0,0.072059,0.103644,0.376712,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.004494,0.0,1.0,0.017143,0.434531,0.000,0.0,0.694118,0.015713,0.321918,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [53]:
#Rabust
df[num_col]=robust.fit_transform(df[num_col])

In [54]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Gender_female,Gender_male,Embarked_C,Embarked_Q,Embarked_S,Degree_Bachelor,Degree_Master,Degree_PhD
0,-1.013554,0.0,0.0,-0.725843,-0.595012,1.0,0.0,0.515235,-0.312011,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-1.011287,1.0,-2.0,-0.541573,0.635757,1.0,0.0,0.717452,2.461242,0.232877,1.0,-1.0,1.0,0.0,-1.0,0.0,0.0,0.0
2,-1.009019,1.0,0.0,-0.182022,-0.287320,0.0,0.0,0.919668,-0.282777,0.000000,1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.006752,1.0,-2.0,-0.361798,0.404988,1.0,0.0,-0.797784,1.673732,0.054795,1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.004484,0.0,0.0,-0.932584,0.404988,0.0,0.0,0.373961,-0.277363,0.000000,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0

In [31]:
df['Pclass']=minmax.fit_transform(df[['Pclass']])

In [32]:
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Degree
0,-1.009029,0.0,1.0,"Braund, Mr. Owen Harris",male,-0.342857,1.0,0.0,A/5 21171,-0.312011,NaN,S,Bachelor
1,-1.006772,1.0,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.571429,1.0,0.0,PC 17599,2.461242,C85,C,Bachelor
2,-1.004515,1.0,1.0,"Heikkinen, Miss. Laina",female,-0.114286,0.0,0.0,STON/O2. 3101282,-0.282777,NaN,S,Bachelor
3,-1.002257,1.0,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.400000,1.0,0.0,113803,1.673732,C123,S,NaN
4,-1.000000,0.0,1.0,"Allen, Mr. William Henry",male,0.400000,0.0,0.0,373450,-0.277363,NaN,S,Master