# Data bn tanishuv

In [47]:
import pandas as pd
df=pd.read_csv('Bank_Personal_Loan_Modelling.csv')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 4995 non-null   float64
 2   Experience          5000 non-null   int64
 3   Income              4995 non-null   float64
 4   ZIP Code            4995 non-null   float64
 5   Family              4995 non-null   float64
 6   CCAvg               4995 non-null   float64
 7   Education           4995 non-null   float64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 547.0 KB

In [49]:
df.drop('ID',axis=1,inplace=True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 4995 non-null   float64
 1   Experience          5000 non-null   int64
 2   Income              4995 non-null   float64
 3   ZIP Code            4995 non-null   float64
 4   Family              4995 non-null   float64
 5   CCAvg               4995 non-null   float64
 6   Education           4995 non-null   float64
 7   Mortgage            5000 non-null   int64
 8   Personal Loan       5000 non-null   int64
 9   Securities Account  5000 non-null   int64
 10  CD Account          5000 non-null   int64
 11  Online              5000 non-null   int64
 12  CreditCard          5000 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 507.9 KB

# Scaling

In [1]:
import pandas as pd
df=pd.read_csv('Bank_Personal_Loan_Modelling.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 4995 non-null   float64
 2   Experience          5000 non-null   int64
 3   Income              4995 non-null   float64
 4   ZIP Code            4995 non-null   float64
 5   Family              4995 non-null   float64
 6   CCAvg               4995 non-null   float64
 7   Education           4995 non-null   float64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 547.0 KB

# Handling missing values

In [3]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   float64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   float64
 4   ZIP Code            5000 non-null   float64
 5   Family              5000 non-null   float64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   float64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 547.0 KB

In [5]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

# Encoding

In [ ]:
# Object qiymatlar mavjud emasligi uchun bu bosqichni tashlab ketamiz

# Scaling

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   float64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   float64
 4   ZIP Code            5000 non-null   float64
 5   Family              5000 non-null   float64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   float64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 547.0 KB

In [7]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25.0,1,49.0,91107.0,4.0,1.6,1.0,0,0,1,0,0,0
1,2,45.0,19,34.0,90089.0,3.0,1.5,1.0,0,0,1,0,0,0
2,3,39.0,15,11.0,94720.0,1.0,1.0,1.0,0,0,0,0,0,0
3,4,35.0,9,100.0,94112.0,1.0,2.7,2.0,0,0,0,0,0,0
4,5,35.0,8,45.0,91330.0,4.0,1.0,2.0,0,0,0,0,0,1

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [ ]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Personal Loan')   # izoh: Target qiymat scalimng qilinmaydi

In [14]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Securities Account', 'CD Account', 'Online',
       'CreditCard'],
      dtype='object')

# StandardScaler

In [15]:
scaler=StandardScaler()

In [16]:
scaler

StandardScaler()

In [18]:
df['Age']=scaler.fit_transform(df[['Age']])

In [19]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,-1.775331,1,49.0,91107.0,4.0,1.6,1.0,0,0,1,0,0,0
1,2,-0.028915,19,34.0,90089.0,3.0,1.5,1.0,0,0,1,0,0,0
2,3,-0.552839,15,11.0,94720.0,1.0,1.0,1.0,0,0,0,0,0,0
3,4,-0.902123,9,100.0,94112.0,1.0,2.7,2.0,0,0,0,0,0,0
4,5,-0.902123,8,45.0,91330.0,4.0,1.0,2.0,0,0,0,0,0,1

# MinMaxScaler

In [20]:
scaler=MinMaxScaler()

In [21]:
scaler

MinMaxScaler()

In [28]:
df['ZIP Code']=scaler.fit_transform(df[['ZIP Code']])

In [24]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,-1.775331,1,49.0,0.936527,4.0,1.6,1.0,0,0,1,0,0,0
1,2,-0.028915,19,34.0,0.924872,3.0,1.5,1.0,0,0,1,0,0,0
2,3,-0.552839,15,11.0,0.977892,1.0,1.0,1.0,0,0,0,0,0,0
3,4,-0.902123,9,100.0,0.970931,1.0,2.7,2.0,0,0,0,0,0,0
4,5,-0.902123,8,45.0,0.939080,4.0,1.0,2.0,0,0,0,0,0,1

# RobustScaler

In [29]:
scaler=RobustScaler()

In [30]:
scaler

RobustScaler()

In [31]:
df['Family']=scaler.fit_transform(df[['Family']])

In [32]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,ZIP Code,ZIP code
0,1,-1.775331,1,49.0,0.936527,1.0,1.6,1.0,0,0,1,0,0,0,0.936527,0.936527
1,2,-0.028915,19,34.0,0.924872,0.5,1.5,1.0,0,0,1,0,0,0,0.924872,0.924872
2,3,-0.552839,15,11.0,0.977892,-0.5,1.0,1.0,0,0,0,0,0,0,0.977892,0.977892
3,4,-0.902123,9,100.0,0.970931,-0.5,2.7,2.0,0,0,0,0,0,0,0.970931,0.970931
4,5,-0.902123,8,45.0,0.939080,1.0,1.0,2.0,0,0,0,0,0,1,0.939080,0.939080

# For Loop + Scaling

In [ ]:
#1-usul
scaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype!='object':
        df[col]=scaler.fit_transform(df[[col]])

In [38]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,ZIP Code,ZIP code
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,0.16,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.936527,0.936527
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,0.15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.924872,0.924872
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.977892,0.977892
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,0.27,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.970931,0.970931
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,0.10,0.5,0.0,0.0,0.0,0.0,0.0,1.0,0.939080,0.939080

In [39]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Personal Loan')   # izoh: Target qiymat scalimng qilinmaydi

In [40]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Securities Account', 'CD Account', 'Online',
       'CreditCard', 'ZIP  Code', 'ZIP  code '],
      dtype='object')

In [41]:
df[num_col]=scaler.fit_transform(df[num_col])

In [42]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,ZIP Code,ZIP code
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,0.16,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.936527,0.936527
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,0.15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.924872,0.924872
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.977892,0.977892
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,0.27,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.970931,0.970931
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,0.10,0.5,0.0,0.0,0.0,0.0,0.0,1.0,0.939080,0.939080

In [ ]:
#2-usul
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Personal Loan')  # izoh: Target qiymat scalimng qilinmaydi
for col in num_col:
 
    df[col]=scaler.fit_transform(df[[col]])

In [46]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,ZIP Code,ZIP code
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,0.16,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.936527,0.936527
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,0.15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.924872,0.924872
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.977892,0.977892
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,0.27,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.970931,0.970931
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,0.10,0.5,0.0,0.0,0.0,0.0,0.0,1.0,0.939080,0.939080