# Algorithms

In [141]:
import pandas as pd 
df=pd.read_csv('Bank_Personal_Loan_Modelling.csv')

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 4995 non-null   float64
 2   Experience          5000 non-null   int64
 3   Income              4995 non-null   float64
 4   ZIP Code            4995 non-null   float64
 5   Family              4995 non-null   float64
 6   CCAvg               4995 non-null   float64
 7   Education           4995 non-null   float64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
 14  City                88 non-null     object
 15  Code                24 non-null     object
dtypes: float64(6), int64(8), object(2)
memory usage: 625.1+ KB

In [143]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

In [144]:
encoder

LabelEncoder()

In [145]:
from sklearn.linear_model import LinearRegression,LogisticRegression

In [146]:
lr=LinearRegression()

In [147]:
lr

LinearRegression()

In [148]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [10]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 4995 non-null   float64
 2   Experience          5000 non-null   int64
 3   Income              4995 non-null   float64
 4   ZIP Code            4995 non-null   float64
 5   Family              4995 non-null   float64
 6   CCAvg               4995 non-null   float64
 7   Education           4995 non-null   float64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
 14  City                88 non-null     object
 15  Code                24 non-null     object
dtypes: float64(6), int64(8), object(2)
memory usage: 625.1+ KB

In [149]:
df.drop('City',axis=1,inplace=True)
df.drop('Code',axis=1,inplace=True)
df.drop('ID',axis=1,inplace=True)

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 4995 non-null   float64
 1   Experience          5000 non-null   int64
 2   Income              4995 non-null   float64
 3   ZIP Code            4995 non-null   float64
 4   Family              4995 non-null   float64
 5   CCAvg               4995 non-null   float64
 6   Education           4995 non-null   float64
 7   Mortgage            5000 non-null   int64
 8   Personal Loan       5000 non-null   int64
 9   Securities Account  5000 non-null   int64
 10  CD Account          5000 non-null   int64
 11  Online              5000 non-null   int64
 12  CreditCard          5000 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 507.9 KB

In [169]:
df.dropna(inplace=True)

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4991 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 4991 non-null   float64
 1   Experience          4991 non-null   int64
 2   Income              4991 non-null   float64
 3   ZIP Code            4991 non-null   float64
 4   Family              4991 non-null   float64
 5   CCAvg               4991 non-null   float64
 6   Education           4991 non-null   float64
 7   Mortgage            4991 non-null   int64
 8   Personal Loan       4991 non-null   int64
 9   Securities Account  4991 non-null   int64
 10  CD Account          4991 non-null   int64
 11  Online              4991 non-null   int64
 12  CreditCard          4991 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 545.9 KB

In [171]:
df.head()

,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25.0,1,49.0,91107.0,4.0,1.6,1.0,0,0,1,0,0,0
1,45.0,19,34.0,90089.0,3.0,1.5,1.0,0,0,1,0,0,0
2,39.0,15,11.0,94720.0,1.0,1.0,1.0,0,0,0,0,0,0
3,35.0,9,100.0,94112.0,1.0,2.7,2.0,0,0,0,0,0,0
4,35.0,8,45.0,91330.0,4.0,1.0,2.0,0,0,0,0,0,1

In [172]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [173]:
scaler

MinMaxScaler()

In [174]:
for col in df.columns:
    df[col]=scaler.fit_transform(df[[col]])

In [175]:
df.head()

,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,0.045455,0.086957,0.189815,0.936527,1.000000,0.16,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.500000,0.478261,0.120370,0.924872,0.666667,0.15,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.363636,0.391304,0.013889,0.977892,0.000000,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.272727,0.260870,0.425926,0.970931,0.000000,0.27,0.5,0.0,0.0,0.0,0.0,0.0,0.0
4,0.272727,0.239130,0.171296,0.939080,1.000000,0.10,0.5,0.0,0.0,0.0,0.0,0.0,1.0

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4991 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 4991 non-null   float64
 1   Experience          4991 non-null   float64
 2   Income              4991 non-null   float64
 3   ZIP Code            4991 non-null   float64
 4   Family              4991 non-null   float64
 5   CCAvg               4991 non-null   float64
 6   Education           4991 non-null   float64
 7   Mortgage            4991 non-null   float64
 8   Personal Loan       4991 non-null   float64
 9   Securities Account  4991 non-null   float64
 10  CD Account          4991 non-null   float64
 11  Online              4991 non-null   float64
 12  CreditCard          4991 non-null   float64
dtypes: float64(13)
memory usage: 545.9 KB

In [177]:
x----inputlar
y--output

NameError: name 'inputlar' is not defined

In [ ]:
num_col=df.select_dtypes(include=['float64']).columns

In [ ]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4991 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  4991 non-null   float64
 1   Age                 4991 non-null   float64
 2   Experience          4991 non-null   float64
 3   Income              4991 non-null   float64
 4   ZIP Code            4991 non-null   float64
 5   Family              4991 non-null   float64
 6   CCAvg               4991 non-null   float64
 7   Education           4991 non-null   float64
 8   Mortgage            4991 non-null   float64
 9   Personal Loan       4991 non-null   float64
 10  Securities Account  4991 non-null   float64
 11  CD Account          4991 non-null   float64
 12  Online              4991 non-null   float64
 13  CreditCard          4991 non-null   float64
dtypes: float64(14)
memory usage: 584.9 KB

In [ ]:
x=df.drop('Personal Loan',axis=1)

In [ ]:
y=df['Personal Loan'].astype(int)

In [ ]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal Loan, Length: 4991, dtype: int32

In [ ]:
x

,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,25.0,1,49.0,91107.0,4.0,1.6,1.0,0,1,0,0,0
1,45.0,19,34.0,90089.0,3.0,1.5,1.0,0,1,0,0,0
2,39.0,15,11.0,94720.0,1.0,1.0,1.0,0,0,0,0,0
3,35.0,9,100.0,94112.0,1.0,2.7,2.0,0,0,0,0,0
4,35.0,8,45.0,91330.0,4.0,1.0,2.0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29.0,3,40.0,92697.0,1.0,1.9,3.0,0,0,0,1,0
4996,30.0,4,15.0,92037.0,4.0,0.4,1.0,85,0,0,1,0
4997,63.0,39,24.0,93023.0,2.0,0.3,3.0,0,0,0,0,0
4998,65.0,40,49.0,90034.0,3.0,0.5,2.0,0,0,0,1,0
4999,28.0,4,83.0,92612.0,3.0,0.8,1.0,0,0,0,1,1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
x_train.shape

(3493, 12)

In [ ]:
x_test.shape

(1498, 12)

In [ ]:
y_train.shape

(3493,)

In [ ]:
y_test.shape

(1498,)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_reg=LogisticRegression()

In [ ]:
log_reg

LogisticRegression()

In [ ]:
log_reg.fit(x_train,y_train)

c:\Users\davro\.jupyter\New folder\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred=log_reg.predict(x_test)

In [ ]:
y_pred[1:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 0])

# Evaluation

In [178]:
from sklearn.metrics import accuracy_score

In [179]:
score=accuracy_score(y_test,y_pred)

In [69]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.9479479479479479

In [100]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.948948948948949

In [114]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.9506008010680908

In [180]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.9352469959946595