In [48]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [49]:
df = pd.read_csv('bank_transactions_data_2_augmented_clean_2.csv')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  object
 1   AccountID            50000 non-null  object
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  object
 4   TransactionType      50000 non-null  object
 5   Location             50000 non-null  object
 6   DeviceID             50000 non-null  object
 7   IP Address           50000 non-null  object
 8   MerchantID           50000 non-null  object
 9   Channel              50000 non-null  object
 10  CustomerAge          50000 non-null  int64
 11  CustomerOccupation   50000 non-null  object
 12  TransactionDuration  50000 non-null  int64
 13  LoginAttempts        50000 non-null  int64
 14  AccountBalance       50000 non-null  float64
dtypes: float64(2), int64(3), object(10)
memory usage: 5.7+ MB

In [51]:
df.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
3,TX000004,AC00070,184.50,5/5/2023 16:32,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
4,TX000005,AC00411,13.45,10/16/2023 17:51,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40

#### writing a function that handles missing values in a dataset

In [52]:
def missing_values(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype != 'object':
                df[col] = df[col].fillna(df[col].mean(), inplace=True)
            else:
                df[col] = df[col].fillna(df[col].mode()[0], inplace=True)
    return df

In [53]:
missing_values(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  object
 1   AccountID            50000 non-null  object
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  object
 4   TransactionType      50000 non-null  object
 5   Location             50000 non-null  object
 6   DeviceID             50000 non-null  object
 7   IP Address           50000 non-null  object
 8   MerchantID           50000 non-null  object
 9   Channel              50000 non-null  object
 10  CustomerAge          50000 non-null  int64
 11  CustomerOccupation   50000 non-null  object
 12  TransactionDuration  50000 non-null  int64
 13  LoginAttempts        50000 non-null  int64
 14  AccountBalance       50000 non-null  float64
dtypes: float64(2), int64(3), object(10)
memory usage: 5.7+ MB

#### Writing a function that deals with encoding

In [54]:
encoder = LabelEncoder()

In [55]:
def encoding(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            if df[col].nunique() <=3:
                dummies = pd.get_dummies(df[col], prefix='col', dtype=int)
                df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
            else:
                df[col] = encoder.fit_transform(df[col])
    return df

In [56]:
encoding(df)

,TransactionID,AccountID,TransactionAmount,TransactionDate,Location,DeviceID,IP Address,MerchantID,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,col_Credit,col_Debit,col_ATM,col_Branch,col_Online
0,0,126,14.09,3253,36,365,186,14,70,0,81,1,5112.21,0,1,1,0,0
1,1,450,376.24,4569,15,50,82,51,68,0,141,1,13758.91,0,1,1,0,0
2,2,18,126.29,4796,23,229,343,8,19,3,56,1,1122.35,0,1,0,0,1
3,3,68,184.50,4162,33,182,300,1,26,3,25,1,8569.06,0,1,0,0,1
4,4,406,13.45,686,1,298,501,90,26,3,198,1,7429.40,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,310,69.23,370,19,529,433,96,69,0,69,1,6020.29,0,1,0,0,1
49996,49996,365,514.53,278,15,572,112,60,46,1,143,1,6371.51,0,1,1,0,0
49997,49997,273,118.39,1618,29,211,150,28,33,0,296,1,749.34,0,1,0,0,1
49998,49998,6,446.99,3418,19,315,88,81,58,0,11,1,10915.11,0,1,1,0,0
49999,49999,422,84.82,1281,9,343,270,77,31,0,23,1,842.56,0,1,0,1,0

#### Writing a function that scales given dataset.

In [57]:
def scaling(df):
    for col in df.columns:
        if df[col].dtype != "object":
            scaler = MinMaxScaler()
            scaler
            df[col] = scaler.fit_transform(df[[col]])
    return df

In [64]:
preprocessed_df = missing_values(scaling(encoding(df)))
preprocessed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  float64
 1   AccountID            50000 non-null  float64
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  float64
 4   Location             50000 non-null  float64
 5   DeviceID             50000 non-null  float64
 6   IP Address           50000 non-null  float64
 7   MerchantID           50000 non-null  float64
 8   CustomerAge          50000 non-null  float64
 9   CustomerOccupation   50000 non-null  float64
 10  TransactionDuration  50000 non-null  float64
 11  LoginAttempts        50000 non-null  float64
 12  AccountBalance       50000 non-null  float64
 13  col_Credit           50000 non-null  float64
 14  col_Debit            50000 non-null  float64
 15  col_ATM              50000 non-null  float64
 16  col_Branch           50000 non-null  float64
 17  col_Online           50000 non-null  float64
dtypes: float64(18)
memory usage: 6.9 MB