#### Final project

In [85]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, RobustScaler, StandardScaler

df = pd.read_csv('autos.csv')

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  object
 2   name                 371528 non-null  object
 3   seller               371528 non-null  object
 4   offerType            371528 non-null  object
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  object
 7   vehicleType          333659 non-null  object
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  object
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  object
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  object
 15  brand                371528 non-null  object
 16  notRepairedDamage    299468 non-null  object
 17  dateCreated          371528 non-null  object
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  object
dtypes: int64(8), object(13)
memory usage: 59.5+ MB

#### Handling missing values

In [87]:
df.isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [88]:
df.dropna(inplace=True)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 260956 entries, 3 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                260956 non-null  int64
 1   dateCrawled          260956 non-null  object
 2   name                 260956 non-null  object
 3   seller               260956 non-null  object
 4   offerType            260956 non-null  object
 5   price                260956 non-null  int64
 6   abtest               260956 non-null  object
 7   vehicleType          260956 non-null  object
 8   yearOfRegistration   260956 non-null  int64
 9   gearbox              260956 non-null  object
 10  powerPS              260956 non-null  int64
 11  model                260956 non-null  object
 12  kilometer            260956 non-null  int64
 13  monthOfRegistration  260956 non-null  int64
 14  fuelType             260956 non-null  object
 15  brand                260956 non-null  object
 16  notRepairedDamage    260956 non-null  object
 17  dateCreated          260956 non-null  object
 18  nrOfPictures         260956 non-null  int64
 19  postalCode           260956 non-null  int64
 20  lastSeen             260956 non-null  object
dtypes: int64(8), object(13)
memory usage: 43.8+ MB

#### Encoding

In [90]:
encoder = LabelEncoder()
encoder

LabelEncoder()

In [91]:
for col in df.columns:
    if df[col].dtype == "object":
        if df[col].nunique() <= 5:
            dummies = pd.get_dummies(df[col], prefix='encoded', dtype=int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
        else:
            df[col] = encoder.fit_transform(df[col])

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 260956 entries, 3 to 371527
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                260956 non-null  int64
 1   dateCrawled          260956 non-null  int32
 2   name                 260956 non-null  int32
 3   price                260956 non-null  int64
 4   vehicleType          260956 non-null  int32
 5   yearOfRegistration   260956 non-null  int64
 6   powerPS              260956 non-null  int64
 7   model                260956 non-null  int32
 8   kilometer            260956 non-null  int64
 9   monthOfRegistration  260956 non-null  int64
 10  fuelType             260956 non-null  int32
 11  brand                260956 non-null  int32
 12  dateCreated          260956 non-null  int32
 13  nrOfPictures         260956 non-null  int64
 14  postalCode           260956 non-null  int64
 15  lastSeen             260956 non-null  int32
 16  encoded_gewerblich   260956 non-null  int32
 17  encoded_privat       260956 non-null  int32
 18  encoded_Angebot      260956 non-null  int32
 19  encoded_Gesuch       260956 non-null  int32
 20  encoded_control      260956 non-null  int32
 21  encoded_test         260956 non-null  int32
 22  encoded_automatik    260956 non-null  int32
 23  encoded_manuell      260956 non-null  int32
 24  encoded_ja           260956 non-null  int32
 25  encoded_nein         260956 non-null  int32
dtypes: int32(18), int64(8)
memory usage: 35.8 MB

In [93]:
df.head()

,index,dateCrawled,name,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,...,encoded_gewerblich,encoded_privat,encoded_Angebot,encoded_Gesuch,encoded_control,encoded_test,encoded_automatik,encoded_manuell,encoded_ja,encoded_nein
3,3,80673,49852,1500,4,2001,75,118,150000,6,...,0,1,1,0,0,1,0,1,0,1
4,4,175599,110371,3600,4,2008,69,103,90000,7,...,0,1,1,0,0,1,0,1,0,1
5,5,206288,17693,650,6,1995,102,11,150000,10,...,0,1,1,0,0,1,0,1,1,0
6,6,184645,94170,2200,2,2004,109,8,150000,8,...,0,1,1,0,0,1,0,1,0,1
7,7,107214,120738,0,6,1980,50,40,40000,7,...,0,1,1,0,0,1,0,1,0,1

#### Scaling

##### MinMaxScaler is used

In [94]:
scaler = StandardScaler()
scaler

StandardScaler()

In [95]:
for col in df.columns:
    if df[col].dtype!= "object":
        df[col] = scaler.fit_transform(df[[col]])

In [96]:
df.head()

,index,dateCrawled,name,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,...,encoded_gewerblich,encoded_privat,encoded_Angebot,encoded_Gesuch,encoded_control,encoded_test,encoded_automatik,encoded_manuell,encoded_ja,encoded_nein
3,-1.731267,-0.429318,-0.569306,-0.019541,-0.243508,-0.354645,-0.353341,0.253672,0.651005,-0.052588,...,-0.002768,0.002768,0.003915,-0.003915,-0.962091,0.962091,-0.55172,0.55172,-0.346760,0.346760
4,-1.731258,1.107474,0.807802,-0.013424,-0.243508,0.720269,-0.394641,0.045520,-0.854713,0.235484,...,-0.002768,0.002768,0.003915,-0.003915,-0.962091,0.962091,-0.55172,0.55172,-0.346760,0.346760
5,-1.731249,1.604309,-1.301083,-0.022017,0.925133,-1.276000,-0.167489,-1.231147,0.651005,1.099700,...,-0.002768,0.002768,0.003915,-0.003915,-0.962091,0.962091,-0.55172,0.55172,2.883839,-2.883839
6,-1.731239,1.253923,0.439149,-0.017502,-1.412149,0.106033,-0.119305,-1.272778,0.651005,0.523556,...,-0.002768,0.002768,0.003915,-0.003915,-0.962091,0.962091,-0.55172,0.55172,-0.346760,0.346760
7,-1.731230,0.000364,1.043703,-0.023910,0.925133,-3.579387,-0.525425,-0.828719,-2.109478,0.235484,...,-0.002768,0.002768,0.003915,-0.003915,-0.962091,0.962091,-0.55172,0.55172,-0.346760,0.346760

#### Model selection

In [97]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [98]:
lr

LinearRegression()

In [99]:
x = df.drop('price', axis=1)
y = df['price']

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [102]:
lr.fit(x_train, y_train)

LinearRegression()

In [103]:
y_prediction = lr.predict(x_test)

In [104]:
y_prediction

array([-0.01912539,  0.00340267, -0.0094022 , ..., -0.00124353,
       -0.02683882, -0.0224164 ])

In [105]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [106]:
mae=mean_absolute_error(y_test,y_prediction)
mse=mean_squared_error(y_test,y_prediction)
r2=r2_score(y_test,y_prediction)

In [107]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 0.018255016084951173
mse: 0.03275240145437402
r2: 0.0009769827281767007