# Final Project

In [54]:
import pandas as pd

In [55]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_12/Indian_Kids_Screen_Time.csv')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     6494 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

## Filling missing values

In [57]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype == 'object':
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
            df[col].fillna(df[col].mean(), inplace=True)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     9712 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

# Encoding

In [59]:
df['Gender'].value_counts()

Gender
Male      4942
Female    4770
Name: count, dtype: int64

In [60]:
df = pd.get_dummies(df, columns=['Gender'], prefix='gender', dtype=int)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 2   Primary_Device                     9712 non-null   object
 3   Exceeded_Recommended_Limit         9712 non-null   bool
 4   Educational_to_Recreational_Ratio  9712 non-null   float64
 5   Health_Impacts                     9712 non-null   object
 6   Urban_or_Rural                     9712 non-null   object
 7   gender_Female                      9712 non-null   int32
 8   gender_Male                        9712 non-null   int32
dtypes: bool(1), float64(2), int32(2), int64(1), object(3)
memory usage: 540.7+ KB

In [62]:
df['Primary_Device'].value_counts()

Primary_Device
Smartphone    4568
TV            2487
Laptop        1433
Tablet        1224
Name: count, dtype: int64

In [63]:
df['Primary_Device_freq'] = df['Primary_Device'].map(df['Primary_Device'].value_counts())
df.drop(columns='Primary_Device', axis=1, inplace=True)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 2   Exceeded_Recommended_Limit         9712 non-null   bool
 3   Educational_to_Recreational_Ratio  9712 non-null   float64
 4   Health_Impacts                     9712 non-null   object
 5   Urban_or_Rural                     9712 non-null   object
 6   gender_Female                      9712 non-null   int32
 7   gender_Male                        9712 non-null   int32
 8   Primary_Device_freq                9712 non-null   int64
dtypes: bool(1), float64(2), int32(2), int64(2), object(2)
memory usage: 540.7+ KB

In [65]:
df['Exceeded_Recommended_Limit'].value_counts()

Exceeded_Recommended_Limit
True     8301
False    1411
Name: count, dtype: int64

In [66]:
df['Exceeded_Recommended_Limit'] = df['Exceeded_Recommended_Limit'].astype(int)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 2   Exceeded_Recommended_Limit         9712 non-null   int32
 3   Educational_to_Recreational_Ratio  9712 non-null   float64
 4   Health_Impacts                     9712 non-null   object
 5   Urban_or_Rural                     9712 non-null   object
 6   gender_Female                      9712 non-null   int32
 7   gender_Male                        9712 non-null   int32
 8   Primary_Device_freq                9712 non-null   int64
dtypes: float64(2), int32(3), int64(2), object(2)
memory usage: 569.2+ KB

In [68]:
df['Health_Impacts'].value_counts()

Health_Impacts
Poor Sleep                                       5486
Poor Sleep, Eye Strain                            979
Eye Strain                                        644
Poor Sleep, Anxiety                               608
Poor Sleep, Obesity Risk                          452
Anxiety                                           385
Poor Sleep, Eye Strain, Anxiety                   258
Obesity Risk                                      252
Poor Sleep, Eye Strain, Obesity Risk              188
Eye Strain, Anxiety                               135
Eye Strain, Obesity Risk                          106
Poor Sleep, Anxiety, Obesity Risk                  78
Anxiety, Obesity Risk                              69
Poor Sleep, Eye Strain, Anxiety, Obesity Risk      37
Eye Strain, Anxiety, Obesity Risk                  35
Name: count, dtype: int64

In [69]:
df['Health_Impacts_freq'] = df['Health_Impacts'].map(df['Health_Impacts'].value_counts())
df.drop(columns='Health_Impacts', axis=1, inplace=True)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 2   Exceeded_Recommended_Limit         9712 non-null   int32
 3   Educational_to_Recreational_Ratio  9712 non-null   float64
 4   Urban_or_Rural                     9712 non-null   object
 5   gender_Female                      9712 non-null   int32
 6   gender_Male                        9712 non-null   int32
 7   Primary_Device_freq                9712 non-null   int64
 8   Health_Impacts_freq                9712 non-null   int64
dtypes: float64(2), int32(3), int64(3), object(1)
memory usage: 569.2+ KB

In [71]:
df['Urban_or_Rural'].value_counts()

Urban_or_Rural
Urban    6851
Rural    2861
Name: count, dtype: int64

In [72]:
custom_mapping_dict = {
    'Urban':1,
    'Rural':0
}

df['Urban_or_Rural_ordinal'] = df['Urban_or_Rural'].map(custom_mapping_dict)


df.drop(columns='Urban_or_Rural', axis=1, inplace=True)

In [73]:
df.sample(5)

,Age,Avg_Daily_Screen_Time_hr,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,gender_Female,gender_Male,Primary_Device_freq,Health_Impacts_freq,Urban_or_Rural_ordinal
3035,16,5.64,1,0.35,0,1,2487,5486,1
9661,10,4.11,1,0.40,0,1,2487,188,1
5121,15,4.41,1,0.39,0,1,1224,608,1
3416,17,3.01,1,0.46,0,1,2487,252,0
190,8,1.13,0,0.41,1,0,2487,5486,1

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 2   Exceeded_Recommended_Limit         9712 non-null   int32
 3   Educational_to_Recreational_Ratio  9712 non-null   float64
 4   gender_Female                      9712 non-null   int32
 5   gender_Male                        9712 non-null   int32
 6   Primary_Device_freq                9712 non-null   int64
 7   Health_Impacts_freq                9712 non-null   int64
 8   Urban_or_Rural_ordinal             9712 non-null   int64
dtypes: float64(2), int32(3), int64(4)
memory usage: 569.2 KB

# Scaling

In [78]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, LabelEncoder

In [79]:
num_col=df.select_dtypes(include=['int64','float64','int32']).columns.tolist()

In [80]:
minmax = MinMaxScaler()

In [81]:
minmax

MinMaxScaler()

In [82]:
df[num_col] = minmax.fit_transform(df[num_col])

In [83]:
df

,Age,Avg_Daily_Screen_Time_hr,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,gender_Female,gender_Male,Primary_Device_freq,Health_Impacts_freq,Urban_or_Rural_ordinal
0,0.6,0.287257,1.0,0.400000,0.0,1.0,1.000000,0.173179,1.0
1,0.3,0.331893,1.0,0.000000,1.0,0.0,0.062500,1.000000,1.0
2,1.0,0.268539,1.0,0.066667,1.0,0.0,0.377691,1.000000,1.0
3,0.7,0.087113,0.0,0.300000,1.0,0.0,0.062500,1.000000,1.0
4,0.4,0.424046,1.0,0.633333,1.0,0.0,1.000000,0.105118,1.0
...,...,...,...,...,...,...,...,...,...
9707,0.9,0.234701,1.0,0.466667,0.0,1.0,1.000000,1.000000,1.0
9708,0.9,0.318934,1.0,0.333333,1.0,0.0,1.000000,1.000000,0.0
9709,0.8,0.404608,1.0,0.300000,0.0,1.0,1.000000,0.040910,0.0
9710,0.9,0.403168,1.0,0.433333,0.0,1.0,0.377691,1.000000,1.0
9711,0.7,0.440605,1.0,0.100000,1.0,0.0,0.377691,0.064208,1.0

# Model Training

In [84]:
# Input columns

x = df.drop('Urban_or_Rural_ordinal', axis=1)

x

,Age,Avg_Daily_Screen_Time_hr,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,gender_Female,gender_Male,Primary_Device_freq,Health_Impacts_freq
0,0.6,0.287257,1.0,0.400000,0.0,1.0,1.000000,0.173179
1,0.3,0.331893,1.0,0.000000,1.0,0.0,0.062500,1.000000
2,1.0,0.268539,1.0,0.066667,1.0,0.0,0.377691,1.000000
3,0.7,0.087113,0.0,0.300000,1.0,0.0,0.062500,1.000000
4,0.4,0.424046,1.0,0.633333,1.0,0.0,1.000000,0.105118
...,...,...,...,...,...,...,...,...
9707,0.9,0.234701,1.0,0.466667,0.0,1.0,1.000000,1.000000
9708,0.9,0.318934,1.0,0.333333,1.0,0.0,1.000000,1.000000
9709,0.8,0.404608,1.0,0.300000,0.0,1.0,1.000000,0.040910
9710,0.9,0.403168,1.0,0.433333,0.0,1.0,0.377691,1.000000
9711,0.7,0.440605,1.0,0.100000,1.0,0.0,0.377691,0.064208

In [85]:
# Output(target) column

y = df['Urban_or_Rural_ordinal'].astype(int)

y

0       1
1       1
2       1
3       1
4       1
       ..
9707    1
9708    0
9709    0
9710    1
9711    1
Name: Urban_or_Rural_ordinal, Length: 9712, dtype: int32

In [87]:
# splitting data into train and test

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

model=DecisionTreeClassifier()

In [89]:
model

DecisionTreeClassifier()

In [90]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [91]:
# Prediction 

y_prediction = model.predict(x_test)

In [92]:
y_prediction

array([1, 0, 1, ..., 0, 1, 0])

In [93]:
from sklearn.metrics import accuracy_score

In [95]:
accuracy = accuracy_score(y_test, y_prediction)

In [99]:
accuracy*100

56.51055069480185