In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('heart_cleveland_upload.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    int64
 1   gender     297 non-null    int64
 2   cp         297 non-null    int64
 3   trestbps   297 non-null    int64
 4   chol       297 non-null    int64
 5   fbs        297 non-null    int64
 6   restecg    297 non-null    int64
 7   thalach    297 non-null    int64
 8   exang      297 non-null    int64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    int64
 11  ca         297 non-null    int64
 12  thal       297 non-null    int64
 13  condition  297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

In [4]:
df.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

# Random Forest

In [ ]:
x=df.drop('condition',axis=1)

In [19]:
x.head(10)

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,69.0,1.0,0.0,160.0,234.0,1.0,2.0,131.0,0.0,0.1,1.0,1.0,0.0
1,69.0,0.0,0.0,140.0,239.0,0.0,0.0,151.0,0.0,1.8,0.0,2.0,0.0
2,66.0,0.0,0.0,150.0,226.0,0.0,0.0,114.0,0.0,2.6,2.0,0.0,0.0
3,65.0,1.0,0.0,138.0,282.0,1.0,2.0,174.0,0.0,1.4,1.0,1.0,0.0
4,64.0,1.0,0.0,110.0,211.0,0.0,2.0,144.0,1.0,1.8,1.0,0.0,0.0
5,64.0,1.0,0.0,170.0,227.0,0.0,2.0,155.0,0.0,0.6,1.0,0.0,2.0
6,63.0,1.0,0.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,2.0,0.0,1.0
7,61.0,1.0,0.0,134.0,234.0,0.0,0.0,145.0,0.0,2.6,1.0,2.0,0.0
8,60.0,0.0,0.0,150.0,240.0,0.0,0.0,171.0,0.0,0.9,0.0,0.0,0.0
9,59.0,1.0,0.0,178.0,270.0,0.0,2.0,145.0,0.0,4.2,2.0,0.0,2.0

In [ ]:
y=df['condition']

In [31]:
y.value_counts()

condition
0    160
1    137
Name: count, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf=RandomForestClassifier()

In [26]:
rf

RandomForestClassifier()

In [32]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [33]:
y_pred=rf.predict(x_test)

In [47]:
y_pred

array([1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 0.])

In [35]:
x_test

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
167,66.0,0.0,3.0,178.0,228.0,1.0,0.0,165.0,1.0,1.0,1.0,2.0,2.0
211,59.0,1.0,3.0,140.0,177.0,0.0,0.0,162.0,1.0,0.0,0.0,1.0,2.0
63,41.0,1.0,1.0,135.0,203.0,0.0,0.0,132.0,0.0,0.0,1.0,0.0,1.0
154,37.0,0.0,2.0,120.0,215.0,0.0,0.0,170.0,0.0,0.0,0.0,0.0,0.0
5,64.0,1.0,0.0,170.0,227.0,0.0,2.0,155.0,0.0,0.6,1.0,0.0,2.0
77,68.0,0.0,2.0,120.0,211.0,0.0,2.0,115.0,0.0,1.5,1.0,0.0,0.0
183,63.0,1.0,3.0,130.0,330.0,1.0,2.0,132.0,1.0,1.8,0.0,3.0,2.0
158,70.0,1.0,3.0,130.0,322.0,0.0,2.0,109.0,0.0,2.4,1.0,3.0,0.0
9,59.0,1.0,0.0,178.0,270.0,0.0,2.0,145.0,0.0,4.2,2.0,0.0,2.0
139,44.0,1.0,2.0,130.0,233.0,0.0,0.0,179.0,1.0,0.4,0.0,0.0,0.0
285,43.0,1.0,3.0,150.0,247.0,0.0,0.0,171.0,0.0,1.5,0.0,0.0,0.0
78,68.0,1.0,2.0,118.0,277.0,0.0,0.0,151.0,0.0,1.0,0.0,1.0,2.0
92,61.0,1.0,2.0,150.0,243.0,1.0,0.0,137.0,1.0,1.0,1.0,0.0,0.0
101,58.0,0.0,2.0,120.0,340.0,0.0,0.0,172.0,0.0,0.0,0.0,0.0,0.0
42,55.0,0.0,1.0,132.0,342.0,0.0,0.0,166.0,0.0,1.2,0.0,0.0,0.0
222,58.0,1.0,3.0,100.0,234.0,0.0,0.0,156.0,0.0,0.1,0.0,1.0,2.0
283,43.0,0.0,3.0,132.0,341.0,1.0,2.0,136.0,1.0,3.0,1.0,0.0,2.0
33,57.0,0.0,1.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,1.0,1.0,0.0
263,50.0,1.0,3.0,150.0,243.0,0.0,2.0,128.0,0.0,2.6,1.0,0.0,2.0
148,41.0,1.0,2.0,112.0,250.0,0.0,0.0,179.0,0.0,0.0,0.0,0.0,0.0
245,54.0,1.0,3.0,120.0,188.0,0.0,0.0,113.0,0.0,1.4,1.0,1.0,2.0
45,54.0,1.0,1.0,192.0,283.0,0.0,2.0,195.0,0.0,0.0,0.0,1.0,2.0
60,44.0,1.0,1.0,130.0,219.0,0.0,2.0,188.0,0.0,0.0,0.0,0.0,0.0
46,52.0,1.0,1.0,120.0,325.0,0.0,0.0,172.0,0.0,0.2,0.0,0.0,0.0
278,45.0,1.0,3.0,115.0,260.0,0.0,2.0,185.0,0.0,0.0,0.0,0.0,0.0
237,56.0,1.0,3.0,132.0,184.0,0.0,2.0,105.0,1.0,2.1,1.0,1.0,1.0
175,64.0,1.0,3.0,145.0,212.0,0.0,2.0,132.0,0.0,2.0,1.0,2.0,1.0
234,56.0,0.0,3.0,200.0,288.0,1.0,2.0,133.0,1.0,4.0,2.0,2.0,2.0
17,51.0,1.0,0.0,125.0,213.0,0.0,2.0,125.0,1.0,1.4,0.0,1.0,0.0
279,44.0,1.0,3.0,120.0,169.0,0.0,0.0,144.0,1.0,2.8,2.0,0.0,1.0
111,54.0,1.0,2.0,150.0,232.0,0.0,2.0,165.0,0.0,1.6,0.0,0.0,2.0
219,58.0,0.0,3.0,170.0,225.0,1.0,2.0,146.0,1.0,2.8,1.0,2.0,1.0
24,71.0,0.0,1.0,160.0,302.0,0.0,0.0,162.0,0.0,0.4,0.0,2.0,0.0
82,66.0,0.0,2.0,146.0,278.0,0.0,2.0,152.0,0.0,0.0,1.0,1.0,0.0
7,61.0,1.0,0.0,134.0,234.0,0.0,0.0,145.0,0.0,2.6,1.0,2.0,0.0
75,69.0,1.0,2.0,140.0,254.0,0.0,2.0,146.0,0.0,2.0,1.0,3.0,2.0
108,54.0,1.0,2.0,120.0,258.0,0.0,2.0,147.0,0.0,0.4,1.0,0.0,2.0
84,65.0,0.0,2.0,155.0,269.0,0.0,0.0,148.0,0.0,0.8,0.0,0.0,0.0
90,62.0,1.0,2.0,130.0,231.0,0.0,0.0,146.0,0.0,1.8,1.0,3.0,2.0
73,71.0,0.0,2.0,110.0,265.0,1.0,2.0,130.0,0.0,0.0,0.0,1.0,0.0
116,52.0,0.0,2.0,136.0,196.0,0.0,2.0,169.0,0.0,0.1,1.0,0.0,0.0
126,50.0,1.0,2.0,140.0,233.0,0.0,0.0,163.0,0.0,0.6,1.0,1.0,2.0
233,57.0,1.0,3.0,132.0,207.0,0.0,0.0,168.0,1.0,0.0,0.0,0.0,2.0
59,44.0,1.0,1.0,120.0,263.0,0.0,0.0,173.0,0.0,0.0,0.0,0.0,2.0
195,61.0,0.0,3.0,130.0,330.0,0.0,2.0,169.0,0.0,0.0,0.0,0.0,0.0
208,59.0,1.0,3.0,110.0,239.0,0.0,2.0,142.0,1.0,1.2,1.0,1.0,2.0
97,59.0,1.0,2.0,150.0,212.0,1.0,0.0,157.0,0.0,1.6,0.0,0.0,0.0
185,62.0,0.0,3.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,2.0,2.0,0.0
176,64.0,0.0,3.0,130.0,303.0,0.0,0.0,122.0,0.0,2.0,1.0,2.0,0.0
124,51.0,0.0,2.0,120.0,295.0,0.0,2.0,157.0,0.0,0.6,0.0,0.0,0.0
93,60.0,1.0,2.0,140.0,185.0,0.0,2.0,155.0,0.0,3.0,1.0,0.0,0.0
294,35.0,1.0,3.0,120.0,198.0,0.0,0.0,130.0,1.0,1.6,1.0,0.0,2.0
182,63.0,0.0,3.0,124.0,197.0,0.0,0.0,136.0,1.0,0.0,1.0,0.0,0.0
275,45.0,1.0,3.0,104.0,208.0,0.0,2.0,148.0,1.0,3.0,1.0,0.0,0.0
192,61.0,1.0,3.0,120.0,260.0,0.0,0.0,140.0,1.0,3.6,1.0,1.0,2.0
292,40.0,1.0,3.0,152.0,223.0,0.0,0.0,181.0,0.0,0.0,0.0,0.0,2.0
25,70.0,1.0,1.0,156.0,245.0,0.0,2.0,143.0,0.0,0.0,0.0,0.0,0.0
224,57.0,1.0,3.0,150.0,276.0,0.0,2.0,112.0,1.0,0.6,1.0,1.0,1.0
6,63.0,1.0,0.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,2.0,0.0,1.0
181,63.0,0.0,3.0,108.0,269.0,0.0,0.0,169.0,1.0,1.8,1.0,2.0,0.0

In [38]:
#Evaluation
from sklearn.metrics import classification_report, accuracy_score

In [39]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [40]:
print(report)
print(score)

              precision    recall  f1-score   support

         0.0       0.76      0.69      0.72        32
         1.0       0.68      0.75      0.71        28

    accuracy                           0.72        60
   macro avg       0.72      0.72      0.72        60
weighted avg       0.72      0.72      0.72        60

0.7166666666666667

In [41]:
#Decision Tree Classifier

In [42]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [43]:
dt=DecisionTreeClassifier()
lg=LogisticRegression()

In [44]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [45]:
y_pred=dt.predict(x_test)

In [46]:
y_pred

array([1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 0.])

In [48]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [49]:
print(report)
print(score)

              precision    recall  f1-score   support

         0.0       0.75      0.66      0.70        32
         1.0       0.66      0.75      0.70        28

    accuracy                           0.70        60
   macro avg       0.70      0.70      0.70        60
weighted avg       0.71      0.70      0.70        60

0.7

In [50]:
#Logistic Regression
lg.fit(x_train,y_train)

c:\Users\davro\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [54]:
y_pred=lg.predict(x_test)

In [55]:
y_pred

array([1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 0.])

In [56]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [57]:
print(report)
print(score)

              precision    recall  f1-score   support

         0.0       0.77      0.72      0.74        32
         1.0       0.70      0.75      0.72        28

    accuracy                           0.73        60
   macro avg       0.73      0.73      0.73        60
weighted avg       0.74      0.73      0.73        60

0.7333333333333333

In [ ]:
# Modelni saqlash
#Joblib

In [ ]:
import joblib

In [64]:
from joblib import dump , load

In [65]:
dump(lg,'yurak_kasalliklari_predikti.joblib')

['yurak_kasalliklari_predikti.joblib']

In [63]:
lg

LogisticRegression()

In [66]:
dump(rf,'kasalliklari_predikti.joblib')

['kasalliklari_predikti.joblib']

In [67]:
model=load('kasalliklari_predikti.joblib')

In [69]:
model.predict(x_test)

array([1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 0., 1., 1., 0., 1.])