In [174]:
import pandas as pd
df=pd.read_csv('heart_disease_uci.csv')

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       916 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        916 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     861 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(6), int64(2), object(8)
memory usage: 115.1+ KB

In [176]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col].fillna(df[col].mode()[0],inplace=True)

In [177]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [178]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        920 non-null    int64
 1   age                       920 non-null    float64
 2   trestbps                  920 non-null    float64
 3   chol                      920 non-null    float64
 4   fbs                       920 non-null    bool
 5   thalch                    920 non-null    float64
 6   exang                     920 non-null    bool
 7   oldpeak                   920 non-null    float64
 8   ca                        920 non-null    float64
 9   num                       920 non-null    int64
 10  gender_Female             920 non-null    int32
 11  gender_Male               920 non-null    int32
 12  dataset_Cleveland         920 non-null    int32
 13  dataset_Hungary           920 non-null    int32
 14  dataset_Switzerland       920 non-null    int32
 15  dataset_VA Long Beach     920 non-null    int32
 16  cp_asymptomatic           920 non-null    int32
 17  cp_atypical angina        920 non-null    int32
 18  cp_non-anginal            920 non-null    int32
 19  cp_typical angina         920 non-null    int32
 20  restecg_lv hypertrophy    920 non-null    int32
 21  restecg_normal            920 non-null    int32
 22  restecg_st-t abnormality  920 non-null    int32
 23  slope_downsloping         920 non-null    int32
 24  slope_flat                920 non-null    int32
 25  slope_upsloping           920 non-null    int32
 26  thal_fixed defect         920 non-null    int32
 27  thal_normal               920 non-null    int32
 28  thal_reversable defect    920 non-null    int32
dtypes: bool(2), float64(6), int32(19), int64(2)
memory usage: 127.7 KB

In [180]:
num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('num')
df[num_col]=scaler.fit_transform(df[num_col])

In [181]:
df.head()

,id,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,num,...,cp_typical angina,restecg_lv hypertrophy,restecg_normal,restecg_st-t abnormality,slope_downsloping,slope_flat,slope_upsloping,thal_fixed defect,thal_normal,thal_reversable defect
0,0.000000,0.714286,0.725,0.386401,True,0.633803,False,0.556818,0.000000,0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.001088,0.795918,0.800,0.474295,False,0.338028,True,0.465909,1.000000,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.002176,0.795918,0.600,0.379768,False,0.485915,True,0.590909,0.666667,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.003264,0.183673,0.650,0.414594,False,0.894366,False,0.693182,0.000000,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.004353,0.265306,0.650,0.338308,False,0.788732,False,0.454545,0.000000,0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        920 non-null    float64
 1   age                       920 non-null    float64
 2   trestbps                  920 non-null    float64
 3   chol                      920 non-null    float64
 4   fbs                       920 non-null    bool
 5   thalch                    920 non-null    float64
 6   exang                     920 non-null    bool
 7   oldpeak                   920 non-null    float64
 8   ca                        920 non-null    float64
 9   num                       920 non-null    int64
 10  gender_Female             920 non-null    float64
 11  gender_Male               920 non-null    float64
 12  dataset_Cleveland         920 non-null    float64
 13  dataset_Hungary           920 non-null    float64
 14  dataset_Switzerland       920 non-null    float64
 15  dataset_VA Long Beach     920 non-null    float64
 16  cp_asymptomatic           920 non-null    float64
 17  cp_atypical angina        920 non-null    float64
 18  cp_non-anginal            920 non-null    float64
 19  cp_typical angina         920 non-null    float64
 20  restecg_lv hypertrophy    920 non-null    float64
 21  restecg_normal            920 non-null    float64
 22  restecg_st-t abnormality  920 non-null    float64
 23  slope_downsloping         920 non-null    float64
 24  slope_flat                920 non-null    float64
 25  slope_upsloping           920 non-null    float64
 26  thal_fixed defect         920 non-null    float64
 27  thal_normal               920 non-null    float64
 28  thal_reversable defect    920 non-null    float64
dtypes: bool(2), float64(26), int64(1)
memory usage: 196.0 KB

# Lasso Regression

In [221]:
from sklearn.linear_model import LinearRegression, Lasso,Ridge

In [207]:
lasso=Lasso(alpha=0.1)

In [208]:
x=df.drop('num',axis=1)

In [209]:
y=df['num']

In [210]:
from sklearn.model_selection import train_test_split

In [211]:
lasso

Lasso(alpha=0.1)

In [212]:
lasso.fit(x_train,y_train)

Lasso(alpha=0.1)

In [213]:
y_pred=lasso.predict(x_test)

In [214]:
from sklearn.metrics import r2_score, mean_absolute_error

In [215]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [ ]:
print(r2)
print(mae)

0.23626216354320095
0.7564841157846129

In [217]:
ridge=Ridge(alpha=0.1)

In [218]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.1)

In [219]:
y_pred=ridge.predict(x_test)

In [220]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(r2)
print(mae)

0.4528799437886093
0.5983221083435563

In [222]:
lr=LinearRegression()

In [228]:
lr.fit(x_train,y_train)

LinearRegression()

In [229]:
y_pred=lr.predict(x_test)

In [230]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(r2)
print(mae)

0.4523564274280638
0.5987365626971974

In [231]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()

In [232]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [233]:
y_pred=rf.predict(x_test)

In [234]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(r2)
print(mae)

0.4744679909427748
0.5045108695652174

In [235]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()

In [237]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [238]:
y_pred=dt.predict(x_test)

In [239]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(r2)
print(mae)

-0.08892548373816389
0.7065217391304348

# Evaluation Classification

In [96]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [97]:
lg

LogisticRegression()

In [98]:
df['num']

0      0
1      2
2      1
3      0
4      0
      ..
915    1
916    0
917    2
918    0
919    1
Name: num, Length: 920, dtype: int64

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
x=df.drop('num',axis=1)

In [101]:
x

,id,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,gender_Female,...,cp_typical angina,restecg_lv hypertrophy,restecg_normal,restecg_st-t abnormality,slope_downsloping,slope_flat,slope_upsloping,thal_fixed defect,thal_normal,thal_reversable defect
0,0.000000,0.714286,0.725000,0.386401,True,0.633803,False,0.556818,0.000000,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.001088,0.795918,0.800000,0.474295,False,0.338028,True,0.465909,1.000000,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.002176,0.795918,0.600000,0.379768,False,0.485915,True,0.590909,0.666667,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.003264,0.183673,0.650000,0.414594,False,0.894366,False,0.693182,0.000000,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.004353,0.265306,0.650000,0.338308,False,0.788732,False,0.454545,0.000000,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,0.995647,0.530612,0.635000,0.552239,True,0.661972,False,0.295455,0.225458,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
916,0.996736,0.693878,0.660662,0.230514,False,0.546096,False,0.395317,0.225458,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.997824,0.551020,0.610000,0.369818,True,0.281690,False,0.295455,0.225458,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
918,0.998912,0.612245,0.660662,0.638474,True,0.546096,False,0.395317,0.225458,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
919,1.000000,0.693878,0.600000,0.421227,False,0.232394,True,0.295455,0.225458,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [102]:
y=df['num']

In [103]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)   # Hold out method

In [104]:
lg.fit(x_train,y_train)

LogisticRegression()

In [105]:
#Predict
y_pred=lg.predict(x_test)

In [106]:
y_pred

array([0, 0, 1, 1, 0, 0, 3, 3, 2, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1,
       2, 1, 1, 2, 2, 1, 3, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 1,
       1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 3, 3, 2, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 3, 1, 0, 3, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 2,
       1, 4, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 3,
       2, 0, 0, 2, 0, 0, 0, 0, 1, 2, 3, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 2, 1, 1], dtype=int64)

In [107]:
y_test

719    1
218    0
537    1
195    3
416    0
      ..
374    0
17     0
668    1
692    3
569    1
Name: num, Length: 184, dtype: int64

In [108]:
from sklearn.metrics import accuracy_score,classification_report, r2_score, mean_absolute_error, mean_squared_error
# from sklearn.metrics import classification_report
# from sklearn.metrics import r2_score
# from sklearn.metrics import mean_absolute_error

In [109]:
score=accuracy_score(y_test,y_pred)
print(score)

0.5815217391304348

In [110]:
# K-Fold cross validation
from sklearn.model_selection import KFold, cross_val_score

In [114]:
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(lg,x,y,cv=kf)

C:\Users\davro\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\davro\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [115]:
print(scores)

[0.45652174 0.64130435 0.64130435 0.59782609 0.63043478 0.64130435
 0.55434783 0.59782609 0.64130435 0.67391304]

In [116]:
print(scores.mean())

0.6076086956521738

In [ ]:
# Decision Tree Classifier

In [117]:
from sklearn.tree import DecisionTreeClassifier

In [118]:
dt=DecisionTreeClassifier()

In [119]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [120]:
y_pred=dt.predict(x_test)

In [121]:
score=accuracy_score(y_test,y_pred)
print(score)

0.5706521739130435

In [122]:
y_pred

array([2, 1, 1, 2, 0, 0, 1, 4, 1, 0, 0, 0, 1, 3, 0, 0, 0, 0, 1, 0, 3, 0,
       0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 3, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 4, 1, 0, 1, 0, 4, 1, 0, 0, 1, 4,
       2, 1, 2, 3, 2, 2, 2, 3, 0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 0, 0, 2, 2,
       2, 1, 0, 0, 1, 0, 1, 4, 0, 0, 0, 0, 2, 2, 3, 2, 1, 0, 1, 0, 0, 2,
       2, 1, 0, 3, 0, 1, 0, 3, 0, 2, 1, 1, 0, 0, 1, 3, 1, 1, 4, 2, 4, 2,
       2, 4, 0, 1, 0, 0, 0, 1, 0, 1, 0, 4, 0, 2, 1, 0, 0, 0, 1, 0, 2, 2,
       2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 0, 3, 0, 1, 3, 0, 0,
       1, 0, 0, 0, 0, 2, 3, 1], dtype=int64)

In [123]:
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(dt,x,y,cv=kf)
print(scores)
print(scores.mean())

[0.52173913 0.63043478 0.59782609 0.57608696 0.61956522 0.61956522
 0.52173913 0.5        0.59782609 0.57608696]
0.5760869565217391

In [124]:
# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [125]:
rf=RandomForestClassifier()

In [126]:
rf

RandomForestClassifier()

In [127]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [128]:
y_pred=rf.predict(x_test)

In [129]:
score=accuracy_score(y_test,y_pred)
print(score)

0.6086956521739131

In [131]:
from sklearn.model_selection import KFold, cross_val_score
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(rf,x,y,cv=kf)
print(scores)
print(scores.mean())

[0.57608696 0.64130435 0.67391304 0.65217391 0.67391304 0.58695652
 0.59782609 0.58695652 0.61956522 0.66304348]
0.6271739130434784

# Evaluation Regression

In [132]:
import pandas as pd
df=pd.read_csv('physics_teacher_jobs_linkedin.csv')

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              847 non-null    object
 1   location           847 non-null    object
 2   publishedAt        847 non-null    object
 3   companyName        844 non-null    object
 4   description        847 non-null    object
 5   applicationsCount  847 non-null    object
 6   contractType       847 non-null    object
 7   experienceLevel    847 non-null    object
 8   workType           846 non-null    object
 9   sector             843 non-null    object
 10  salary             153 non-null    object
dtypes: object(11)
memory usage: 72.9+ KB

In [134]:
df['salary'].value_counts()

salary
$47,096.47/yr - $93,839.67/yr     7
$46,942.00/yr - $95,000.00/yr     5
$63,280.00/yr - $112,776.00/yr    5
$70,829.00/yr - $142,270.00/yr    4
$50,000.00/yr - $64,700.00/yr     3
                                 ..
$34,300.00/yr - $41,500.00/yr     1
$52,114.00/yr - $87,140.00/yr     1
$69,626.00/yr - $109,376.00/yr    1
$50,000.00/yr - $100,000.00/yr    1
$54,281.00/yr - $70,246.00/yr     1
Name: count, Length: 120, dtype: int64

In [135]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              847 non-null    object
 1   location           847 non-null    object
 2   publishedAt        847 non-null    object
 3   companyName        847 non-null    object
 4   description        847 non-null    object
 5   applicationsCount  847 non-null    object
 6   contractType       847 non-null    object
 7   experienceLevel    847 non-null    object
 8   workType           847 non-null    object
 9   sector             847 non-null    object
 10  salary             847 non-null    object
dtypes: object(11)
memory usage: 72.9+ KB

In [137]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              847 non-null    int32
 1   location           847 non-null    int32
 2   publishedAt        847 non-null    int32
 3   companyName        847 non-null    int32
 4   description        847 non-null    int32
 5   applicationsCount  847 non-null    int32
 6   contractType       847 non-null    int32
 7   experienceLevel    847 non-null    int32
 8   workType           847 non-null    int32
 9   sector             847 non-null    int32
 10  salary             847 non-null    int32
dtypes: int32(11)
memory usage: 36.5 KB

In [139]:
df.head()

,title,location,publishedAt,companyName,description,applicationsCount,contractType,experienceLevel,workType,sector,salary
0,407,365,191,355,741,22,1,1,4,10,33
1,627,53,167,364,570,22,1,3,4,31,33
2,421,262,34,270,384,22,1,1,0,7,33
3,274,56,105,263,381,22,4,5,0,8,33
4,393,343,11,342,479,22,1,1,4,31,33

In [140]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [141]:
num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('salary')
df[num_col]=scaler.fit_transform(df[num_col])

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              847 non-null    float64
 1   location           847 non-null    float64
 2   publishedAt        847 non-null    float64
 3   companyName        847 non-null    float64
 4   description        847 non-null    float64
 5   applicationsCount  847 non-null    float64
 6   contractType       847 non-null    float64
 7   experienceLevel    847 non-null    float64
 8   workType           847 non-null    float64
 9   sector             847 non-null    float64
 10  salary             847 non-null    int32
dtypes: float64(10), int32(1)
memory usage: 69.6 KB

In [144]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [145]:
x=df.drop('salary',axis=1)

In [146]:
y=df['salary']

In [147]:
#Lineaer Regression
from sklearn.linear_model import LinearRegression

In [148]:
lr=LinearRegression()

In [149]:
lr.fit(x_train,y_train)

LinearRegression()

In [150]:
y_pred=lr.predict(x_test)

In [151]:
y_pred

array([ 6.13867450e-01,  1.19077086e+00,  1.57659974e+00,  1.41380356e+00,
        9.97323728e-01,  1.39449509e+00,  1.58438987e+00,  2.48847798e-01,
        1.91774469e+00,  1.87933800e-01,  1.86555319e+00,  1.64893712e+00,
        1.63042316e+00,  1.87561627e+00,  1.96000035e+00, -3.69136574e-01,
        3.58447464e-01,  1.39607981e+00,  5.00248626e-01,  9.74824113e-02,
        2.28645231e-01,  1.02182090e+00,  2.61717596e+00,  1.28101305e+00,
        1.09270670e+00,  7.23663609e-02,  2.11302591e+00,  1.92302224e+00,
        8.44838719e-01, -1.45999329e-01, -5.50797599e-02, -9.63015671e-02,
        9.39071510e-02,  1.27683978e-01,  1.02482412e+00,  2.27191120e+00,
        2.06254338e+00,  3.01200254e-01,  2.10814157e+00,  1.04669377e+00,
        1.79992628e-01,  1.60312512e+00,  6.10329870e-01,  1.78693827e+00,
        3.16187840e-01, -5.04518110e-03,  3.37330506e-01,  5.27668043e-01,
        7.66714006e-01,  2.26287575e+00,  1.61387783e+00,  2.28566605e+00,
        1.35763752e+00,  1.90457123e+00,  2.06812798e-01,  1.60264416e-03,
        1.71392021e+00,  1.27531772e+00,  6.52481514e-02,  2.27750255e+00,
        2.55450688e-01,  2.74031673e+00,  9.80146241e-01,  1.29031426e+00,
        1.02648968e+00,  5.21202716e-01, -2.40409757e-01,  1.18594846e-01,
        4.33613802e-01,  8.16237946e-01,  5.90663106e-01,  1.31180639e+00,
        6.59173783e-01,  1.31987365e+00,  2.41607988e-01,  2.25543284e+00,
        1.74426505e+00,  1.93934959e+00,  1.36428312e+00,  1.84126657e-01,
        2.06902760e+00,  1.76902120e+00,  1.73535201e+00, -4.37973695e-02,
        6.47017616e-01,  3.50543995e-01,  2.34932861e+00,  1.98595960e+00,
       -3.33238505e-01,  1.60817493e+00,  1.06639405e-01,  1.59806257e+00,
        5.41023528e-01,  9.39655587e-01, -1.10285542e-01,  1.14477364e+00,
        1.91848769e+00, -2.66231630e-02,  2.27863256e+00,  8.91386706e-01,
       -1.90206345e-01,  1.07350016e+00,  2.10580913e+00,  1.37001673e+00,
        3.98214637e-01,  1.63648695e+00,  1.10994037e+00, -3.16006086e-02,
        2.39068950e+00,  2.58541887e-01,  2.00914090e+00, -1.28163571e-01,
        1.17624935e+00, -2.74527246e-02,  2.19241603e-01,  1.78519308e+00,
        1.64995475e+00,  1.50733942e+00,  1.82824526e+00,  5.26144649e-01,
       -1.19423438e-01,  4.16138570e-01,  1.18454336e+00,  2.03880750e+00,
        8.03880632e-01,  2.48054762e+00, -5.57486824e-02,  1.51185289e+00,
        5.70606664e-01,  1.62517749e+00, -2.96246094e-02,  2.64160892e-01,
        1.57820176e-01,  3.53985712e-01, -2.84612502e-02,  6.43846912e-01,
        6.86547346e-02,  2.09003912e-01,  8.98754718e-01,  1.28642843e+00,
        1.87536228e+00,  1.18727744e+00, -8.23762577e-02,  7.03194653e-01,
        7.58831554e-01,  1.65706185e+00,  1.71686632e+00, -1.89402854e-01,
       -1.03306753e-01,  1.90667302e+00,  6.37688452e-01,  1.74321570e+00,
        2.54111760e-01,  3.79653224e-01,  9.57764232e-01,  1.32169025e+00,
        6.19182038e-01,  1.15194492e-01,  1.47102367e-01,  4.37510430e-01,
       -4.49329558e-02,  2.39709102e+00,  1.16206820e+00,  1.08360764e+00,
        2.61722590e+00,  2.60421756e+00,  2.53591301e-02,  3.79194735e-01,
        9.42424837e-01,  1.23513162e+00,  1.28210917e+00,  1.64424230e-01,
        8.71698209e-01,  1.33714679e-01,  8.44700019e-01,  1.85721541e+00,
        2.75918839e+00,  5.16605687e-01, -1.07231115e-02,  1.67846941e+00,
        1.55986732e+00,  4.96359329e-01,  2.40205240e+00,  9.64116525e-01])

In [152]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [153]:
print(r2)
print(mse)

0.4523564274280638
0.6286513411045525

In [155]:
from sklearn.model_selection import KFold, cross_val_score
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(lr,x,y,cv=kf, scoring='neg_mean_squared_error')
scores=-scores
print(scores)
print(scores.mean())

[211.64364627 280.04281067 317.20520811 179.6041757  311.19613071
 380.47402633 495.46908372 229.48857439 366.44848946 376.2924833 ]
314.7864628661143

In [156]:
# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor

In [157]:
dt=DecisionTreeRegressor()

In [158]:
dt

DecisionTreeRegressor()

In [159]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [160]:
dt

DecisionTreeRegressor()

In [161]:
y_pred=dt.predict(x_test)

In [162]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [163]:
print(r2)
print(mse)

-0.0226430629888843
1.173913043478261

In [164]:
from sklearn.model_selection import KFold, cross_val_score
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(dt,x,y,cv=kf, scoring='neg_mean_squared_error')
scores=-scores
print(scores)
print(scores.mean())

[347.68235294 489.44705882 591.54117647 628.4        615.23529412
 447.91764706 501.88235294 538.25       632.91666667 605.52380952]
539.8796358543417

In [165]:
from sklearn.model_selection import KFold, cross_val_score
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(dt,x,y,cv=kf)
scores=-scores
print(scores)
print(scores.mean())

[1.54892943 0.60429416 1.08662805 1.9254249  0.78621719 0.27231436
 0.21923417 0.65756732 0.43880997 0.54684223]
0.8086261785554271

In [166]:
# RandomForest Regressor
from sklearn.ensemble import RandomForestRegressor

In [167]:
rf=RandomForestRegressor()

In [168]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [169]:
y_pred=rf.predict(x_test)

In [170]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [171]:
print(r2)
print(mse)

0.4926208522025525
0.5824309782608695

In [172]:
from sklearn.model_selection import KFold, cross_val_score
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(dt,x,y,cv=kf, scoring='neg_mean_squared_error')
scores=-scores
print(scores)
print(scores.mean())

[588.54117647 551.2        671.4        548.42352941 548.25882353
 435.55294118 554.94117647 550.57142857 714.72619048 610.23809524]
577.3853361344538

In [173]:
from sklearn.model_selection import KFold, cross_val_score
kf=KFold(n_splits=10,shuffle=True,random_state=42)
scores=cross_val_score(dt,x,y,cv=kf)
scores=-scores
print(scores)
print(scores.mean())

[1.66294105 0.85895264 1.10919047 1.70813207 0.68225703 0.04825737
 0.11619659 1.13654678 0.77808536 0.65935191]
0.8759911272817791

# Funksiya

In [117]:
def ikki_son_yigindisi(x,y,z):
    return x+y+z

In [118]:
ikki_son_yigindisi(5,1,2)

8

In [119]:
def soz_soni(s):
    return len(s)

In [121]:
soz_soni('hellopython')

11

In [122]:
# 1 dan 10 gacha bolgan sonlarni toping
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9

In [128]:
# 1 dan 10 gacha bolgan sonlarni topadigan funksiya yasang

def bir_on(x,y):
    for i in range(x,y):
        print(i)
    return i

In [129]:
bir_on(1,10)

1
2
3
4
5
6
7
8
9

9

In [114]:
ikki_son_yigindisi(7,77)

84

In [66]:
# Tushurib qoldirilgan qiymatlarni toldiradigan funksiya yasang
df=pd.read_csv('heart_disease_uci.csv')

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       916 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        916 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     861 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(6), int64(2), object(8)
memory usage: 115.1+ KB

In [68]:
df.isnull().sum()

id            0
age           4
gender        0
dataset       0
cp            4
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        59
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [69]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_28012\2552798676.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col].fillna(df[col].mode()[0],inplace=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  920 non-null    float64
 6   chol      920 non-null    float64
 7   fbs       920 non-null    bool
 8   restecg   920 non-null    object
 9   thalch    920 non-null    float64
 10  exang     920 non-null    bool
 11  oldpeak   920 non-null    float64
 12  slope     920 non-null    object
 13  ca        920 non-null    float64
 14  thal      920 non-null    object
 15  num       920 non-null    int64
dtypes: bool(2), float64(6), int64(2), object(6)
memory usage: 102.6+ KB

In [72]:
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [75]:
tozala(df)

,id,age,gender,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63.0,Male,Cleveland,typical angina,145.000000,233.0,True,lv hypertrophy,150.000000,False,2.300000,downsloping,0.000000,fixed defect,0
1,2,67.0,Male,Cleveland,asymptomatic,160.000000,286.0,False,lv hypertrophy,108.000000,True,1.500000,flat,3.000000,normal,2
2,3,67.0,Male,Cleveland,asymptomatic,120.000000,229.0,False,lv hypertrophy,129.000000,True,2.600000,flat,2.000000,reversable defect,1
3,4,37.0,Male,Cleveland,non-anginal,130.000000,250.0,False,normal,187.000000,False,3.500000,downsloping,0.000000,normal,0
4,5,41.0,Female,Cleveland,atypical angina,130.000000,204.0,False,lv hypertrophy,172.000000,False,1.400000,upsloping,0.000000,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54.0,Female,VA Long Beach,asymptomatic,127.000000,333.0,True,st-t abnormality,154.000000,False,0.000000,flat,0.676375,normal,1
916,917,62.0,Male,VA Long Beach,typical angina,132.132404,139.0,False,st-t abnormality,137.545665,False,0.878788,flat,0.676375,normal,0
917,918,55.0,Male,VA Long Beach,asymptomatic,122.000000,223.0,True,st-t abnormality,100.000000,False,0.000000,flat,0.676375,fixed defect,2
918,919,58.0,Male,VA Long Beach,asymptomatic,132.132404,385.0,True,lv hypertrophy,137.545665,False,0.878788,flat,0.676375,normal,0
919,920,62.0,Male,VA Long Beach,atypical angina,120.000000,254.0,False,lv hypertrophy,93.000000,True,0.000000,flat,0.676375,normal,1

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  920 non-null    float64
 6   chol      920 non-null    float64
 7   fbs       920 non-null    bool
 8   restecg   920 non-null    object
 9   thalch    920 non-null    float64
 10  exang     920 non-null    bool
 11  oldpeak   920 non-null    float64
 12  slope     920 non-null    object
 13  ca        920 non-null    float64
 14  thal      920 non-null    object
 15  num       920 non-null    int64
dtypes: bool(2), float64(6), int64(2), object(6)
memory usage: 102.6+ KB

In [76]:
# df=pd.read_csv('physics_teacher_jobs_linkedin.csv')

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  920 non-null    float64
 6   chol      920 non-null    float64
 7   fbs       920 non-null    bool
 8   restecg   920 non-null    object
 9   thalch    920 non-null    float64
 10  exang     920 non-null    bool
 11  oldpeak   920 non-null    float64
 12  slope     920 non-null    object
 13  ca        920 non-null    float64
 14  thal      920 non-null    object
 15  num       920 non-null    int64
dtypes: bool(2), float64(6), int64(2), object(6)
memory usage: 102.6+ KB

In [157]:
df.isnull().sum()

title                  0
location               0
publishedAt            0
companyName            3
description            0
applicationsCount      0
contractType           0
experienceLevel        0
workType               1
sector                 4
salary               694
dtype: int64

In [158]:
tozala(df)

C:\Users\davro\AppData\Local\Temp\ipykernel_24204\4132828920.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

,title,location,publishedAt,companyName,description,applicationsCount,contractType,experienceLevel,workType,sector,salary
0,Physics Teacher @ Roseville Pathways (2025-26),"Roseville, CA",2025-06-05,Roseville Joint Union High School District,Valid California Single Subject Science Creden...,Be among the first 25 applicants,Full-time,Entry level,Education and Training,Education Management,"$47,096.47/yr - $93,839.67/yr"
1,Upper School Physics/Math Teacher,"Bryn Mawr, PA",2025-05-12,Sacred Heart Academy Bryn Mawr,Sacred Heart Academy (SHA) Bryn Mawr (PA) seek...,Be among the first 25 applicants,Full-time,Internship,Education and Training,Primary and Secondary Education,"$47,096.47/yr - $93,839.67/yr"
2,SCIENCE (PHYSICS) TEACHER,"Miami, FL",2024-07-11,Miami-Dade County Public Schools,"Miami-Dade County Public Schools (M-DCPS), an ...",Be among the first 25 applicants,Full-time,Entry level,Education,Education,"$47,096.47/yr - $93,839.67/yr"
3,Math & Science Instructors,"California, United States",2025-02-24,Mavin Learning Resources,Mavin Learning Resources strives to ignite our...,Be among the first 25 applicants,Part-time,Not Applicable,Education,Education Administration Programs,"$47,096.47/yr - $93,839.67/yr"
4,Physics Teacher,"Reading, PA",2023-10-03,"Reading School District l Reading, Pa.",Position Title: Science Teacher\n\nClassificat...,Be among the first 25 applicants,Full-time,Entry level,Education and Training,Primary and Secondary Education,"$47,096.47/yr - $93,839.67/yr"
...,...,...,...,...,...,...,...,...,...,...,...
842,Science Teacher,"Minnetonka, MN",2025-05-30,Lionsgate Academy,Lionsgate Academy specializes in educating stu...,Be among the first 25 applicants,Full-time,Entry level,Education and Training,Primary and Secondary Education,"$47,096.47/yr - $93,839.67/yr"
843,ELL/Bi-Lingual Science Teacher,"Oak Lawn, IL",2025-05-02,Community High School District 218,Job Title: Bilingual Science (Biology & Chemis...,Be among the first 25 applicants,Full-time,Entry level,Education and Training,Primary and Secondary Education,"$47,096.47/yr - $93,839.67/yr"
844,Anticipated Middle School Science Teacher,"Elmwood Park, NJ",2025-05-14,ELMWOOD PARK BOARD OF EDUCATION SCHOOL DISTRICT,Anticipated Middle School Science Teacher\n\n2...,Be among the first 25 applicants,Full-time,Entry level,Education and Training,Primary and Secondary Education,"$47,096.47/yr - $93,839.67/yr"
845,High School Physical Science Teacher,"Tecumseh, OK",2025-06-07,Oklahoma State School Boards Association,Tecumseh Public Schools is actively seeking in...,Be among the first 25 applicants,Full-time,Entry level,Education and Training,Education Administration Programs,"$47,096.47/yr - $93,839.67/yr"
846,Adjunct Instructor - Physics (65663),"New Rochelle, NY",2024-03-21,Iona University,The Mathematics and Physics Department of Iona...,Be among the first 25 applicants,Part-time,Entry level,Education and Training,Higher Education,"$47,096.47/yr - $93,839.67/yr"

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              847 non-null    object
 1   location           847 non-null    object
 2   publishedAt        847 non-null    object
 3   companyName        847 non-null    object
 4   description        847 non-null    object
 5   applicationsCount  847 non-null    object
 6   contractType       847 non-null    object
 7   experienceLevel    847 non-null    object
 8   workType           847 non-null    object
 9   sector             847 non-null    object
 10  salary             847 non-null    object
dtypes: object(11)
memory usage: 72.9+ KB

In [160]:
df.isnull().sum()

title                0
location             0
publishedAt          0
companyName          0
description          0
applicationsCount    0
contractType         0
experienceLevel      0
workType             0
sector               0
salary               0
dtype: int64

In [78]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [161]:
def encodla(df):
    from sklearn.preprocessing import LabelEncoder
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [162]:
df=encodla(df)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        920 non-null    int64
 1   age                       920 non-null    float64
 2   trestbps                  920 non-null    float64
 3   chol                      920 non-null    float64
 4   fbs                       920 non-null    bool
 5   thalch                    920 non-null    float64
 6   exang                     920 non-null    bool
 7   oldpeak                   920 non-null    float64
 8   ca                        920 non-null    float64
 9   num                       920 non-null    int64
 10  gender_Female             920 non-null    int32
 11  gender_Male               920 non-null    int32
 12  dataset_Cleveland         920 non-null    int32
 13  dataset_Hungary           920 non-null    int32
 14  dataset_Switzerland       920 non-null    int32
 15  dataset_VA Long Beach     920 non-null    int32
 16  cp_asymptomatic           920 non-null    int32
 17  cp_atypical angina        920 non-null    int32
 18  cp_non-anginal            920 non-null    int32
 19  cp_typical angina         920 non-null    int32
 20  restecg_lv hypertrophy    920 non-null    int32
 21  restecg_normal            920 non-null    int32
 22  restecg_st-t abnormality  920 non-null    int32
 23  slope_downsloping         920 non-null    int32
 24  slope_flat                920 non-null    int32
 25  slope_upsloping           920 non-null    int32
 26  thal_fixed defect         920 non-null    int32
 27  thal_normal               920 non-null    int32
 28  thal_reversable defect    920 non-null    int32
dtypes: bool(2), float64(6), int32(19), int64(2)
memory usage: 127.7 KB

In [165]:
df=pd.read_csv('heart_disease_uci.csv')

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       916 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        916 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     861 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(6), int64(2), object(8)
memory usage: 115.1+ KB

In [167]:
tozala(df)

C:\Users\davro\AppData\Local\Temp\ipykernel_24204\4132828920.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_24204\4132828920.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_24204\4132828920.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col].fillna(df[col].mode()[0],inplace=True)

,id,age,gender,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63.0,Male,Cleveland,typical angina,145.000000,233.0,True,lv hypertrophy,150.000000,False,2.300000,downsloping,0.000000,fixed defect,0
1,2,67.0,Male,Cleveland,asymptomatic,160.000000,286.0,False,lv hypertrophy,108.000000,True,1.500000,flat,3.000000,normal,2
2,3,67.0,Male,Cleveland,asymptomatic,120.000000,229.0,False,lv hypertrophy,129.000000,True,2.600000,flat,2.000000,reversable defect,1
3,4,37.0,Male,Cleveland,non-anginal,130.000000,250.0,False,normal,187.000000,False,3.500000,downsloping,0.000000,normal,0
4,5,41.0,Female,Cleveland,atypical angina,130.000000,204.0,False,lv hypertrophy,172.000000,False,1.400000,upsloping,0.000000,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54.0,Female,VA Long Beach,asymptomatic,127.000000,333.0,True,st-t abnormality,154.000000,False,0.000000,flat,0.676375,normal,1
916,917,62.0,Male,VA Long Beach,typical angina,132.132404,139.0,False,st-t abnormality,137.545665,False,0.878788,flat,0.676375,normal,0
917,918,55.0,Male,VA Long Beach,asymptomatic,122.000000,223.0,True,st-t abnormality,100.000000,False,0.000000,flat,0.676375,fixed defect,2
918,919,58.0,Male,VA Long Beach,asymptomatic,132.132404,385.0,True,lv hypertrophy,137.545665,False,0.878788,flat,0.676375,normal,0
919,920,62.0,Male,VA Long Beach,atypical angina,120.000000,254.0,False,lv hypertrophy,93.000000,True,0.000000,flat,0.676375,normal,1

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    float64
 2   gender    920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  920 non-null    float64
 6   chol      920 non-null    float64
 7   fbs       920 non-null    bool
 8   restecg   920 non-null    object
 9   thalch    920 non-null    float64
 10  exang     920 non-null    bool
 11  oldpeak   920 non-null    float64
 12  slope     920 non-null    object
 13  ca        920 non-null    float64
 14  thal      920 non-null    object
 15  num       920 non-null    int64
dtypes: bool(2), float64(6), int64(2), object(6)
memory usage: 102.6+ KB

In [170]:
df=encodla(df)

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        920 non-null    int64
 1   age                       920 non-null    float64
 2   trestbps                  920 non-null    float64
 3   chol                      920 non-null    float64
 4   fbs                       920 non-null    bool
 5   thalch                    920 non-null    float64
 6   exang                     920 non-null    bool
 7   oldpeak                   920 non-null    float64
 8   ca                        920 non-null    float64
 9   num                       920 non-null    int64
 10  gender_Female             920 non-null    int32
 11  gender_Male               920 non-null    int32
 12  dataset_Cleveland         920 non-null    int32
 13  dataset_Hungary           920 non-null    int32
 14  dataset_Switzerland       920 non-null    int32
 15  dataset_VA Long Beach     920 non-null    int32
 16  cp_asymptomatic           920 non-null    int32
 17  cp_atypical angina        920 non-null    int32
 18  cp_non-anginal            920 non-null    int32
 19  cp_typical angina         920 non-null    int32
 20  restecg_lv hypertrophy    920 non-null    int32
 21  restecg_normal            920 non-null    int32
 22  restecg_st-t abnormality  920 non-null    int32
 23  slope_downsloping         920 non-null    int32
 24  slope_flat                920 non-null    int32
 25  slope_upsloping           920 non-null    int32
 26  thal_fixed defect         920 non-null    int32
 27  thal_normal               920 non-null    int32
 28  thal_reversable defect    920 non-null    int32
dtypes: bool(2), float64(6), int32(19), int64(2)
memory usage: 127.7 KB

In [172]:
df.head()

,id,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,num,...,cp_typical angina,restecg_lv hypertrophy,restecg_normal,restecg_st-t abnormality,slope_downsloping,slope_flat,slope_upsloping,thal_fixed defect,thal_normal,thal_reversable defect
0,1,63.0,145.0,233.0,True,150.0,False,2.3,0.0,0,...,1,1,0,0,1,0,0,1,0,0
1,2,67.0,160.0,286.0,False,108.0,True,1.5,3.0,2,...,0,1,0,0,0,1,0,0,1,0
2,3,67.0,120.0,229.0,False,129.0,True,2.6,2.0,1,...,0,1,0,0,0,1,0,0,0,1
3,4,37.0,130.0,250.0,False,187.0,False,3.5,0.0,0,...,0,0,1,0,1,0,0,0,1,0
4,5,41.0,130.0,204.0,False,172.0,False,1.4,0.0,0,...,0,1,0,0,0,0,1,0,1,0

In [80]:
from sklearn.preprocessing import MinMaxScaler

In [81]:
scaler=MinMaxScaler()

In [82]:
num_col=df.select_dtypes(include=['int64','float64','int32']).columns.drop('num')

In [83]:
def scaler_qil(df):
    from sklearn.preprocessing import MinMaxScaler
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64','int32']).columns.drop('num')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [84]:
scaler_qil(df)

,id,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,num,...,cp_typical angina,restecg_lv hypertrophy,restecg_normal,restecg_st-t abnormality,slope_downsloping,slope_flat,slope_upsloping,thal_fixed defect,thal_normal,thal_reversable defect
0,0.000000,0.714286,0.725000,0.386401,True,0.633803,False,0.556818,0.000000,0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.001088,0.795918,0.800000,0.474295,False,0.338028,True,0.465909,1.000000,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.002176,0.795918,0.600000,0.379768,False,0.485915,True,0.590909,0.666667,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.003264,0.183673,0.650000,0.414594,False,0.894366,False,0.693182,0.000000,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.004353,0.265306,0.650000,0.338308,False,0.788732,False,0.454545,0.000000,0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,0.995647,0.530612,0.635000,0.552239,True,0.661972,False,0.295455,0.225458,1,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
916,0.996736,0.693878,0.660662,0.230514,False,0.546096,False,0.395317,0.225458,0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.997824,0.551020,0.610000,0.369818,True,0.281690,False,0.295455,0.225458,2,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
918,0.998912,0.612245,0.660662,0.638474,True,0.546096,False,0.395317,0.225458,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
919,1.000000,0.693878,0.600000,0.421227,False,0.232394,True,0.295455,0.225458,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [85]:
df.head()

,id,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,num,...,cp_typical angina,restecg_lv hypertrophy,restecg_normal,restecg_st-t abnormality,slope_downsloping,slope_flat,slope_upsloping,thal_fixed defect,thal_normal,thal_reversable defect
0,0.000000,0.714286,0.725,0.386401,True,0.633803,False,0.556818,0.000000,0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.001088,0.795918,0.800,0.474295,False,0.338028,True,0.465909,1.000000,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.002176,0.795918,0.600,0.379768,False,0.485915,True,0.590909,0.666667,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.003264,0.183673,0.650,0.414594,False,0.894366,False,0.693182,0.000000,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.004353,0.265306,0.650,0.338308,False,0.788732,False,0.454545,0.000000,0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        920 non-null    float64
 1   age                       920 non-null    float64
 2   trestbps                  920 non-null    float64
 3   chol                      920 non-null    float64
 4   fbs                       920 non-null    bool
 5   thalch                    920 non-null    float64
 6   exang                     920 non-null    bool
 7   oldpeak                   920 non-null    float64
 8   ca                        920 non-null    float64
 9   num                       920 non-null    int64
 10  gender_Female             920 non-null    float64
 11  gender_Male               920 non-null    float64
 12  dataset_Cleveland         920 non-null    float64
 13  dataset_Hungary           920 non-null    float64
 14  dataset_Switzerland       920 non-null    float64
 15  dataset_VA Long Beach     920 non-null    float64
 16  cp_asymptomatic           920 non-null    float64
 17  cp_atypical angina        920 non-null    float64
 18  cp_non-anginal            920 non-null    float64
 19  cp_typical angina         920 non-null    float64
 20  restecg_lv hypertrophy    920 non-null    float64
 21  restecg_normal            920 non-null    float64
 22  restecg_st-t abnormality  920 non-null    float64
 23  slope_downsloping         920 non-null    float64
 24  slope_flat                920 non-null    float64
 25  slope_upsloping           920 non-null    float64
 26  thal_fixed defect         920 non-null    float64
 27  thal_normal               920 non-null    float64
 28  thal_reversable defect    920 non-null    float64
dtypes: bool(2), float64(26), int64(1)
memory usage: 196.0 KB