In [8]:
a=[1,2,3]
for i in a:
    print(i)

1
2
3

In [9]:
for i in a:
    print(i+1)

2
3
4

In [10]:
for i in a:
    print(i*2)

2
4
6

In [ ]:
for element in a:
    
    print(element)

1
2
3

In [13]:
b=['Hello','Hi','Bye']
for i in b:
    print(len(i))

5
2
3

In [18]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [19]:
for i in range(1,10):
    if i%2==0:
        print(i)

2
4
6
8

In [20]:
for i in range(1,10):
    if i%2!=0:
        print(i)

1
3
5
7
9

In [21]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9

In [ ]:
range(start,stop,step)

In [22]:
for i in range(2,11,2):
    print(i)

2
4
6
8
10

In [57]:
import pandas as pd
df=pd.read_csv('metadata_bundesliga_1415.csv')

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   448 non-null    object
 2   games         448 non-null    float64
 3   time          448 non-null    float64
 4   goals         448 non-null    float64
 5   xG            444 non-null    float64
 6   assists       444 non-null    float64
 7   xA            444 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          5 non-null      object
dtypes: float64(9), int64(6), object(4)
memory usage: 67.4+ KB

In [16]:
df.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,Size
0,356,Alexander Meier,26,2209,19,15.395941,2,1.268694,80,22,0,0,F M S,Eintracht Frankfurt,16,12.364834,12.408789,1.915658,XL
1,227,Robert Lewandowski,31,2493,17,17.722183,5,4.644013,104,32,0,0,F M S,Bayern Munich,16,16.964407,23.315430,4.924822,S
2,392,Arjen Robben,21,1681,17,10.364112,7,7.505970,88,50,0,0,D F M S,Bayern Munich,15,8.848720,20.820983,8.605793,MS
3,158,Bas Dost,21,1532,16,11.341977,4,2.659186,43,15,1,0,F S,Wolfsburg,16,11.341977,15.911891,2.538306,2XL
4,318,Pierre-Emerick Aubameyang,33,2724,16,15.396760,6,6.378020,102,46,4,0,F M S,Borussia Dortmund,14,13.881207,20.852728,2.512650,NaN

# Data Preprocessing + for loop

In [23]:
# Missing + for loop

In [27]:
df.isnull().sum()

id                0
player_name       5
games             5
time              5
goals             5
xG                9
assists           9
xA                9
shots             0
key_passes        0
yellow_cards      0
red_cards         0
position          0
team_title        0
npg               0
npxG              0
xGChain           0
xGBuildup         0
Size            448
dtype: int64

In [28]:
df['player_name'].fillna(df['player_name'].mode()[0],inplace=True)

In [29]:
df.isnull().sum()

id                0
player_name       0
games             5
time              5
goals             5
xG                9
assists           9
xA                9
shots             0
key_passes        0
yellow_cards      0
red_cards         0
position          0
team_title        0
npg               0
npxG              0
xGChain           0
xGBuildup         0
Size            448
dtype: int64

In [30]:
df['games'].fillna(df['games'].mean(),inplace=True)

C:\Users\davro\AppData\Local\Temp\ipykernel_18920\359088722.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['games'].fillna(df['games'].mean(),inplace=True)

In [31]:
df.isnull().sum()

id                0
player_name       0
games             0
time              5
goals             5
xG                9
assists           9
xA                9
shots             0
key_passes        0
yellow_cards      0
red_cards         0
position          0
team_title        0
npg               0
npxG              0
xGChain           0
xGBuildup         0
Size            448
dtype: int64

In [34]:
df.isnull().sum()

id                0
player_name       5
games             5
time              5
goals             5
xG                9
assists           9
xA                9
shots             0
key_passes        0
yellow_cards      0
red_cards         0
position          0
team_title        0
npg               0
npxG              0
xGChain           0
xGBuildup         0
Size            448
dtype: int64

In [35]:
df.info(
    
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   448 non-null    object
 2   games         448 non-null    float64
 3   time          448 non-null    float64
 4   goals         448 non-null    float64
 5   xG            444 non-null    float64
 6   assists       444 non-null    float64
 7   xA            444 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          5 non-null      object
dtypes: float64(9), int64(6), object(4)
memory usage: 67.4+ KB

In [37]:
df.isnull().sum()

id                0
player_name       5
games             5
time              5
goals             5
xG                9
assists           9
xA                9
shots             0
key_passes        0
yellow_cards      0
red_cards         0
position          0
team_title        0
npg               0
npxG              0
xGChain           0
xGBuildup         0
Size            448
dtype: int64

In [38]:
df.isnull().any()

id              False
player_name      True
games            True
time             True
goals            True
xG               True
assists          True
xA               True
shots           False
key_passes      False
yellow_cards    False
red_cards       False
position        False
team_title      False
npg             False
npxG            False
xGChain         False
xGBuildup       False
Size             True
dtype: bool

In [36]:
df.columns

Index(['id', 'player_name', 'games', 'time', 'goals', 'xG', 'assists', 'xA',
       'shots', 'key_passes', 'yellow_cards', 'red_cards', 'position',
       'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup', 'Size'],
      dtype='object')

In [59]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

C:\Users\davro\AppData\Local\Temp\ipykernel_18920\1755169422.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)
C:\Users\davro\AppData\Local\Temp\ipykernel_18920\1755169422.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)

In [60]:
df.isnull().sum()

id              0
player_name     0
games           0
time            0
goals           0
xG              0
assists         0
xA              0
shots           0
key_passes      0
yellow_cards    0
red_cards       0
position        0
team_title      0
npg             0
npxG            0
xGChain         0
xGBuildup       0
Size            0
dtype: int64

In [41]:
# Encoding + For loop

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    float64
 3   time          453 non-null    float64
 4   goals         453 non-null    float64
 5   xG            453 non-null    float64
 6   assists       453 non-null    float64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          453 non-null    object
dtypes: float64(9), int64(6), object(4)
memory usage: 67.4+ KB

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
encoder=LabelEncoder()

In [45]:
encoder

LabelEncoder()

In [46]:
df['player_name']=encoder.fit_transform(df['player_name'])

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    int64
 2   games         453 non-null    float64
 3   time          453 non-null    float64
 4   goals         453 non-null    float64
 5   xG            453 non-null    float64
 6   assists       453 non-null    float64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          453 non-null    object
dtypes: float64(9), int64(7), object(3)
memory usage: 67.4+ KB

In [48]:
df.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,Size
0,356,0,26.0,2209.0,19.0,15.395941,2.0,1.268694,80,22,0,0,F M S,Eintracht Frankfurt,16,12.364834,12.408789,1.915658,XL
1,227,1,31.0,2493.0,17.0,17.722183,5.0,4.644013,104,32,0,0,F M S,Bayern Munich,16,16.964407,23.315430,4.924822,S
2,392,22,21.0,1681.0,17.0,10.364112,7.0,1.229209,88,50,0,0,D F M S,Bayern Munich,15,8.848720,20.820983,8.605793,MS
3,158,29,21.0,1532.0,16.0,11.341977,4.0,1.229209,43,15,1,0,F S,Wolfsburg,16,11.341977,15.911891,2.538306,2XL
4,318,324,33.0,2724.0,16.0,15.396760,6.0,1.229209,102,46,4,0,F M S,Borussia Dortmund,14,13.881207,20.852728,2.512650,2XL

In [49]:
df.nunique()

id              453
player_name     448
games            35
time            393
goals            17
xG              383
assists          13
xA              381
shots            76
key_passes       59
yellow_cards     12
red_cards         3
position         14
team_title       26
npg              16
npxG            391
xGChain         432
xGBuildup       419
Size              4
dtype: int64

In [50]:
df['Size']

0       XL
1        S
2       MS
3      2XL
4      2XL
      ...
448    2XL
449    2XL
450    2XL
451    2XL
452    2XL
Name: Size, Length: 453, dtype: object

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    int64
 2   games         453 non-null    float64
 3   time          453 non-null    float64
 4   goals         453 non-null    float64
 5   xG            453 non-null    float64
 6   assists       453 non-null    float64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          453 non-null    object
dtypes: float64(9), int64(7), object(3)
memory usage: 67.4+ KB

In [52]:
dummies=pd.get_dummies(df['Size'],prefix='col',dtype=int)

In [53]:
dummies

     col_2XL  col_MS  col_S  col_XL
0          0       0      0       1
1          0       0      1       0
2          0       1      0       0
3          1       0      0       0
4          1       0      0       0
..       ...     ...    ...     ...
448        1       0      0       0
449        1       0      0       0
450        1       0      0       0
451        1       0      0       0
452        1       0      0       0

[453 rows x 4 columns]

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    int64
 2   games         453 non-null    float64
 3   time          453 non-null    float64
 4   goals         453 non-null    float64
 5   xG            453 non-null    float64
 6   assists       453 non-null    float64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          453 non-null    object
dtypes: float64(9), int64(7), object(3)
memory usage: 67.4+ KB

In [55]:
df=pd.concat([df.drop(columns=['Size']),dummies],axis=1)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    float64
 3   time          453 non-null    float64
 4   goals         453 non-null    float64
 5   xG            453 non-null    float64
 6   assists       453 non-null    float64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          453 non-null    object
dtypes: float64(9), int64(6), object(4)
memory usage: 67.4+ KB

In [ ]:
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
       
        else:
            df[col]=encoder.fit_transform(df[col])

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    int64
 2   games         453 non-null    float64
 3   time          453 non-null    float64
 4   goals         453 non-null    float64
 5   xG            453 non-null    float64
 6   assists       453 non-null    float64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    int64
 13  team_title    453 non-null    int64
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size_2XL      453 non-null    int64
 19  Size_MS       453 non-null    int64
 20  Size_S        453 non-null    int64
 21  Size_XL       453 non-null    int64
dtypes: float64(9), int64(13)
memory usage: 78.0 KB

In [64]:
qosh=0
for i in range(1,10):
    if i%2==0:
        qosh=qosh+i
        print(i)
print(qosh)

2
4
6
8
20