In [103]:
import pandas as pd

In [104]:
df = pd.read_csv('sleep_health_dataset.csv')

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   gender                       100000 non-null  object
 3   occupation                   100000 non-null  object
 4   bmi                          100000 non-null  float64
 5   country                      100000 non-null  object
 6   sleep_duration_hrs           100000 non-null  float64
 7   sleep_quality_score          100000 non-null  float64
 8   rem_percentage               100000 non-null  float64
 9   deep_sleep_percentage        100000 non-null  float64
 10  sleep_latency_mins           100000 non-null  int64
 11  wake_episodes_per_night      100000 non-null  int64
 12  caffeine_mg_before_bed       100000 non-null  int64
 13  alcohol_units_before_bed     100000 non-null  float64
 14  screen_time_before_bed_mins  100000 non-null  int64
 15  exercise_day                 100000 non-null  int64
 16  steps_that_day               100000 non-null  int64
 17  nap_duration_mins            100000 non-null  int64
 18  stress_score                 100000 non-null  float64
 19  work_hours_that_day          100000 non-null  float64
 20  chronotype                   100000 non-null  object
 21  mental_health_condition      100000 non-null  object
 22  heart_rate_resting_bpm       100000 non-null  int64
 23  sleep_aid_used               100000 non-null  int64
 24  shift_work                   100000 non-null  int64
 25  room_temperature_celsius     100000 non-null  float64
 26  weekend_sleep_diff_hrs       100000 non-null  float64
 27  season                       100000 non-null  object
 28  day_type                     100000 non-null  object
 29  cognitive_performance_score  100000 non-null  float64
 30  sleep_disorder_risk          100000 non-null  object
 31  felt_rested                  100000 non-null  int64
dtypes: float64(11), int64(13), object(8)
memory usage: 24.4+ MB

In [106]:
df.columns

Index(['person_id', 'age', 'gender', 'occupation', 'bmi', 'country',
       'sleep_duration_hrs', 'sleep_quality_score', 'rem_percentage',
       'deep_sleep_percentage', 'sleep_latency_mins',
       'wake_episodes_per_night', 'caffeine_mg_before_bed',
       'alcohol_units_before_bed', 'screen_time_before_bed_mins',
       'exercise_day', 'steps_that_day', 'nap_duration_mins', 'stress_score',
       'work_hours_that_day', 'chronotype', 'mental_health_condition',
       'heart_rate_resting_bpm', 'sleep_aid_used', 'shift_work',
       'room_temperature_celsius', 'weekend_sleep_diff_hrs', 'season',
       'day_type', 'cognitive_performance_score', 'sleep_disorder_risk',
       'felt_rested'],
      dtype='object')

In [109]:
df.sample(10)

,person_id,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,...,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,cognitive_performance_score,sleep_disorder_risk,felt_rested
94349,94350,41,Male,Doctor,30.1,Italy,6.85,5.0,18.7,16.1,...,65,0,0,18.7,1.77,Autumn,Weekend,68.8,Healthy,1
69949,69950,36,Female,Software Engineer,21.3,UK,5.45,3.8,19.2,18.9,...,70,0,0,23.6,1.96,Spring,Weekday,42.3,Mild,0
14115,14116,28,Female,Doctor,27.0,Spain,8.36,6.2,20.6,20.8,...,85,1,0,19.9,-0.40,Spring,Weekend,72.6,Healthy,0
49443,49444,28,Other,Doctor,26.4,India,4.82,2.7,18.3,16.4,...,57,1,0,18.0,1.83,Spring,Weekday,30.6,Moderate,0
2759,2760,20,Male,Software Engineer,27.9,France,5.51,4.2,17.7,25.7,...,65,0,0,21.8,1.80,Summer,Weekday,55.2,Healthy,1
30774,30775,32,Female,Freelancer,25.6,USA,7.62,5.3,18.9,20.5,...,73,1,0,20.0,1.46,Winter,Weekday,59.0,Mild,1
92269,92270,23,Male,Software Engineer,20.5,USA,5.66,3.9,20.1,23.1,...,58,1,0,21.7,0.40,Autumn,Weekday,59.0,Healthy,0
19218,19219,38,Female,Lawyer,38.4,Brazil,6.06,6.0,17.2,10.9,...,59,1,0,21.4,2.21,Spring,Weekday,44.6,Mild,0
82356,82357,57,Female,Teacher,28.8,USA,6.20,5.9,25.1,23.5,...,61,1,0,21.9,0.13,Autumn,Weekday,79.9,Healthy,0
8870,8871,52,Male,Student,29.5,France,5.18,5.1,19.9,14.1,...,56,0,0,19.4,0.73,Summer,Weekend,47.9,Mild,1

### **Handling missing values**

In [110]:
df.isnull().sum()

person_id                      0
age                            0
gender                         0
occupation                     0
bmi                            0
country                        0
sleep_duration_hrs             0
sleep_quality_score            0
rem_percentage                 0
deep_sleep_percentage          0
sleep_latency_mins             0
wake_episodes_per_night        0
caffeine_mg_before_bed         0
alcohol_units_before_bed       0
screen_time_before_bed_mins    0
exercise_day                   0
steps_that_day                 0
nap_duration_mins              0
stress_score                   0
work_hours_that_day            0
chronotype                     0
mental_health_condition        0
heart_rate_resting_bpm         0
sleep_aid_used                 0
shift_work                     0
room_temperature_celsius       0
weekend_sleep_diff_hrs         0
season                         0
day_type                       0
cognitive_performance_score    0
sleep_disorder_risk            0
felt_rested                    0
dtype: int64

### **Encoding**

In [111]:
from sklearn.preprocessing import OrdinalEncoder

In [114]:
def encoding(df):
    
    for col in df.columns:
        if df[col].dtype == "object":
            if df[col].nunique() <= 3:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
            else:
                encoder = OrdinalEncoder()
                df[col] = encoder.fit_transform(df[[col]])
    return df

In [115]:
df =  encoding(df)
df

,person_id,age,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,...,sleep_disorder_risk,felt_rested,gender_Female,gender_Male,gender_Other,chronotype_Evening,chronotype_Morning,chronotype_Neutral,day_type_Weekday,day_type_Weekend
0,1,29,1.0,25.7,7.0,6.19,6.6,22.5,19.3,16,...,0.0,0,1,0,0,0,1,0,1,0
1,2,55,9.0,22.0,14.0,8.32,6.9,26.9,14.9,17,...,0.0,1,1,0,0,0,0,1,0,1
2,3,42,6.0,25.0,5.0,3.74,1.0,20.2,16.2,26,...,3.0,0,0,1,0,0,0,1,0,1
3,4,37,10.0,29.5,5.0,6.79,6.4,17.7,17.7,13,...,0.0,0,1,0,0,0,1,0,0,1
4,5,23,4.0,23.6,11.0,5.02,3.2,23.3,18.3,30,...,1.0,0,0,1,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,44,6.0,25.9,14.0,6.77,6.3,26.8,24.6,18,...,0.0,1,1,0,0,0,1,0,0,1
99996,99997,44,5.0,30.2,5.0,4.90,4.1,21.6,22.3,9,...,1.0,0,1,0,0,0,1,0,1,0
99997,99998,39,5.0,29.2,1.0,5.94,5.1,21.4,14.3,9,...,0.0,1,0,1,0,0,0,1,1,0
99998,99999,33,6.0,27.3,5.0,5.27,3.0,21.9,23.6,23,...,1.0,0,1,0,0,0,0,1,0,1
99999,100000,30,8.0,24.3,14.0,6.33,4.7,14.5,25.3,27,...,1.0,0,0,1,0,1,0,0,1,0

In [116]:
df.columns

Index(['person_id', 'age', 'occupation', 'bmi', 'country',
       'sleep_duration_hrs', 'sleep_quality_score', 'rem_percentage',
       'deep_sleep_percentage', 'sleep_latency_mins',
       'wake_episodes_per_night', 'caffeine_mg_before_bed',
       'alcohol_units_before_bed', 'screen_time_before_bed_mins',
       'exercise_day', 'steps_that_day', 'nap_duration_mins', 'stress_score',
       'work_hours_that_day', 'mental_health_condition',
       'heart_rate_resting_bpm', 'sleep_aid_used', 'shift_work',
       'room_temperature_celsius', 'weekend_sleep_diff_hrs', 'season',
       'cognitive_performance_score', 'sleep_disorder_risk', 'felt_rested',
       'gender_Female', 'gender_Male', 'gender_Other', 'chronotype_Evening',
       'chronotype_Morning', 'chronotype_Neutral', 'day_type_Weekday',
       'day_type_Weekend'],
      dtype='object')

In [117]:
df.sample(10)

,person_id,age,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,...,sleep_disorder_risk,felt_rested,gender_Female,gender_Male,gender_Other,chronotype_Evening,chronotype_Morning,chronotype_Neutral,day_type_Weekday,day_type_Weekend
26385,26386,26,6.0,31.1,1.0,6.25,5.5,16.9,16.5,24,...,1.0,0,0,1,0,0,0,1,1,0
63839,63840,19,0.0,23.2,5.0,5.60,3.1,18.4,23.7,19,...,1.0,1,1,0,0,0,0,1,0,1
8854,8855,33,6.0,19.6,11.0,4.63,3.0,20.9,20.2,19,...,1.0,0,0,1,0,0,0,1,1,0
7439,7440,22,10.0,27.7,14.0,8.07,5.4,19.8,21.5,17,...,0.0,0,1,0,0,0,0,1,0,1
86665,86666,18,11.0,22.3,7.0,7.79,7.2,18.0,23.1,8,...,0.0,1,0,1,0,0,0,1,0,1
85803,85804,47,6.0,28.0,1.0,5.57,3.5,23.0,18.5,16,...,0.0,0,1,0,0,0,0,1,1,0
59736,59737,40,1.0,24.6,7.0,4.70,3.9,19.6,18.4,27,...,0.0,0,1,0,0,1,0,0,1,0
36124,36125,31,8.0,32.7,14.0,6.54,3.0,16.0,22.9,37,...,1.0,0,0,1,0,1,0,0,0,1
70509,70510,36,11.0,29.1,1.0,7.19,4.3,15.9,21.9,32,...,0.0,1,1,0,0,1,0,0,1,0
8762,8763,34,1.0,31.6,2.0,6.82,4.7,19.9,21.0,19,...,0.0,0,1,0,0,0,1,0,0,1

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 37 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   occupation                   100000 non-null  float64
 3   bmi                          100000 non-null  float64
 4   country                      100000 non-null  float64
 5   sleep_duration_hrs           100000 non-null  float64
 6   sleep_quality_score          100000 non-null  float64
 7   rem_percentage               100000 non-null  float64
 8   deep_sleep_percentage        100000 non-null  float64
 9   sleep_latency_mins           100000 non-null  int64
 10  wake_episodes_per_night      100000 non-null  int64
 11  caffeine_mg_before_bed       100000 non-null  int64
 12  alcohol_units_before_bed     100000 non-null  float64
 13  screen_time_before_bed_mins  100000 non-null  int64
 14  exercise_day                 100000 non-null  int64
 15  steps_that_day               100000 non-null  int64
 16  nap_duration_mins            100000 non-null  int64
 17  stress_score                 100000 non-null  float64
 18  work_hours_that_day          100000 non-null  float64
 19  mental_health_condition      100000 non-null  float64
 20  heart_rate_resting_bpm       100000 non-null  int64
 21  sleep_aid_used               100000 non-null  int64
 22  shift_work                   100000 non-null  int64
 23  room_temperature_celsius     100000 non-null  float64
 24  weekend_sleep_diff_hrs       100000 non-null  float64
 25  season                       100000 non-null  float64
 26  cognitive_performance_score  100000 non-null  float64
 27  sleep_disorder_risk          100000 non-null  float64
 28  felt_rested                  100000 non-null  int64
 29  gender_Female                100000 non-null  int32
 30  gender_Male                  100000 non-null  int32
 31  gender_Other                 100000 non-null  int32
 32  chronotype_Evening           100000 non-null  int32
 33  chronotype_Morning           100000 non-null  int32
 34  chronotype_Neutral           100000 non-null  int32
 35  day_type_Weekday             100000 non-null  int32
 36  day_type_Weekend             100000 non-null  int32
dtypes: float64(16), int32(8), int64(13)
memory usage: 25.2 MB

### **Scaling**

In [119]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_scale = df.select_dtypes(include = ['float64','int64', 'int32']).columns.drop('sleep_disorder_risk')
df[df_scale] = scaler.fit_transform(df[df_scale])

In [120]:
df.sample(10)

,person_id,age,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,...,sleep_disorder_risk,felt_rested,gender_Female,gender_Male,gender_Other,chronotype_Evening,chronotype_Morning,chronotype_Neutral,day_type_Weekday,day_type_Weekend
41470,0.414704,0.019608,0.181818,0.365517,0.928571,0.644000,0.677778,0.830,0.772,0.368421,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
97511,0.975120,0.372549,0.909091,0.351724,0.928571,0.402667,0.433333,0.705,0.496,0.403509,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
24077,0.240772,0.156863,0.090909,0.400000,0.642857,0.537333,0.611111,0.760,0.772,0.192982,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
20838,0.208382,0.490196,0.909091,0.210345,0.285714,0.305333,0.366667,0.700,0.732,0.140351,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
25831,0.258313,0.411765,0.454545,0.403448,1.000000,0.514667,0.300000,0.525,0.772,0.333333,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
5232,0.052321,0.431373,0.818182,0.548276,0.285714,0.653333,0.522222,0.805,0.548,0.456140,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
92562,0.925629,0.235294,0.727273,0.568966,0.071429,0.424000,0.511111,0.470,0.376,0.228070,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
8381,0.083811,0.098039,0.545455,0.551724,1.000000,0.456000,0.366667,0.725,0.608,0.561404,...,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
42958,0.429584,0.098039,0.636364,0.334483,0.357143,0.529333,0.600000,0.585,0.392,0.315789,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
63448,0.634486,0.078431,0.090909,0.300000,0.928571,0.244000,0.255556,0.575,0.576,0.526316,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

### **Logistic Regression**

In [121]:
x = df.drop('sleep_disorder_risk', axis=1)
y = df['sleep_disorder_risk']

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [130]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr

LogisticRegression(max_iter=1000)

In [131]:
lr.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [132]:
y_pred = lr.predict(x_test)
y_pred

array([1., 3., 1., ..., 1., 1., 1.])

In [137]:
from sklearn.metrics import classification_report, mean_absolute_error
cl = classification_report(y_test, y_pred)
print(cl)

              precision    recall  f1-score   support

         0.0       0.88      0.90      0.89     10892
         1.0       0.71      0.76      0.73      6673
         2.0       0.49      0.34      0.40      1626
         3.0       0.69      0.57      0.63       809

    accuracy                           0.79     20000
   macro avg       0.69      0.64      0.66     20000
weighted avg       0.79      0.79      0.79     20000

In [138]:
mae = mean_absolute_error(y_test, y_pred)

### **Cross Validation**

In [142]:
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)
kf

scores = cross_val_score(lr, x,y,cv=kf, scoring="r2")
print(scores.mean())

0.6472593260870108

### **MAE Cross Validation**

In [143]:
from sklearn.metrics import make_scorer
mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(lr,x,y,cv=kf,scoring=mae)
print(-scores)

[0.21255 0.21765 0.2139  0.22085 0.2168 ]

### **Decision Tree Regressor**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(x_train, y_train)
y_pred = dtr.predict(x_test)

In [154]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [155]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

In [156]:
print(mae)
print(mse)
print(rmse)
print(r2)

0.10595
0.11075
0.3327912258458747
0.827349745796469

### **MAE Cross Validation**

In [157]:
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)
kf

scores = cross_val_score(dtr, x,y,cv=kf, scoring="r2")
print(scores.mean())

0.8305331745914997

In [158]:
from sklearn.metrics import make_scorer
mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(dtr,x,y,cv=kf,scoring=mae)
print(-scores)

[0.10555 0.1062  0.1062  0.10795 0.10595]