# Model Building

In [425]:
import pandas as pd

In [ ]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_13/ai_assistant_usage_student_life.csv')

In [427]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SessionID           10000 non-null  object
 1   StudentLevel        10000 non-null  object
 2   Discipline          10000 non-null  object
 3   SessionDate         10000 non-null  object
 4   SessionLengthMin    10000 non-null  float64
 5   TotalPrompts        10000 non-null  int64
 6   TaskType            10000 non-null  object
 7   AI_AssistanceLevel  10000 non-null  int64
 8   FinalOutcome        10000 non-null  object
 9   UsedAgain           10000 non-null  bool
 10  SatisfactionRating  10000 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(6)
memory usage: 791.1+ KB

### filling missing values

In [428]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [429]:
df['SessionID'].value_counts()

SessionID
SESSION00001    1
SESSION06671    1
SESSION06664    1
SESSION06665    1
SESSION06666    1
               ..
SESSION03334    1
SESSION03335    1
SESSION03336    1
SESSION03337    1
SESSION10000    1
Name: count, Length: 10000, dtype: int64

### dropping columns that are not meaningful features

In [430]:
df.drop(columns='SessionID', axis=1, inplace=True)
df.drop(columns='SessionDate', axis=1, inplace=True)

In [431]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   StudentLevel        10000 non-null  object
 1   Discipline          10000 non-null  object
 2   SessionLengthMin    10000 non-null  float64
 3   TotalPrompts        10000 non-null  int64
 4   TaskType            10000 non-null  object
 5   AI_AssistanceLevel  10000 non-null  int64
 6   FinalOutcome        10000 non-null  object
 7   UsedAgain           10000 non-null  bool
 8   SatisfactionRating  10000 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(4)
memory usage: 634.9+ KB

In [432]:
df.sample(5)

,StudentLevel,Discipline,SessionLengthMin,TotalPrompts,TaskType,AI_AssistanceLevel,FinalOutcome,UsedAgain,SatisfactionRating
1909,High School,Biology,7.62,2,Homework Help,5,Assignment Completed,True,4.5
4232,Graduate,Biology,4.43,1,Coding,4,Assignment Completed,True,5.0
2531,Graduate,Computer Science,11.44,3,Coding,2,Confused,True,2.3
3681,Undergraduate,History,19.82,7,Writing,3,Idea Drafted,False,2.5
2426,High School,Computer Science,19.02,4,Writing,3,Assignment Completed,True,2.7

In [433]:
df['StudentLevel'].value_counts()

StudentLevel
Undergraduate    5978
High School      2027
Graduate         1995
Name: count, dtype: int64

### ORDINAL ENCODING

In [434]:
custom_mapping_dict = {
    'Undergraduate':0,
    'High School':1,
    'Graduate':2}

df['StudentLevel_Ordinal'] = df['StudentLevel'].map(custom_mapping_dict)

df.drop(columns='StudentLevel', axis=1, inplace=True)

In [435]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Discipline            10000 non-null  object
 1   SessionLengthMin      10000 non-null  float64
 2   TotalPrompts          10000 non-null  int64
 3   TaskType              10000 non-null  object
 4   AI_AssistanceLevel    10000 non-null  int64
 5   FinalOutcome          10000 non-null  object
 6   UsedAgain             10000 non-null  bool
 7   SatisfactionRating    10000 non-null  float64
 8   StudentLevel_Ordinal  10000 non-null  int64
dtypes: bool(1), float64(2), int64(3), object(3)
memory usage: 634.9+ KB

### FREQUENCY ENCODING

In [436]:
df['Discipline'].value_counts()

Discipline
Biology             1458
Computer Science    1445
Engineering         1430
Math                1422
Psychology          1418
History             1417
Business            1410
Name: count, dtype: int64

In [437]:
df['Discipline_frequency'] = df['Discipline'].map(df['Discipline'].value_counts())
df['TaskType_frequency'] = df['TaskType'].map(df['TaskType'].value_counts())
df['FinalOutcome_frequency'] = df['FinalOutcome'].map(df['FinalOutcome'].value_counts())

In [438]:
df.drop(columns='Discipline', axis=1, inplace=True)
df.drop(columns='TaskType', axis=1, inplace=True)
df.drop(columns='FinalOutcome', axis=1, inplace=True)

In [439]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SessionLengthMin        10000 non-null  float64
 1   TotalPrompts            10000 non-null  int64
 2   AI_AssistanceLevel      10000 non-null  int64
 3   UsedAgain               10000 non-null  bool
 4   SatisfactionRating      10000 non-null  float64
 5   StudentLevel_Ordinal    10000 non-null  int64
 6   Discipline_frequency    10000 non-null  int64
 7   TaskType_frequency      10000 non-null  int64
 8   FinalOutcome_frequency  10000 non-null  int64
dtypes: bool(1), float64(2), int64(6)
memory usage: 634.9 KB

### BOOLEAN TO INT

In [440]:
df['UsedAgain'] = df['UsedAgain'].astype(int)

In [441]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SessionLengthMin        10000 non-null  float64
 1   TotalPrompts            10000 non-null  int64
 2   AI_AssistanceLevel      10000 non-null  int64
 3   UsedAgain               10000 non-null  int32
 4   SatisfactionRating      10000 non-null  float64
 5   StudentLevel_Ordinal    10000 non-null  int64
 6   Discipline_frequency    10000 non-null  int64
 7   TaskType_frequency      10000 non-null  int64
 8   FinalOutcome_frequency  10000 non-null  int64
dtypes: float64(2), int32(1), int64(6)
memory usage: 664.2 KB

In [442]:
df.sample(5)

,SessionLengthMin,TotalPrompts,AI_AssistanceLevel,UsedAgain,SatisfactionRating,StudentLevel_Ordinal,Discipline_frequency,TaskType_frequency,FinalOutcome_frequency
9794,39.85,11,2,1,2.1,0,1417,1948,2866
4953,0.70,1,5,0,5.0,0,1422,2040,1613
4551,2.81,1,3,1,5.0,0,1422,476,2866
2989,7.32,2,4,0,3.3,1,1422,1959,4768
2202,15.51,5,4,1,2.1,1,1430,1959,2866

In [443]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler, LabelEncoder
standart=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [444]:
num_col=df.select_dtypes(include=['int64','float64','int32']).columns.tolist()

In [445]:
num_col

['SessionLengthMin',
 'TotalPrompts',
 'AI_AssistanceLevel',
 'UsedAgain',
 'SatisfactionRating',
 'StudentLevel_Ordinal',
 'Discipline_frequency',
 'TaskType_frequency',
 'FinalOutcome_frequency']

In [446]:
robust_cols = ['SessionLengthMin', 'Discipline_frequency', 'TaskType_frequency', 'FinalOutcome_frequency']
standard_cols = ['TotalPrompts']
minmax_cols = ['SatisfactionRating']

# Apply scalers
robust_scaler = RobustScaler()
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

df[robust_cols] = robust_scaler.fit_transform(df[robust_cols])
df[standard_cols] = standard_scaler.fit_transform(df[standard_cols])
df[minmax_cols] = minmax_scaler.fit_transform(df[minmax_cols])

In [447]:
df.sample(5)

,SessionLengthMin,TotalPrompts,AI_AssistanceLevel,UsedAgain,SatisfactionRating,StudentLevel_Ordinal,Discipline_frequency,TaskType_frequency,FinalOutcome_frequency
743,0.654930,-0.130686,5,0,0.85,1,0.821429,0.000000,-0.65878
8086,1.172535,0.299557,4,1,0.75,0,0.000000,0.000000,0.00000
7501,0.489437,0.514679,4,1,0.40,2,1.285714,0.920208,1.00000
4281,-0.152582,-0.345808,2,1,0.30,0,-0.178571,0.920208,0.00000
799,1.479460,1.590287,4,0,0.45,0,0.000000,0.000000,1.00000

# MODEL TRAINING

In [448]:
x = df.drop('UsedAgain', axis=1)

In [449]:
x

,SessionLengthMin,TotalPrompts,AI_AssistanceLevel,SatisfactionRating,StudentLevel_Ordinal,Discipline_frequency,TaskType_frequency,FinalOutcome_frequency
0,0.853873,1.160044,2,0.000,0,0.821429,0.000000,1.0
1,-0.208920,0.084435,3,0.250,0,-0.142857,0.000000,1.0
2,0.150822,-0.130686,3,0.575,0,-0.428571,-0.079792,1.0
3,-0.759977,-0.991173,3,0.625,0,0.821429,-0.079792,1.0
4,0.673122,0.729800,3,0.475,0,-0.142857,0.920208,1.0
...,...,...,...,...,...,...,...,...
9995,0.690141,-0.130686,3,0.800,0,-0.142857,0.000000,1.0
9996,-0.156690,0.084435,5,1.000,1,-0.428571,0.920208,1.0
9997,-0.344484,-0.776052,3,0.625,0,1.285714,0.000000,0.0
9998,0.835094,0.299557,3,0.825,0,-0.428571,0.920208,1.0
9999,-0.340376,-0.560930,4,0.975,0,0.000000,0.920208,1.0

In [450]:
y = df['UsedAgain']

In [451]:
y

0       1
1       1
2       1
3       1
4       1
       ..
9995    1
9996    1
9997    1
9998    0
9999    1
Name: UsedAgain, Length: 10000, dtype: int32

### SPLITTING DATA INTO TRAINING AND TESTING

In [452]:
from sklearn.model_selection import train_test_split

In [453]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [454]:
from sklearn.tree import DecisionTreeClassifier

In [455]:
model=DecisionTreeClassifier()

In [456]:
model

DecisionTreeClassifier()

In [457]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [458]:
y_prediction = model.predict(x_test)

In [459]:
y_prediction

array([0, 1, 1, ..., 1, 1, 1])

In [460]:
from sklearn.metrics import accuracy_score

In [461]:
accuracy = accuracy_score(y_test, y_prediction)

In [468]:
print(f'Accuracy is {accuracy*100}%')

Accuracy is 61.95%