In [1]:
import pandas as pd
df=pd.read_csv('appearances.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           object
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    object
 6   player_name             object
 7   competition_id          object
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), object(4)
memory usage: 169.3+ MB

In [3]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [45]:
df

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.053099,0.011541,0.060261,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.088351,0.001759,0.027279,0.000268,0.309524,0.0,0.0,0,0.166667,0.605442
...,...,...,...,...,...,...,...,...,...,...,...,...
1706801,0.999579,0.989370,0.587869,0.008921,0.008939,1.000000,0.285714,0.0,0.0,0,0.000000,0.557823
1706802,0.999579,0.989370,0.594094,0.008921,0.008939,1.000000,0.285714,0.5,0.0,0,0.000000,0.040816
1706803,0.999580,0.989370,0.669016,0.008921,0.008939,1.000000,0.285714,0.0,0.0,1,0.000000,0.605442
1706804,0.999581,0.989370,0.671276,0.008921,0.008939,1.000000,0.285714,0.0,0.0,0,0.000000,0.605442
1706805,0.999581,0.989370,0.067863,0.009429,0.009447,1.000000,0.285714,0.0,0.0,0,0.000000,0.258503

# Data bilan tanishuv

In [ ]:
# Xar bir feautureni manosini tushunish
# Target qiymatlarni 
# Keraksiz bolgan ustunlarni tashlab yuborish

In [4]:
df.drop('player_name',axis=1,inplace=True)

In [22]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,ELQ,0,0,0,1,90

# Data Preprocessing

In [5]:
#Missing qiymatlar
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [24]:
# Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [7]:
df=encodla(df)

In [9]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,13,0,0,0,1,90

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int32
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int32
 6   competition_id          int32
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int32(3), int64(9)
memory usage: 136.7 MB

In [12]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,13,0,0,0,1,90

In [31]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int32','int64']).columns.drop('goals')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [32]:
df=scaling_qil(df)

In [33]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.053099,0.011541,0.060261,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.088351,0.001759,0.027279,0.000268,0.309524,0.0,0.0,0,0.166667,0.605442

# Training

In [13]:
x=df.drop('goals',axis=1)

In [14]:
y=df['goals']

In [16]:
from sklearn.model_selection import  train_test_split

In [17]:
x_train, x_test,y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [18]:
df['goals'].value_counts()

goals
0    1560446
1     130986
2      13631
3       1572
4        147
5         23
6          1
Name: count, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int32
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int32
 6   competition_id          int32
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int32(3), int64(9)
memory usage: 136.7 MB

In [20]:
df.head(3)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,0,45

# Decesion Tree Regressor

In [41]:
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
dt_model=DecisionTreeRegressor()

In [22]:
dt_model

DecisionTreeRegressor()

In [23]:
# Fit--Traing
dt_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [24]:
#predict
y_pred=dt_model.predict(x_test)

In [25]:
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [26]:
#Model evaulation
from sklearn.metrics import  r2_score, mean_absolute_error,mean_squared_error, root_mean_squared_error

In [27]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [28]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)
print('rmse:',rmse)

r2: -0.8864189115047001
mae: 0.17013448115584268
mse: 0.20818214130872076
rmse: 0.45626981196296645

# Decesion Tree Classifier

In [42]:
dt_cl=DecisionTreeClassifier()

In [43]:
dt_cl.fit(x_train,y_train)

DecisionTreeClassifier()

In [44]:
y_pred=dt_cl.predict(x_test)

In [45]:
from sklearn.metrics import classification_report

In [46]:
class_report=classification_report(y_test,y_pred)

In [48]:
print(class_report)

              precision    recall  f1-score   support

           0       0.92      0.91      0.92    467980
           1       0.13      0.15      0.14     39371
           2       0.04      0.04      0.04      4150
           3       0.02      0.02      0.02       488
           4       0.00      0.00      0.00        47
           5       0.00      0.00      0.00         6

    accuracy                           0.85    512042
   macro avg       0.19      0.19      0.19    512042
weighted avg       0.85      0.85      0.85    512042

In [50]:
y.value_counts()

goals
0    1560446
1     130986
2      13631
3       1572
4        147
5         23
6          1
Name: count, dtype: int64

# Linear Regression

In [29]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()

In [30]:
lr_model.fit(x_train,y_train)

LinearRegression()

In [31]:
y_pred=lr_model.predict(x_test)

In [32]:
y_pred

array([0.0705823 , 0.11259353, 0.19249236, ..., 0.14086168, 0.10916532,
       0.10377112])

In [33]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [34]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)
print('rmse:',rmse)

r2: 0.011327693596871136
mae: 0.17356939789383716
mse: 0.10910827735259494
rmse: 0.3303154210033115

In [ ]:
r2: -0.8864189115047001
mae: 0.17013448115584268
mse: 0.20818214130872076
rmse: 0.4562698119629664

In [39]:
y.nunique()

7

# Logistic Regression

In [51]:
from sklearn.linear_model import LogisticRegression
lg_reg=LogisticRegression()

In [52]:
lg_reg.fit(x_train,y_train)

c:\Users\davro\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [53]:
y_pred=lg_reg.predict(x_test)

In [54]:
class_report=classification_report(y_test,y_pred)

c:\Users\davro\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\davro\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\davro\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
acc_score=accuracy_score(y_test,y_pred)

In [57]:
print(acc_score)

0.913948465164967

In [58]:
df=pd.read_csv('appearances.csv')

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           object
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    object
 6   player_name             object
 7   competition_id          object
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), object(4)
memory usage: 169.3+ MB