# Encoding

In [26]:
import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder

In [19]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_8/ShareRaceByCity.csv')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29268 entries, 0 to 29267
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Geographic area        29268 non-null  object
 1   City                   29268 non-null  object
 2   share_white            29268 non-null  object
 3   share_black            29268 non-null  object
 4   share_native_american  29268 non-null  object
 5   share_asian            29268 non-null  object
 6   share_hispanic         29268 non-null  object
dtypes: object(7)
memory usage: 1.6+ MB

In [21]:
df.sample(5)

,Geographic area,City,share_white,share_black,share_native_american,share_asian,share_hispanic
27427,WA,Edison CDP,95.5,2.3,0,0,0
9999,KY,Hebron CDP,92.8,2.9,0.3,0.6,3.5
15442,NE,Pierce city,98.9,0,0.3,0.2,1.2
24364,TN,Portland city,92.4,3.5,0.3,0.5,3.9
1815,AR,Roland CDP,89.9,7.2,0.8,0.3,3.1

In [22]:
df['Geographic area'].nunique()

51

### One-hot encoding

In [23]:
df=pd.get_dummies(df,columns=['Geographic area'],prefix='states', dtype=int)

In [25]:
df.sample(5)

,City,share_white,share_black,share_native_american,share_asian,share_hispanic,states_AK,states_AL,states_AR,states_AZ,...,states_SD,states_TN,states_TX,states_UT,states_VA,states_VT,states_WA,states_WI,states_WV,states_WY
24785,Concepcion CDP,88.7,0,0,0,100,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1245,St. Johns city,82.6,0.1,5.3,0.3,25.3,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18274,Granite Quarry town,87.5,8.3,0.2,1.1,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26124,Villa del Sol CDP,81.7,0,0,0,95.4,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
10096,Meadowview Estates city,77.7,17.4,0,1.7,4.4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29268 entries, 0 to 29267
Data columns (total 57 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   City                   29268 non-null  object
 1   share_white            29268 non-null  object
 2   share_black            29268 non-null  object
 3   share_native_american  29268 non-null  object
 4   share_asian            29268 non-null  object
 5   share_hispanic         29268 non-null  object
 6   states_AK              29268 non-null  int32
 7   states_AL              29268 non-null  int32
 8   states_AR              29268 non-null  int32
 9   states_AZ              29268 non-null  int32
 10  states_CA              29268 non-null  int32
 11  states_CO              29268 non-null  int32
 12  states_CT              29268 non-null  int32
 13  states_DC              29268 non-null  int32
 14  states_DE              29268 non-null  int32
 15  states_FL              29268 non-null  int32
 16  states_GA              29268 non-null  int32
 17  states_HI              29268 non-null  int32
 18  states_IA              29268 non-null  int32
 19  states_ID              29268 non-null  int32
 20  states_IL              29268 non-null  int32
 21  states_IN              29268 non-null  int32
 22  states_KS              29268 non-null  int32
 23  states_KY              29268 non-null  int32
 24  states_LA              29268 non-null  int32
 25  states_MA              29268 non-null  int32
 26  states_MD              29268 non-null  int32
 27  states_ME              29268 non-null  int32
 28  states_MI              29268 non-null  int32
 29  states_MN              29268 non-null  int32
 30  states_MO              29268 non-null  int32
 31  states_MS              29268 non-null  int32
 32  states_MT              29268 non-null  int32
 33  states_NC              29268 non-null  int32
 34  states_ND              29268 non-null  int32
 35  states_NE              29268 non-null  int32
 36  states_NH              29268 non-null  int32
 37  states_NJ              29268 non-null  int32
 38  states_NM              29268 non-null  int32
 39  states_NV              29268 non-null  int32
 40  states_NY              29268 non-null  int32
 41  states_OH              29268 non-null  int32
 42  states_OK              29268 non-null  int32
 43  states_OR              29268 non-null  int32
 44  states_PA              29268 non-null  int32
 45  states_RI              29268 non-null  int32
 46  states_SC              29268 non-null  int32
 47  states_SD              29268 non-null  int32
 48  states_TN              29268 non-null  int32
 49  states_TX              29268 non-null  int32
 50  states_UT              29268 non-null  int32
 51  states_VA              29268 non-null  int32
 52  states_VT              29268 non-null  int32
 53  states_WA              29268 non-null  int32
 54  states_WI              29268 non-null  int32
 55  states_WV              29268 non-null  int32
 56  states_WY              29268 non-null  int32
dtypes: int32(51), object(6)
memory usage: 7.0+ MB

### LABEL ENCODING

In [29]:
encoder = LabelEncoder()

In [30]:
df['share_white']=encoder.fit_transform(df['share_white'])

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29268 entries, 0 to 29267
Data columns (total 57 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   City                   29268 non-null  object
 1   share_white            29268 non-null  int32
 2   share_black            29268 non-null  object
 3   share_native_american  29268 non-null  object
 4   share_asian            29268 non-null  object
 5   share_hispanic         29268 non-null  object
 6   states_AK              29268 non-null  int32
 7   states_AL              29268 non-null  int32
 8   states_AR              29268 non-null  int32
 9   states_AZ              29268 non-null  int32
 10  states_CA              29268 non-null  int32
 11  states_CO              29268 non-null  int32
 12  states_CT              29268 non-null  int32
 13  states_DC              29268 non-null  int32
 14  states_DE              29268 non-null  int32
 15  states_FL              29268 non-null  int32
 16  states_GA              29268 non-null  int32
 17  states_HI              29268 non-null  int32
 18  states_IA              29268 non-null  int32
 19  states_ID              29268 non-null  int32
 20  states_IL              29268 non-null  int32
 21  states_IN              29268 non-null  int32
 22  states_KS              29268 non-null  int32
 23  states_KY              29268 non-null  int32
 24  states_LA              29268 non-null  int32
 25  states_MA              29268 non-null  int32
 26  states_MD              29268 non-null  int32
 27  states_ME              29268 non-null  int32
 28  states_MI              29268 non-null  int32
 29  states_MN              29268 non-null  int32
 30  states_MO              29268 non-null  int32
 31  states_MS              29268 non-null  int32
 32  states_MT              29268 non-null  int32
 33  states_NC              29268 non-null  int32
 34  states_ND              29268 non-null  int32
 35  states_NE              29268 non-null  int32
 36  states_NH              29268 non-null  int32
 37  states_NJ              29268 non-null  int32
 38  states_NM              29268 non-null  int32
 39  states_NV              29268 non-null  int32
 40  states_NY              29268 non-null  int32
 41  states_OH              29268 non-null  int32
 42  states_OK              29268 non-null  int32
 43  states_OR              29268 non-null  int32
 44  states_PA              29268 non-null  int32
 45  states_RI              29268 non-null  int32
 46  states_SC              29268 non-null  int32
 47  states_SD              29268 non-null  int32
 48  states_TN              29268 non-null  int32
 49  states_TX              29268 non-null  int32
 50  states_UT              29268 non-null  int32
 51  states_VA              29268 non-null  int32
 52  states_VT              29268 non-null  int32
 53  states_WA              29268 non-null  int32
 54  states_WI              29268 non-null  int32
 55  states_WV              29268 non-null  int32
 56  states_WY              29268 non-null  int32
dtypes: int32(52), object(5)
memory usage: 6.9+ MB

In [40]:
df.isna().sum()

City                     0
share_white              0
share_black              0
share_native_american    0
share_asian              0
share_hispanic           0
states_AK                0
states_AL                0
states_AR                0
states_AZ                0
states_CA                0
states_CO                0
states_CT                0
states_DC                0
states_DE                0
states_FL                0
states_GA                0
states_HI                0
states_IA                0
states_ID                0
states_IL                0
states_IN                0
states_KS                0
states_KY                0
states_LA                0
states_MA                0
states_MD                0
states_ME                0
states_MI                0
states_MN                0
states_MO                0
states_MS                0
states_MT                0
states_NC                0
states_ND                0
states_NE                0
states_NH                0
states_NJ                0
states_NM                0
states_NV                0
states_NY                0
states_OH                0
states_OK                0
states_OR                0
states_PA                0
states_RI                0
states_SC                0
states_SD                0
states_TN                0
states_TX                0
states_UT                0
states_VA                0
states_VT                0
states_WA                0
states_WI                0
states_WV                0
states_WY                0
dtype: int64

### TASK FOR LOOP

###  1 dan 100 gacha bolgan sonlar ichida 5 ga bolinadiganlarini ekranga chiqaring(2 xil usulda)

In [34]:
numbers = []
for i in range(1, 100):
    if i%5==0:
        numbers.append(i)
print(numbers)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [38]:
for i in range(0, 100, 5):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95

### 2 Berilgan listdagi sonlar ichida faqat musbat va juftlarini ekranga chiqaring([-2,3,4,-5,6,7]) ekranga chiqaring

In [39]:
list = [-2,3,4,-5,6,7]
for i in list:
    if i%2==0 and i>0:
        print(i)

4
6