# Lesson 9 Tasks

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_9/us_house_Sales_data.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Price           3000 non-null   object
 1   Address         3000 non-null   object
 2   City            3000 non-null   object
 3   Zipcode         3000 non-null   int64
 4   State           3000 non-null   object
 5   Bedrooms        3000 non-null   object
 6   Bathrooms       3000 non-null   object
 7   Area (Sqft)     3000 non-null   object
 8   Lot Size        3000 non-null   object
 9   Year Built      2990 non-null   float64
 10  Days on Market  2986 non-null   float64
 11  Property Type   3000 non-null   object
 12  MLS ID          3000 non-null   object
 13  Listing Agent   3000 non-null   object
 14  Status          3000 non-null   object
 15  Listing URL     3000 non-null   object
dtypes: float64(2), int64(1), object(13)
memory usage: 375.1+ KB

In [8]:
df.columns

Index(['Price', 'Address', 'City', 'Zipcode', 'State', 'Bedrooms', 'Bathrooms',
       'Area (Sqft)', 'Lot Size', 'Year Built', 'Days on Market',
       'Property Type', 'MLS ID', 'Listing Agent', 'Status', 'Listing URL'],
      dtype='object')

###

In [9]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

In [11]:
df.isna().sum()

Price             0
Address           0
City              0
Zipcode           0
State             0
Bedrooms          0
Bathrooms         0
Area (Sqft)       0
Lot Size          0
Year Built        0
Days on Market    0
Property Type     0
MLS ID            0
Listing Agent     0
Status            0
Listing URL       0
dtype: int64

In [12]:
df.sample(5)

,Price,Address,City,Zipcode,State,Bedrooms,Bathrooms,Area (Sqft),Lot Size,Year Built,Days on Market,Property Type,MLS ID,Listing Agent,Status,Listing URL
151,"$1,021,673","8746 Elm St, San Francisco, FL 78745",San Francisco,78745,FL,4 bds,2 ba,3019 sqft,8469 sqft,1969.0,57.0,Condo,Z974190,Mike Lee - Coldwell Banker,Sold,https://www.zillow.com/homedetails/61200601_zpid/
2517,"$1,262,766","3197 Pine Rd, Sacramento, TX 63296",Sacramento,63296,TX,4 bds,3 ba,3424 sqft,3819 sqft,1977.0,90.0,Apartment,Z294341,Emily Davis - Century 21,For Sale,https://www.zillow.com/homedetails/63663724_zpid/
2781,"$234,244","2286 Pine Rd, Los Angeles, TX 94702",Los Angeles,94702,TX,2 bds,2 ba,748 sqft,3418 sqft,1998.0,78.0,Multi-Family,Z855121,Jane Smith - Keller Williams,Pending,https://www.zillow.com/homedetails/46398337_zpid/
1625,"$104,321","8769 Pine Rd, Sacramento, IL 72702",Sacramento,72702,IL,1 bds,1 ba,1951 sqft,4375 sqft,1985.0,42.0,Condo,Z780787,Alex Johnson - Compass,Pending,https://www.zillow.com/homedetails/86002312_zpid/
2648,"$176,303","2087 Maple Dr, San Francisco, NY 55776",San Francisco,55776,NY,1 bds,1 ba,3194 sqft,3870 sqft,1950.0,69.0,Multi-Family,Z537139,Alex Johnson - Compass,Sold,https://www.zillow.com/homedetails/35156588_zpid/

## One-hot encoding

In [13]:
df=pd.get_dummies(df,columns=['Bathrooms'],prefix='bath_num',dtype=int)

In [15]:
df.columns

Index(['Price', 'Address', 'City', 'Zipcode', 'State', 'Bedrooms',
       'Area (Sqft)', 'Lot Size', 'Year Built', 'Days on Market',
       'Property Type', 'MLS ID', 'Listing Agent', 'Status', 'Listing URL',
       'bath_num_1 ba', 'bath_num_2 ba', 'bath_num_3 ba', 'bath_num_4 ba'],
      dtype='object')

## Label Encoding

In [17]:
encoder = LabelEncoder()
encoder

LabelEncoder()

In [18]:
df['Status'] = encoder.fit_transform(df['Status'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Price           3000 non-null   object
 1   Address         3000 non-null   object
 2   City            3000 non-null   object
 3   Zipcode         3000 non-null   int64
 4   State           3000 non-null   object
 5   Bedrooms        3000 non-null   object
 6   Area (Sqft)     3000 non-null   object
 7   Lot Size        3000 non-null   object
 8   Year Built      3000 non-null   float64
 9   Days on Market  3000 non-null   float64
 10  Property Type   3000 non-null   object
 11  MLS ID          3000 non-null   object
 12  Listing Agent   3000 non-null   object
 13  Status          3000 non-null   int32
 14  Listing URL     3000 non-null   object
 15  bath_num_1 ba   3000 non-null   int32
 16  bath_num_2 ba   3000 non-null   int32
 17  bath_num_3 ba   3000 non-null   int32
 18  bath_num_4 ba   3000 non-null   int32
dtypes: float64(2), int32(5), int64(1), object(11)
memory usage: 386.8+ KB

## Frequence Encoding

In [20]:
df.sample()

,Price,Address,City,Zipcode,State,Bedrooms,Area (Sqft),Lot Size,Year Built,Days on Market,Property Type,MLS ID,Listing Agent,Status,Listing URL,bath_num_1 ba,bath_num_2 ba,bath_num_3 ba,bath_num_4 ba
1226,"$445,101","2740 Elm St, Los Angeles, CA 52810",Los Angeles,52810,CA,6 bds,1624 sqft,5436 sqft,1975.0,117.0,Apartment,Z684218,John Doe - RE/MAX,2,https://www.zillow.com/homedetails/98604018_zpid/,0,0,1,0

In [21]:
df['Bedroom_freq']=df['Bedrooms'].map(df['Bedrooms'].value_counts())

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Price           3000 non-null   object
 1   Address         3000 non-null   object
 2   City            3000 non-null   object
 3   Zipcode         3000 non-null   int64
 4   State           3000 non-null   object
 5   Bedrooms        3000 non-null   object
 6   Area (Sqft)     3000 non-null   object
 7   Lot Size        3000 non-null   object
 8   Year Built      3000 non-null   float64
 9   Days on Market  3000 non-null   float64
 10  Property Type   3000 non-null   object
 11  MLS ID          3000 non-null   object
 12  Listing Agent   3000 non-null   object
 13  Status          3000 non-null   int32
 14  Listing URL     3000 non-null   object
 15  bath_num_1 ba   3000 non-null   int32
 16  bath_num_2 ba   3000 non-null   int32
 17  bath_num_3 ba   3000 non-null   int32
 18  bath_num_4 ba   3000 non-null   int32
 19  Bedroom_freq    3000 non-null   int64
dtypes: float64(2), int32(5), int64(2), object(11)
memory usage: 410.3+ KB

In [28]:
df.sample(10)

,Price,Address,City,Zipcode,State,Bedrooms,Area (Sqft),Lot Size,Year Built,Days on Market,Property Type,MLS ID,Listing Agent,Status,Listing URL,bath_num_1 ba,bath_num_2 ba,bath_num_3 ba,bath_num_4 ba,Bedroom_freq
1510,"$102,028","4880 Elm St, Fresno, CA 60495",Fresno,60495,CA,1 bds,1824 sqft,8908 sqft,1975.0,42.0,Townhouse,Z103938,Jane Smith - Keller Williams,0,https://www.zillow.com/homedetails/70050549_zpid/,0,1,0,0,494
1629,"$531,098","5999 Maple Dr, Fresno, IL 51303",Fresno,51303,IL,1 bds,3332 sqft,3979 sqft,1958.0,9.0,Single Family,Z590213,Alex Johnson - Compass,2,https://www.zillow.com/homedetails/48410973_zpid/,0,0,1,0,494
1221,"$1,427,202","4783 Elm St, San Francisco, IL 97697",San Francisco,97697,IL,6 bds,1396 sqft,8997 sqft,2009.0,95.0,Townhouse,Z638274,John Doe - RE/MAX,0,https://www.zillow.com/homedetails/61811939_zpid/,1,0,0,0,502
1870,"$450,980","5500 Oak Ave, Sacramento, NY 44660",Sacramento,44660,NY,3 bds,3967 sqft,9785 sqft,2021.0,53.0,Single Family,Z250212,Mike Lee - Coldwell Banker,2,https://www.zillow.com/homedetails/51006778_zpid/,1,0,0,0,518
1717,"$788,063","8999 Pine Rd, Sacramento, IL 54548",Sacramento,54548,IL,2 bds,2405 sqft,9872 sqft,1973.0,106.0,Townhouse,Z716530,Jane Smith - Keller Williams,2,https://www.zillow.com/homedetails/99657400_zpid/,0,0,1,0,533
1857,"$624,172","9687 Oak Ave, Fresno, CA 58626",Fresno,58626,CA,6 bds,1607 sqft,6024 sqft,2022.0,26.0,Condo,Z615545,Jane Smith - Keller Williams,0,https://www.zillow.com/homedetails/43013367_zpid/,0,0,1,0,502
32,"$630,339","4020 Elm St, San Diego, IL 93752",San Diego,93752,IL,1 bds,1752 sqft,3040 sqft,1993.0,61.0,Single Family,Z221816,Mike Lee - Coldwell Banker,0,https://www.zillow.com/homedetails/67849427_zpid/,0,0,0,1,494
2082,"$1,063,868","9282 Maple Dr, San Francisco, TX 96466",San Francisco,96466,TX,5 bds,3750 sqft,3199 sqft,1984.0,103.0,Condo,Z160592,Emily Davis - Century 21,2,https://www.zillow.com/homedetails/25417671_zpid/,0,0,1,0,471
2207,"$835,365","764 Oak Ave, Fresno, IL 19990",Fresno,19990,IL,4 bds,936 sqft,7113 sqft,1996.0,77.0,Condo,Z191315,Mike Lee - Coldwell Banker,1,https://www.zillow.com/homedetails/46876466_zpid/,1,0,0,0,482
2021,"$1,202,188","2343 Oak Ave, San Diego, CA 14862",San Diego,14862,CA,1 bds,965 sqft,2591 sqft,2019.0,107.0,Single Family,Z304000,John Doe - RE/MAX,1,https://www.zillow.com/homedetails/70342182_zpid/,1,0,0,0,494

In [26]:
df.Bedroom_freq.value_counts()

Bedroom_freq
533    533
518    518
502    502
494    494
482    482
471    471
Name: count, dtype: int64

##

# Target Encoding

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Price           3000 non-null   object
 1   Address         3000 non-null   object
 2   City            3000 non-null   object
 3   Zipcode         3000 non-null   int64
 4   State           3000 non-null   object
 5   Bedrooms        3000 non-null   object
 6   Area (Sqft)     3000 non-null   object
 7   Lot Size        3000 non-null   object
 8   Year Built      3000 non-null   float64
 9   Days on Market  3000 non-null   float64
 10  Property Type   3000 non-null   object
 11  MLS ID          3000 non-null   object
 12  Listing Agent   3000 non-null   object
 13  Status          3000 non-null   int32
 14  Listing URL     3000 non-null   object
 15  bath_num_1 ba   3000 non-null   int32
 16  bath_num_2 ba   3000 non-null   int32
 17  bath_num_3 ba   3000 non-null   int32
 18  bath_num_4 ba   3000 non-null   int32
 19  Bedroom_freq    3000 non-null   int64
dtypes: float64(2), int32(5), int64(2), object(11)
memory usage: 410.3+ KB

In [30]:
df.sample(5)

,Price,Address,City,Zipcode,State,Bedrooms,Area (Sqft),Lot Size,Year Built,Days on Market,Property Type,MLS ID,Listing Agent,Status,Listing URL,bath_num_1 ba,bath_num_2 ba,bath_num_3 ba,bath_num_4 ba,Bedroom_freq
560,"$478,198","894 Oak Ave, San Diego, CA 43152",San Diego,43152,CA,2 bds,2971 sqft,1846 sqft,1997.0,1.0,Townhouse,Z592854,Jane Smith - Keller Williams,1,https://www.zillow.com/homedetails/55174186_zpid/,0,0,1,0,533
1113,"$1,333,651","4556 Maple Dr, Los Angeles, NY 60214",Los Angeles,60214,NY,5 bds,792 sqft,6054 sqft,2004.0,35.0,Multi-Family,Z942395,Jane Smith - Keller Williams,1,https://www.zillow.com/homedetails/99902119_zpid/,0,1,0,0,471
2915,"$617,079","6567 Elm St, Sacramento, CA 98321",Sacramento,98321,CA,2 bds,2151 sqft,2613 sqft,2020.0,82.0,Single Family,Z319387,Mike Lee - Coldwell Banker,1,https://www.zillow.com/homedetails/79880597_zpid/,0,0,0,1,533
1957,"$892,712","2653 Oak Ave, Sacramento, NY 97171",Sacramento,97171,NY,6 bds,1370 sqft,4487 sqft,1974.0,11.0,Townhouse,Z169824,Emily Davis - Century 21,1,https://www.zillow.com/homedetails/45860146_zpid/,0,1,0,0,502
2951,"$465,743","7952 Oak Ave, San Francisco, NY 54506",San Francisco,54506,NY,3 bds,2826 sqft,8121 sqft,1962.0,106.0,Apartment,Z532627,John Doe - RE/MAX,1,https://www.zillow.com/homedetails/52995000_zpid/,0,1,0,0,518

In [31]:
target_encoding = df.groupby('City')['Days on Market'].mean()
df['City_Encoded'] = df['City'].map(target_encoding)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Price           3000 non-null   object
 1   Address         3000 non-null   object
 2   City            3000 non-null   object
 3   Zipcode         3000 non-null   int64
 4   State           3000 non-null   object
 5   Bedrooms        3000 non-null   object
 6   Area (Sqft)     3000 non-null   object
 7   Lot Size        3000 non-null   object
 8   Year Built      3000 non-null   float64
 9   Days on Market  3000 non-null   float64
 10  Property Type   3000 non-null   object
 11  MLS ID          3000 non-null   object
 12  Listing Agent   3000 non-null   object
 13  Status          3000 non-null   int32
 14  Listing URL     3000 non-null   object
 15  bath_num_1 ba   3000 non-null   int32
 16  bath_num_2 ba   3000 non-null   int32
 17  bath_num_3 ba   3000 non-null   int32
 18  bath_num_4 ba   3000 non-null   int32
 19  Bedroom_freq    3000 non-null   int64
 20  City_Encoded    3000 non-null   float64
dtypes: float64(3), int32(5), int64(2), object(11)
memory usage: 433.7+ KB

### I didn't delete the original City column

In [33]:
df.sample(5)

,Price,Address,City,Zipcode,State,Bedrooms,Area (Sqft),Lot Size,Year Built,Days on Market,...,MLS ID,Listing Agent,Status,Listing URL,bath_num_1 ba,bath_num_2 ba,bath_num_3 ba,bath_num_4 ba,Bedroom_freq,City_Encoded
1045,"$173,054","4745 Elm St, San Diego, FL 21488",San Diego,21488,FL,1 bds,3340 sqft,9797 sqft,1986.0,68.0,...,Z131536,Mike Lee - Coldwell Banker,1,https://www.zillow.com/homedetails/31883861_zpid/,0,0,1,0,494,62.691166
1900,"$462,942","5861 Pine Rd, Los Angeles, FL 21056",Los Angeles,21056,FL,6 bds,1380 sqft,5869 sqft,1996.0,31.0,...,Z846549,Jane Smith - Keller Williams,2,https://www.zillow.com/homedetails/45444704_zpid/,1,0,0,0,502,61.579436
1503,"$1,424,084","1443 Elm St, Fresno, FL 12119",Fresno,12119,FL,2 bds,1349 sqft,1884 sqft,1976.0,83.0,...,Z143856,Jane Smith - Keller Williams,0,https://www.zillow.com/homedetails/18602823_zpid/,1,0,0,0,533,61.784315
70,"$1,103,898","8234 Elm St, Sacramento, TX 36251",Sacramento,36251,TX,2 bds,1088 sqft,4186 sqft,1983.0,58.0,...,Z738821,John Doe - RE/MAX,2,https://www.zillow.com/homedetails/99412177_zpid/,1,0,0,0,533,60.816130
569,"$524,279","834 Main St, Los Angeles, CA 45798",Los Angeles,45798,CA,4 bds,2371 sqft,4972 sqft,1979.0,86.0,...,Z802108,John Doe - RE/MAX,2,https://www.zillow.com/homedetails/24257923_zpid/,1,0,0,0,482,61.579436

In [34]:
df.City_Encoded.value_counts()

City_Encoded
61.579436    617
60.816130    609
59.469037    605
62.691166    586
61.784315    583
Name: count, dtype: int64

# Ordinal encoding

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Price           3000 non-null   object
 1   Address         3000 non-null   object
 2   City            3000 non-null   object
 3   Zipcode         3000 non-null   int64
 4   State           3000 non-null   object
 5   Bedrooms        3000 non-null   object
 6   Area (Sqft)     3000 non-null   object
 7   Lot Size        3000 non-null   object
 8   Year Built      3000 non-null   float64
 9   Days on Market  3000 non-null   float64
 10  Property Type   3000 non-null   object
 11  MLS ID          3000 non-null   object
 12  Listing Agent   3000 non-null   object
 13  Status          3000 non-null   int32
 14  Listing URL     3000 non-null   object
 15  bath_num_1 ba   3000 non-null   int32
 16  bath_num_2 ba   3000 non-null   int32
 17  bath_num_3 ba   3000 non-null   int32
 18  bath_num_4 ba   3000 non-null   int32
 19  Bedroom_freq    3000 non-null   int64
 20  City_Encoded    3000 non-null   float64
dtypes: float64(3), int32(5), int64(2), object(11)
memory usage: 433.7+ KB

In [38]:
df['Property Type'].value_counts()

Property Type
Apartment        622
Condo            617
Townhouse        614
Single Family    583
Multi-Family     564
Name: count, dtype: int64

In [39]:
property_mapping={
    'Apartment':0,
    'Condo':1,
    'Townhouse':2,
    'Single Family':3,
    'Multi-Family':4
}

df['property_ordinal'] = df['Property Type'].map(property_mapping)

### I didnt delete original Propety type column

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             3000 non-null   object
 1   Address           3000 non-null   object
 2   City              3000 non-null   object
 3   Zipcode           3000 non-null   int64
 4   State             3000 non-null   object
 5   Bedrooms          3000 non-null   object
 6   Area (Sqft)       3000 non-null   object
 7   Lot Size          3000 non-null   object
 8   Year Built        3000 non-null   float64
 9   Days on Market    3000 non-null   float64
 10  Property Type     3000 non-null   object
 11  MLS ID            3000 non-null   object
 12  Listing Agent     3000 non-null   object
 13  Status            3000 non-null   int32
 14  Listing URL       3000 non-null   object
 15  bath_num_1 ba     3000 non-null   int32
 16  bath_num_2 ba     3000 non-null   int32
 17  bath_num_3 ba     3000 non-null   int32
 18  bath_num_4 ba     3000 non-null   int32
 19  Bedroom_freq      3000 non-null   int64
 20  City_Encoded      3000 non-null   float64
 21  property_ordinal  3000 non-null   int64
dtypes: float64(3), int32(5), int64(3), object(11)
memory usage: 457.2+ KB

# DATA CLEANING

In [41]:
df.Price.value_counts()

Price
$1,280,680    2
$102,028      2
$1,387,365    2
$672,952      2
$634,979      1
             ..
$872,311      1
$1,123,484    1
$908,029      1
$858,758      1
$712,029      1
Name: count, Length: 2996, dtype: int64

In [42]:
df['Price']=df['Price'].str.replace(r'[^\d.]','', regex=True).astype(float)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             3000 non-null   float64
 1   Address           3000 non-null   object
 2   City              3000 non-null   object
 3   Zipcode           3000 non-null   int64
 4   State             3000 non-null   object
 5   Bedrooms          3000 non-null   object
 6   Area (Sqft)       3000 non-null   object
 7   Lot Size          3000 non-null   object
 8   Year Built        3000 non-null   float64
 9   Days on Market    3000 non-null   float64
 10  Property Type     3000 non-null   object
 11  MLS ID            3000 non-null   object
 12  Listing Agent     3000 non-null   object
 13  Status            3000 non-null   int32
 14  Listing URL       3000 non-null   object
 15  bath_num_1 ba     3000 non-null   int32
 16  bath_num_2 ba     3000 non-null   int32
 17  bath_num_3 ba     3000 non-null   int32
 18  bath_num_4 ba     3000 non-null   int32
 19  Bedroom_freq      3000 non-null   int64
 20  City_Encoded      3000 non-null   float64
 21  property_ordinal  3000 non-null   int64
dtypes: float64(4), int32(5), int64(3), object(10)
memory usage: 457.2+ KB

# ANSWERS

### Outputga  bog’liq bolgan ecoding turi?
 ### Eng oson encoding turi?
 ### Eng kop va kam ishlatiladigan encoding turi?

1. Outputga bog'liq bo'lgan encoding turi: Target encoding

2. Eng oson encoding turi: Ordinal encoding

3. Eng ko'p ishlatiladigan encoding turi: one-hot encoding, Label encoding