# Data Preprocessing

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('nyc_temperature.csv')

In [5]:
data.head()

,date,tmax,tmin,tavg,departure,HDD,CDD,precipitation,new_snow,snow_depth
0,1/1/19,60,40,50.0,13.9,15,0,0.08,0,0
1,2/1/19,41,35,38.0,2.1,27,0,0,0,0
2,3/1/19,45,39,42.0,6.3,23,0,T,0,0
3,4/1/19,47,37,42.0,6.5,23,0,0,0,0
4,5/1/19,47,42,44.5,9.1,20,0,0.45,0,0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           365 non-null    object
 1   tmax           365 non-null    int64
 2   tmin           365 non-null    int64
 3   tavg           365 non-null    float64
 4   departure      365 non-null    float64
 5   HDD            365 non-null    int64
 6   CDD            365 non-null    int64
 7   precipitation  365 non-null    object
 8   new_snow       365 non-null    object
 9   snow_depth     365 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 28.6+ KB

In [7]:
data.isnull().sum()

date             0
tmax             0
tmin             0
tavg             0
departure        0
HDD              0
CDD              0
precipitation    0
new_snow         0
snow_depth       0
dtype: int64

In [10]:
df = pd.read_csv('world_bank_data_2025.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3472 entries, 0 to 3471
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country_name                     3472 non-null   object
 1   country_id                       3472 non-null   object
 2   year                             3472 non-null   int64
 3   Inflation (CPI %)                2694 non-null   float64
 4   GDP (Current USD)                2933 non-null   float64
 5   GDP per Capita (Current USD)     2938 non-null   float64
 6   Unemployment Rate (%)            2795 non-null   float64
 7   Interest Rate (Real, %)          1735 non-null   float64
 8   Inflation (GDP Deflator, %)      2904 non-null   float64
 9   GDP Growth (% Annual)            2912 non-null   float64
 10  Current Account Balance (% GDP)  2563 non-null   float64
 11  Government Expense (% of GDP)    1820 non-null   float64
 12  Government Revenue (% of GDP)    1829 non-null   float64
 13  Tax Revenue (% of GDP)           1833 non-null   float64
 14  Gross National Income (USD)      2796 non-null   float64
 15  Public Debt (% of GDP)           852 non-null    float64
dtypes: float64(13), int64(1), object(2)
memory usage: 434.1+ KB

In [12]:
df.head()

,country_name,country_id,year,Inflation (CPI %),GDP (Current USD),GDP per Capita (Current USD),Unemployment Rate (%),"Interest Rate (Real, %)","Inflation (GDP Deflator, %)",GDP Growth (% Annual),Current Account Balance (% GDP),Government Expense (% of GDP),Government Revenue (% of GDP),Tax Revenue (% of GDP),Gross National Income (USD),Public Debt (% of GDP)
0,Aruba,aw,2010,2.078141,2.453597e+09,24093.140151,NaN,11.666131,-1.223407,-2.733457,-18.752537,NaN,NaN,NaN,2.313385e+09,NaN
1,Aruba,aw,2011,4.316297,2.637859e+09,25712.384302,NaN,4.801974,4.005674,3.369237,-9.877656,NaN,NaN,NaN,2.391841e+09,NaN
2,Aruba,aw,2012,0.627472,2.615208e+09,25119.665545,NaN,8.200875,0.184033,-1.040800,3.473451,NaN,NaN,NaN,2.499118e+09,NaN
3,Aruba,aw,2013,-2.372065,2.727850e+09,25813.576727,NaN,10.709709,-1.995948,6.431483,-11.813206,NaN,NaN,NaN,2.563517e+09,NaN
4,Aruba,aw,2014,0.421441,2.790850e+09,26129.839062,NaN,3.213869,3.958897,-1.586575,-4.658577,NaN,NaN,NaN,2.688102e+09,NaN

In [13]:
df.isnull().sum()

country_name                          0
country_id                            0
year                                  0
Inflation (CPI %)                   778
GDP (Current USD)                   539
GDP per Capita (Current USD)        534
Unemployment Rate (%)               677
Interest Rate (Real, %)            1737
Inflation (GDP Deflator, %)         568
GDP Growth (% Annual)               560
Current Account Balance (% GDP)     909
Government Expense (% of GDP)      1652
Government Revenue (% of GDP)      1643
Tax Revenue (% of GDP)             1639
Gross National Income (USD)         676
Public Debt (% of GDP)             2620
dtype: int64

In [14]:
df['Inflation (CPI %)'].fillna(df['Inflation (CPI %)'].mean(),inplace=True)

C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\2297522192.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Inflation (CPI %)'].fillna(df['Inflation (CPI %)'].mean(),inplace=True)

In [15]:
df.isnull().sum()

country_name                          0
country_id                            0
year                                  0
Inflation (CPI %)                     0
GDP (Current USD)                   539
GDP per Capita (Current USD)        534
Unemployment Rate (%)               677
Interest Rate (Real, %)            1737
Inflation (GDP Deflator, %)         568
GDP Growth (% Annual)               560
Current Account Balance (% GDP)     909
Government Expense (% of GDP)      1652
Government Revenue (% of GDP)      1643
Tax Revenue (% of GDP)             1639
Gross National Income (USD)         676
Public Debt (% of GDP)             2620
dtype: int64

In [16]:
df['GDP (Current USD)'].fillna(df['GDP (Current USD)'].mean(),inplace=True)
df['GDP per Capita (Current USD)'].fillna(df['GDP per Capita (Current USD)'].mean(),inplace=True)
df['Unemployment Rate (%)'].fillna(df['Unemployment Rate (%)'].mean(),inplace=True)
df['Interest Rate (Real, %)'].fillna(df['Interest Rate (Real, %)'].mode()[0],inplace=True)
df['Inflation (GDP Deflator, %)'].fillna(df['Inflation (GDP Deflator, %)'].mode()[0],inplace=True)
df['GDP Growth (% Annual)'].fillna(df['GDP Growth (% Annual)'].mode()[0],inplace=True)
df['Current Account Balance (% GDP)'].fillna(df['Current Account Balance (% GDP)'].mean(),inplace=True)
df['Government Expense (% of GDP)'].fillna(df['Government Expense (% of GDP)'].mean(),inplace=True)
df['Government Revenue (% of GDP)'].fillna(df['Government Revenue (% of GDP)'].mean(),inplace=True)
df['Tax Revenue (% of GDP)'].fillna(df['Tax Revenue (% of GDP)'].median(),inplace=True)
df['Gross National Income (USD)'].fillna(df['Gross National Income (USD)'].mean(),inplace=True)
df['Public Debt (% of GDP)'].fillna(df['Public Debt (% of GDP)'].median(),inplace=True)
df['Public Debt (% of GDP)'].fillna(df['Public Debt (% of GDP)'].mean(),inplace=True)

C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GDP (Current USD)'].fillna(df['GDP (Current USD)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GDP per Capita (Current USD)'].fillna(df['GDP per Capita (Current USD)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Unemployment Rate (%)'].fillna(df['Unemployment Rate (%)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Interest Rate (Real, %)'].fillna(df['Interest Rate (Real, %)'].mode()[0],inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Inflation (GDP Deflator, %)'].fillna(df['Inflation (GDP Deflator, %)'].mode()[0],inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GDP Growth (% Annual)'].fillna(df['GDP Growth (% Annual)'].mode()[0],inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Current Account Balance (% GDP)'].fillna(df['Current Account Balance (% GDP)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Government Expense (% of GDP)'].fillna(df['Government Expense (% of GDP)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Government Revenue (% of GDP)'].fillna(df['Government Revenue (% of GDP)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Tax Revenue (% of GDP)'].fillna(df['Tax Revenue (% of GDP)'].median(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gross National Income (USD)'].fillna(df['Gross National Income (USD)'].mean(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Public Debt (% of GDP)'].fillna(df['Public Debt (% of GDP)'].median(),inplace=True)
C:\Users\mrcoo\AppData\Local\Temp\ipykernel_19192\3008570019.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Public Debt (% of GDP)'].fillna(df['Public Debt (% of GDP)'].mean(),inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3472 entries, 0 to 3471
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country_name                     3472 non-null   object
 1   country_id                       3472 non-null   object
 2   year                             3472 non-null   int64
 3   Inflation (CPI %)                3472 non-null   float64
 4   GDP (Current USD)                3472 non-null   float64
 5   GDP per Capita (Current USD)     3472 non-null   float64
 6   Unemployment Rate (%)            3472 non-null   float64
 7   Interest Rate (Real, %)          3472 non-null   float64
 8   Inflation (GDP Deflator, %)      3472 non-null   float64
 9   GDP Growth (% Annual)            3472 non-null   float64
 10  Current Account Balance (% GDP)  3472 non-null   float64
 11  Government Expense (% of GDP)    3472 non-null   float64
 12  Government Revenue (% of GDP)    3472 non-null   float64
 13  Tax Revenue (% of GDP)           3472 non-null   float64
 14  Gross National Income (USD)      3472 non-null   float64
 15  Public Debt (% of GDP)           3472 non-null   float64
dtypes: float64(13), int64(1), object(2)
memory usage: 434.1+ KB

In [18]:
df.head()

,country_name,country_id,year,Inflation (CPI %),GDP (Current USD),GDP per Capita (Current USD),Unemployment Rate (%),"Interest Rate (Real, %)","Inflation (GDP Deflator, %)",GDP Growth (% Annual),Current Account Balance (% GDP),Government Expense (% of GDP),Government Revenue (% of GDP),Tax Revenue (% of GDP),Gross National Income (USD),Public Debt (% of GDP)
0,Aruba,aw,2010,2.078141,2.453597e+09,24093.140151,7.841141,11.666131,-1.223407,-2.733457,-18.752537,27.325359,26.677467,16.321438,2.313385e+09,51.651469
1,Aruba,aw,2011,4.316297,2.637859e+09,25712.384302,7.841141,4.801974,4.005674,3.369237,-9.877656,27.325359,26.677467,16.321438,2.391841e+09,51.651469
2,Aruba,aw,2012,0.627472,2.615208e+09,25119.665545,7.841141,8.200875,0.184033,-1.040800,3.473451,27.325359,26.677467,16.321438,2.499118e+09,51.651469
3,Aruba,aw,2013,-2.372065,2.727850e+09,25813.576727,7.841141,10.709709,-1.995948,6.431483,-11.813206,27.325359,26.677467,16.321438,2.563517e+09,51.651469
4,Aruba,aw,2014,0.421441,2.790850e+09,26129.839062,7.841141,3.213869,3.958897,-1.586575,-4.658577,27.325359,26.677467,16.321438,2.688102e+09,51.651469