# CONFUSION MATRIX AND CLASSIFICATION REPORT

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [56]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_14/smart_grid_stability_augmented.csv')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tau1    60000 non-null  float64
 1   tau2    60000 non-null  float64
 2   tau3    60000 non-null  float64
 3   tau4    60000 non-null  float64
 4   p1      60000 non-null  float64
 5   p2      60000 non-null  float64
 6   p3      60000 non-null  float64
 7   p4      60000 non-null  float64
 8   g1      60000 non-null  float64
 9   g2      60000 non-null  float64
 10  g3      60000 non-null  float64
 11  g4      60000 non-null  float64
 12  stab    60000 non-null  float64
 13  stabf   60000 non-null  object
dtypes: float64(13), object(1)
memory usage: 6.4+ MB

In [58]:
df.sample()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
8391,1.136279,9.261779,8.736571,2.396798,3.878883,-1.607562,-0.842587,-1.428734,0.459413,0.157157,0.398017,0.897055,-0.015499,stable

In [59]:
custom_mapping_dict = {
    "stable": 1,
    "unstable" : 0
}


df['stabf_encdd'] = df['stabf'].map(custom_mapping_dict)

df.drop(columns='stabf', axis=1, inplace=True)

In [60]:
df.sample(5)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf_encdd
38642,4.173772,3.406604,3.792392,5.586809,3.271438,-1.096484,-1.001877,-1.173077,0.742170,0.157342,0.841027,0.689708,0.062680,0
11131,0.979394,9.111884,0.747599,8.699922,3.864435,-1.540961,-1.774388,-0.549085,0.273091,0.205144,0.120542,0.782445,-0.008979,1
27963,3.546459,5.092361,7.775137,4.299237,2.068963,-0.766027,-0.602027,-0.700909,0.596276,0.172523,0.580701,0.871143,0.041613,0
55441,8.947947,9.182157,1.524483,8.647446,2.818545,-1.240105,-0.780488,-0.797952,0.311904,0.247091,0.500875,0.643168,0.009191,0
48500,7.254641,6.669159,9.819000,2.643170,4.140336,-1.284693,-1.337804,-1.517839,0.292980,0.699170,0.479849,0.781298,0.030868,0

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tau1         60000 non-null  float64
 1   tau2         60000 non-null  float64
 2   tau3         60000 non-null  float64
 3   tau4         60000 non-null  float64
 4   p1           60000 non-null  float64
 5   p2           60000 non-null  float64
 6   p3           60000 non-null  float64
 7   p4           60000 non-null  float64
 8   g1           60000 non-null  float64
 9   g2           60000 non-null  float64
 10  g3           60000 non-null  float64
 11  g4           60000 non-null  float64
 12  stab         60000 non-null  float64
 13  stabf_encdd  60000 non-null  int64
dtypes: float64(13), int64(1)
memory usage: 6.4 MB

# MODEL TRAINING

In [62]:
x = df.drop('stabf_encdd', axis=1)
y = df['stabf_encdd']

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [64]:
model=DecisionTreeClassifier()

In [65]:
model

DecisionTreeClassifier()

In [66]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [67]:
y_pred = model.predict(x_test)

In [68]:
y_pred

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [69]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[7678,    0],
       [   0, 4322]], dtype=int64)

In [70]:
c_report = classification_report(y_test, y_pred)

In [71]:
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7678
           1       1.00      1.00      1.00      4322

    accuracy                           1.00     12000
   macro avg       1.00      1.00      1.00     12000
weighted avg       1.00      1.00      1.00     12000