# LINEAR REGRESSION

In [36]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [37]:
df = pd.read_csv('C:/Users/mrcoo/ml_course/ML-course/lesson_15/housing.csv')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [39]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [40]:
# Function and missing values 


def clean(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [41]:
clean(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [42]:
def encoding(df):
    encoder = LabelEncoder()

    for col in df.columns.to_list(): 
        if df[col].dtype == 'object':
            if df[col].nunique() <= 6:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df.drop(columns=[col], inplace=True)
                df[dummies.columns] = dummies
            else:
                df[col] = encoder.fit_transform(df[col].astype(str))
    
    return df

In [43]:
encoding(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   longitude                   20640 non-null  float64
 1   latitude                    20640 non-null  float64
 2   housing_median_age          20640 non-null  float64
 3   total_rooms                 20640 non-null  float64
 4   total_bedrooms              20640 non-null  float64
 5   population                  20640 non-null  float64
 6   households                  20640 non-null  float64
 7   median_income               20640 non-null  float64
 8   median_house_value          20640 non-null  float64
 9   ocean_proximity_<1H OCEAN   20640 non-null  int32
 10  ocean_proximity_INLAND      20640 non-null  int32
 11  ocean_proximity_ISLAND      20640 non-null  int32
 12  ocean_proximity_NEAR BAY    20640 non-null  int32
 13  ocean_proximity_NEAR OCEAN  20640 non-null  int32
dtypes: float64(9), int32(5)
memory usage: 1.8 MB

In [44]:
df.sample()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
8194,-118.13,33.79,45.0,2317.0,448.0,1057.0,428.0,4.375,234800.0,0,0,0,0,1

In [45]:
scaler = MinMaxScaler()

In [46]:
def scaling(df):
    for col in df.columns:
        if df[col].dtype!='object':
            df[col]=scaler.fit_transform(df[[col]])
    return df

In [47]:
scaling(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   longitude                   20640 non-null  float64
 1   latitude                    20640 non-null  float64
 2   housing_median_age          20640 non-null  float64
 3   total_rooms                 20640 non-null  float64
 4   total_bedrooms              20640 non-null  float64
 5   population                  20640 non-null  float64
 6   households                  20640 non-null  float64
 7   median_income               20640 non-null  float64
 8   median_house_value          20640 non-null  float64
 9   ocean_proximity_<1H OCEAN   20640 non-null  float64
 10  ocean_proximity_INLAND      20640 non-null  float64
 11  ocean_proximity_ISLAND      20640 non-null  float64
 12  ocean_proximity_NEAR BAY    20640 non-null  float64
 13  ocean_proximity_NEAR OCEAN  20640 non-null  float64
dtypes: float64(14)
memory usage: 2.2 MB

In [48]:
df.sample()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
572,0.209163,0.554729,1.0,0.073096,0.100403,0.037473,0.103766,0.211521,0.490516,0.0,0.0,0.0,1.0,0.0

In [49]:
x = df.drop(columns="median_house_value", axis=1)

In [50]:
x

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,0.211155,0.567481,0.784314,0.022331,0.019863,0.008941,0.020556,0.539668,0.0,0.0,0.0,1.0,0.0
1,0.212151,0.565356,0.392157,0.180503,0.171477,0.067210,0.186976,0.538027,0.0,0.0,0.0,1.0,0.0
2,0.210159,0.564293,1.000000,0.037260,0.029330,0.013818,0.028943,0.466028,0.0,0.0,0.0,1.0,0.0
3,0.209163,0.564293,1.000000,0.032352,0.036313,0.015555,0.035849,0.354699,0.0,0.0,0.0,1.0,0.0
4,0.209163,0.564293,1.000000,0.041330,0.043296,0.015752,0.042427,0.230776,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,0.324701,0.737513,0.470588,0.042296,0.057883,0.023599,0.054103,0.073130,0.0,1.0,0.0,0.0,0.0
20636,0.312749,0.738576,0.333333,0.017676,0.023122,0.009894,0.018582,0.141853,0.0,1.0,0.0,0.0,0.0
20637,0.311753,0.732200,0.313725,0.057277,0.075109,0.028140,0.071041,0.082764,0.0,1.0,0.0,0.0,0.0
20638,0.301793,0.732200,0.333333,0.047256,0.063315,0.020684,0.057227,0.094295,0.0,1.0,0.0,0.0,0.0
20639,0.309761,0.725824,0.294118,0.070782,0.095438,0.038790,0.086992,0.130253,0.0,1.0,0.0,0.0,0.0

In [51]:
y = df['median_house_value']

In [52]:
y

0        0.902266
1        0.708247
2        0.695051
3        0.672783
4        0.674638
           ...
20635    0.130105
20636    0.128043
20637    0.159383
20638    0.143713
20639    0.153403
Name: median_house_value, Length: 20640, dtype: float64

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)
linear_reg = LinearRegression()

In [54]:
linear_reg

LinearRegression()

In [55]:
linear_reg.fit(x_train, y_train)

LinearRegression()

In [56]:
y_prediction = linear_reg.predict(x_test)

In [57]:
y_prediction

array([0.1023304 , 0.24700999, 0.51765638, ..., 0.87459842, 0.21814045,
       0.34718836])

In [58]:
r2=r2_score(y_test,y_prediction)
mse=mean_squared_error(y_test,y_prediction)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_prediction)


print(r2)
print(mse)
print(rmse)
print(mae)

0.6257351821159707
0.020849651727246357
0.14439408480698354
0.1045393194900844