In [1]:
import pandas as pd

In [39]:
df=pd.read_csv('IMDB_Movies_Dataset.csv')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   int64
 1   Title              4991 non-null   object
 2   Average Rating     4991 non-null   float64
 3   Director           4991 non-null   object
 4   Writer             4990 non-null   object
 5   Metascore          3057 non-null   float64
 6   Cast               4984 non-null   object
 7   Release Date       4991 non-null   object
 8   Country of Origin  4988 non-null   object
 9   Languages          4970 non-null   object
 10  Budget             2653 non-null   object
 11  Worldwide Gross    3897 non-null   object
 12  Runtime            4991 non-null   object
 13  Writer.1           4990 non-null   object
 14  Average Rating.1   4991 non-null   float64
dtypes: float64(3), int64(1), object(11)
memory usage: 585.0+ KB

In [5]:
df.head(1)

,Unnamed: 0,Title,Average Rating,Director,Writer,Metascore,Cast,Release Date,Country of Origin,Languages,Budget,Worldwide Gross,Runtime,Writer.1
0,0,The Shawshank Redemption,9.3,Frank Darabont,"Stephen King, Frank Darabont",82.0,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","October 14, 1994 (India)",United States,English,"$25,000,000 (estimated)","$29,332,133",2 hours 22 minutes,"Stephen King, Frank Darabont"

In [9]:
df['Budget'].value_counts()

Budget
$15,000,000 (estimated)       63
$2,000,000 (estimated)        51
$25,000,000 (estimated)       50
$3,000,000 (estimated)        50
$30,000,000 (estimated)       50
                              ..
$5,900,000 (estimated)         1
£153,756 (estimated)           1
$1,135,654 (estimated)         1
DEM 680,000 (estimated)        1
THB 65,000,000 (estimated)     1
Name: count, Length: 882, dtype: int64

In [10]:
df['Budget']

0       $25,000,000 (estimated)
1                           NaN
2        $6,000,000 (estimated)
3                           NaN
4                           NaN
                 ...
4985                        NaN
4986                        NaN
4987     €7,000,000 (estimated)
4988                        NaN
4989    $25,000,000 (estimated)
Name: Budget, Length: 4990, dtype: object

# Tozalash

In [11]:
df['Budget']=df['Budget'].str.replace(r'[^\d.]','', regex=True).astype(float)

In [41]:
df['Budget']

0       $25,000,000 (estimated)
1                           NaN
2        $6,000,000 (estimated)
3                           NaN
4                           NaN
                 ...
4986                        NaN
4987     €7,000,000 (estimated)
4988                        NaN
4989    $25,000,000 (estimated)
4990    $25,000,000 (estimated)
Name: Budget, Length: 4991, dtype: object

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   int64
 1   Title              4991 non-null   object
 2   Average Rating     4991 non-null   float64
 3   Director           4991 non-null   object
 4   Writer             4990 non-null   object
 5   Metascore          3057 non-null   float64
 6   Cast               4984 non-null   object
 7   Release Date       4991 non-null   object
 8   Country of Origin  4988 non-null   object
 9   Languages          4970 non-null   object
 10  Budget             2653 non-null   object
 11  Worldwide Gross    3897 non-null   object
 12  Runtime            4991 non-null   object
 13  Writer.1           4990 non-null   object
 14  Average Rating.1   4991 non-null   float64
dtypes: float64(3), int64(1), object(11)
memory usage: 585.0+ KB

In [18]:
df['Worldwide Gross']=df['Worldwide Gross'].str.replace(r'[^\d.]','', regex=True).astype(float)

In [51]:
df['Worldwide Gross']=df['Worldwide Gross'].str.replace(r'[^\d.]','1', regex=True).astype(float)

AttributeError: Can only use .str accessor with string values!

In [48]:
df['Worldwide Gross']

0       1.291332e+10
1       1.315132e+09
2       1.250134e+11
3                NaN
4                NaN
            ...
4986    1.291893e+10
4987    1.171871e+10
4988    1.550103e+07
4989    1.291332e+10
4990    1.291332e+10
Name: Worldwide Gross, Length: 4991, dtype: float64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4990 entries, 0 to 4989
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4990 non-null   int64
 1   Title              4990 non-null   object
 2   Average Rating     4990 non-null   float64
 3   Director           4990 non-null   object
 4   Writer             4989 non-null   object
 5   Metascore          3056 non-null   float64
 6   Cast               4983 non-null   object
 7   Release Date       4990 non-null   object
 8   Country of Origin  4987 non-null   object
 9   Languages          4969 non-null   object
 10  Budget             2652 non-null   object
 11  Worldwide Gross    3896 non-null   float64
 12  Runtime            4990 non-null   object
 13  Writer.1           4989 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 545.9+ KB

# Duplicated

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   int64
 1   Title              4991 non-null   object
 2   Average Rating     4991 non-null   float64
 3   Director           4991 non-null   object
 4   Writer             4990 non-null   object
 5   Metascore          3057 non-null   float64
 6   Cast               4984 non-null   object
 7   Release Date       4991 non-null   object
 8   Country of Origin  4988 non-null   object
 9   Languages          4970 non-null   object
 10  Budget             2653 non-null   object
 11  Worldwide Gross    3897 non-null   object
 12  Runtime            4991 non-null   object
 13  Writer.1           4990 non-null   object
 14  Average Rating.1   4991 non-null   float64
dtypes: float64(3), int64(1), object(11)
memory usage: 585.0+ KB

In [26]:
# Qator boyicha duplicated elementlarni aniqlang
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4986    False
4987    False
4988    False
4989     True
4990     True
Length: 4991, dtype: bool

In [ ]:
df.duplicated().sum()    # Aynan duplicated bolgan qatorlarni  umumiy sonini aniqlash

2

In [ ]:
df[df.duplicated()]   # Aynan duplicated bolgan qatorlarni aniqlash

,Unnamed: 0,Title,Average Rating,Director,Writer,Metascore,Cast,Release Date,Country of Origin,Languages,Budget,Worldwide Gross,Runtime,Writer.1,Average Rating.1
4989,0,The Shawshank Redemption,9.3,Frank Darabont,"Stephen King, Frank Darabont",82.0,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","October 14, 1994 (India)",United States,English,"$25,000,000 (estimated)","$29,332,133",2 hours 22 minutes,"Stephen King, Frank Darabont",9.3
4990,0,The Shawshank Redemption,9.3,Frank Darabont,"Stephen King, Frank Darabont",82.0,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","October 14, 1994 (India)",United States,English,"$25,000,000 (estimated)","$29,332,133",2 hours 22 minutes,"Stephen King, Frank Darabont",9.3

In [29]:
df=df.drop_duplicates()

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4984    False
4985    False
4986    False
4987    False
4988    False
Length: 4989, dtype: bool

In [31]:
df.duplicated().sum()

0

In [32]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Title, Average Rating, Director, Writer, Metascore, Cast, Release Date, Country of Origin, Languages, Budget, Worldwide Gross, Runtime, Writer.1, Average Rating.1]
Index: []

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4989 entries, 0 to 4988
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4989 non-null   int64
 1   Title              4989 non-null   object
 2   Average Rating     4989 non-null   float64
 3   Director           4989 non-null   object
 4   Writer             4988 non-null   object
 5   Metascore          3055 non-null   float64
 6   Cast               4982 non-null   object
 7   Release Date       4989 non-null   object
 8   Country of Origin  4986 non-null   object
 9   Languages          4968 non-null   object
 10  Budget             2651 non-null   object
 11  Worldwide Gross    3895 non-null   object
 12  Runtime            4989 non-null   object
 13  Writer.1           4988 non-null   object
 14  Average Rating.1   4989 non-null   float64
dtypes: float64(3), int64(1), object(11)
memory usage: 623.6+ KB

In [34]:
# Ustun boyicha duplicated elementlarni aniqlang
df.T.duplicated()

Unnamed: 0           False
Title                False
Average Rating       False
Director             False
Writer               False
Metascore            False
Cast                 False
Release Date         False
Country of Origin    False
Languages            False
Budget               False
Worldwide Gross      False
Runtime              False
Writer.1              True
Average Rating.1      True
dtype: bool

In [35]:
df.T[df.T.duplicated()]

,0,1,2,3,4,5,6,7,8,9,...,4979,4980,4981,4982,4983,4984,4985,4986,4987,4988
Writer.1,"Stephen King, Frank Darabont","Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue","Mario Puzo, Francis Ford Coppola","Umur Bugay, Rifat Ilgaz","Rani Burra, Ram Mohan, Yûgô Sakô",Suzanne Bernert,"Pingali Nagendra Rao, Kadiri Venkata Reddy","Jonathan Nolan, Christopher Nolan, David S. Goyer","Thomas Keneally, Steven Zaillian",Reginald Rose,...,"Leila Conners, Nadia Conners, Leonardo DiCaprio",Samuel Maoz,"Hiroyuki Yamaga, Hiroshi Ônogi","Mahesh Bhatt, Girish Dhamija, Anurag Basu",Nuran Evren Sit,"Jorge Guerricaechevarría, Álex de la Iglesia","Roy Chanslor, Arthur Conan Doyle","Hiroshi Takahashi, Shôgo Mutô","Ruben Alves, Luc-Olivier Veuve, Jean-André Yerlès",Kwak Kyung-taek
Average Rating.1,9.3,9.3,9.2,9.2,9.2,9.1,9.1,9.0,9.0,9.0,...,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2

In [36]:
df=df.loc[:,~df.T.duplicated()]

In [37]:
df.T[df.T.duplicated()]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 4989 columns]

In [38]:
df.T.duplicated()

Unnamed: 0           False
Title                False
Average Rating       False
Director             False
Writer               False
Metascore            False
Cast                 False
Release Date         False
Country of Origin    False
Languages            False
Budget               False
Worldwide Gross      False
Runtime              False
dtype: bool