In [1]:
#Data Loading
import pandas as pd
df=pd.read_csv('Train (1).csv')

# Data bn tanishuv

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   object
 2   Ever_Married     7928 non-null   object
 3   Age              8068 non-null   int64
 4   Graduated        7990 non-null   object
 5   Profession       7944 non-null   object
 6   Work_Experience  7239 non-null   float64
 7   Spending_Score   8068 non-null   object
 8   Family_Size      7733 non-null   float64
 9   Var_1            7992 non-null   object
 10  Segmentation     8068 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 693.5+ KB

In [8]:
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

In [9]:
df['Age'].value_counts()

Age
35    250
37    234
33    232
42    232
40    229
     ...
78     29
87     28
76     27
80     24
85     22
Name: count, Length: 67, dtype: int64

# Data Preprocessing

In [3]:
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [4]:
tozala(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   object
 2   Ever_Married     8068 non-null   object
 3   Age              8068 non-null   int64
 4   Graduated        8068 non-null   object
 5   Profession       8068 non-null   object
 6   Work_Experience  8068 non-null   float64
 7   Spending_Score   8068 non-null   object
 8   Family_Size      8068 non-null   float64
 9   Var_1            8068 non-null   object
 10  Segmentation     8068 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 693.5+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder

In [7]:
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [8]:
df=encodla(df)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      8068 non-null   int64
 1   Age                     8068 non-null   int64
 2   Profession              8068 non-null   int32
 3   Work_Experience         8068 non-null   float64
 4   Family_Size             8068 non-null   float64
 5   Var_1                   8068 non-null   int32
 6   Gender_Female           8068 non-null   int32
 7   Gender_Male             8068 non-null   int32
 8   Ever_Married_No         8068 non-null   int32
 9   Ever_Married_Yes        8068 non-null   int32
 10  Graduated_No            8068 non-null   int32
 11  Graduated_Yes           8068 non-null   int32
 12  Spending_Score_Average  8068 non-null   int32
 13  Spending_Score_High     8068 non-null   int32
 14  Spending_Score_Low      8068 non-null   int32
 15  Segmentation_A          8068 non-null   int32
 16  Segmentation_B          8068 non-null   int32
 17  Segmentation_C          8068 non-null   int32
 18  Segmentation_D          8068 non-null   int32
dtypes: float64(2), int32(15), int64(2)
memory usage: 725.0 KB

In [18]:
df.head()

,ID,Age,Profession,Work_Experience,Family_Size,Var_1,Gender_Female,Gender_Male,Ever_Married_No,Ever_Married_Yes,Graduated_No,Graduated_Yes,Spending_Score_Average,Spending_Score_High,Spending_Score_Low,Segmentation_A,Segmentation_B,Segmentation_C,Segmentation_D
0,462809,22,5,1.000000,4.0,3,0,1,1,0,1,0,0,0,1,0,0,0,1
1,462643,38,2,2.641663,3.0,3,1,0,0,1,0,1,1,0,0,1,0,0,0
2,466315,67,2,1.000000,1.0,5,1,0,0,1,0,1,0,0,1,0,1,0,0
3,461735,67,7,0.000000,2.0,5,0,1,0,1,0,1,0,1,0,0,1,0,0
4,462669,40,3,2.641663,6.0,5,1,0,0,1,0,1,0,1,0,1,0,0,0

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
def scale_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('Age')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [12]:
scale_qil(df)

,ID,Age,Profession,Work_Experience,Family_Size,Var_1,Gender_Female,Gender_Male,Ever_Married_No,Ever_Married_Yes,Graduated_No,Graduated_Yes,Spending_Score_Average,Spending_Score_High,Spending_Score_Low,Segmentation_A,Segmentation_B,Segmentation_C,Segmentation_D
0,0.425601,22,0.625,0.071429,0.375,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.407140,38,0.250,0.188690,0.250,0.500000,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.815503,67,0.250,0.071429,0.000,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.306161,67,0.875,0.000000,0.125,0.833333,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.410031,40,0.375,0.188690,0.625,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8063,0.560053,22,0.000,0.000000,0.750,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8064,0.634230,35,0.500,0.214286,0.375,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8065,0.714413,33,0.625,0.071429,0.000,0.833333,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8066,0.924933,27,0.625,0.071429,0.375,0.833333,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
8067,0.322175,37,0.500,0.000000,0.250,0.500000,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [13]:
df.head()

,ID,Age,Profession,Work_Experience,Family_Size,Var_1,Gender_Female,Gender_Male,Ever_Married_No,Ever_Married_Yes,Graduated_No,Graduated_Yes,Spending_Score_Average,Spending_Score_High,Spending_Score_Low,Segmentation_A,Segmentation_B,Segmentation_C,Segmentation_D
0,0.425601,22,0.625,0.071429,0.375,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.407140,38,0.250,0.188690,0.250,0.500000,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.815503,67,0.250,0.071429,0.000,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.306161,67,0.875,0.000000,0.125,0.833333,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.410031,40,0.375,0.188690,0.625,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      8068 non-null   float64
 1   Age                     8068 non-null   int64
 2   Profession              8068 non-null   float64
 3   Work_Experience         8068 non-null   float64
 4   Family_Size             8068 non-null   float64
 5   Var_1                   8068 non-null   float64
 6   Gender_Female           8068 non-null   float64
 7   Gender_Male             8068 non-null   float64
 8   Ever_Married_No         8068 non-null   float64
 9   Ever_Married_Yes        8068 non-null   float64
 10  Graduated_No            8068 non-null   float64
 11  Graduated_Yes           8068 non-null   float64
 12  Spending_Score_Average  8068 non-null   float64
 13  Spending_Score_High     8068 non-null   float64
 14  Spending_Score_Low      8068 non-null   float64
 15  Segmentation_A          8068 non-null   float64
 16  Segmentation_B          8068 non-null   float64
 17  Segmentation_C          8068 non-null   float64
 18  Segmentation_D          8068 non-null   float64
dtypes: float64(18), int64(1)
memory usage: 1.2 MB

# Linear Regression

In [15]:
x=df.drop('Age',axis=1)

In [16]:
y=df['Age']

In [17]:
from sklearn.model_selection import train_test_split

In [ ]:
# Datasetni train  va testga ajratish
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#kutubxonalar , algorith
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [20]:
lr

LinearRegression()

In [ ]:
# Train
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
x_test

,ID,Profession,Work_Experience,Family_Size,Var_1,Gender_Female,Gender_Male,Ever_Married_No,Ever_Married_Yes,Graduated_No,Graduated_Yes,Spending_Score_Average,Spending_Score_High,Spending_Score_Low,Segmentation_A,Segmentation_B,Segmentation_C,Segmentation_D
742,0.923599,0.375,0.188690,0.250,0.500000,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2127,0.796263,0.375,0.000000,0.125,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2107,0.697843,0.625,0.285714,0.500,0.166667,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2943,0.562834,0.375,0.071429,0.375,0.833333,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4362,0.008118,0.375,0.071429,0.500,0.833333,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3196,0.760009,0.500,0.642857,0.250,0.500000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
6302,0.499666,0.125,0.000000,0.000,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4377,0.823732,0.250,0.000000,0.125,0.833333,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3473,0.109987,0.625,0.571429,0.000,0.833333,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4776,0.509675,0.375,0.071429,0.375,0.833333,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [27]:
# Predict
y_pred=lr.predict(x_test)

In [29]:
y_pred[0
       ]

28.655191191033555

In [30]:
y

0       22
1       38
2       67
3       67
4       40
        ..
8063    22
8064    35
8065    33
8066    27
8067    37
Name: Age, Length: 8068, dtype: int64

In [31]:
# Model Evaluation(Regression)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [33]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [34]:
print(r2)
print(mae)
print(mse)
print(rmse)

0.4844254514629117
9.336751348802302
141.81203239041648
11.908485730369604

# Decision Tree Regressor

In [35]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()

In [36]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [37]:
y_pred=dt.predict(x_test)

In [38]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [39]:
print(r2)
print(mae)
print(mse)
print(rmse)

0.3239933253278411
10.01177199504337
185.93990086741016
13.635978177872321