#### Linear regression
#### Classification report

In [112]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [113]:
df = pd.read_csv('smart_grid_stability_augmented.csv')

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tau1    60000 non-null  float64
 1   tau2    60000 non-null  float64
 2   tau3    60000 non-null  float64
 3   tau4    60000 non-null  float64
 4   p1      60000 non-null  float64
 5   p2      60000 non-null  float64
 6   p3      60000 non-null  float64
 7   p4      60000 non-null  float64
 8   g1      60000 non-null  float64
 9   g2      60000 non-null  float64
 10  g3      60000 non-null  float64
 11  g4      60000 non-null  float64
 12  stab    60000 non-null  float64
 13  stabf   60000 non-null  object
dtypes: float64(13), object(1)
memory usage: 6.4+ MB

In [115]:
df.sample()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
39187,4.970208,4.743189,4.297122,3.766771,3.719625,-0.662392,-1.313596,-1.743636,0.686797,0.583937,0.852362,0.282177,0.067391,unstable

In [116]:
custom_mapping_dict = {
    "stable": 1,
    "unstable" : 0
}

df['stabf_encdd'] = df['stabf'].map(custom_mapping_dict)
df.drop(columns='stabf', axis=1, inplace=True)

In [117]:
df.sample(5)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf_encdd
7276,1.975981,0.834371,8.018833,3.325401,2.231360,-0.621978,-0.932918,-0.676464,0.417101,0.961409,0.211177,0.701045,-0.054493,1
7315,5.229659,0.886574,1.678654,8.219264,2.225979,-0.548027,-0.601866,-1.076086,0.555815,0.454558,0.593222,0.725230,-0.011756,1
20162,2.290102,8.071234,6.169944,3.028512,3.624592,-0.820951,-1.699638,-1.104003,0.785595,0.234290,0.225070,0.770194,-0.020523,1
38707,7.290588,4.058820,4.630990,3.713098,4.839512,-1.818388,-1.654522,-1.366602,0.830744,0.926367,0.743171,0.898920,0.098724,0
16145,5.350829,5.090104,3.317839,3.627837,4.336520,-0.946721,-1.747661,-1.642137,0.407798,0.763454,0.915428,0.999336,0.092042,0

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   tau1         60000 non-null  float64
 1   tau2         60000 non-null  float64
 2   tau3         60000 non-null  float64
 3   tau4         60000 non-null  float64
 4   p1           60000 non-null  float64
 5   p2           60000 non-null  float64
 6   p3           60000 non-null  float64
 7   p4           60000 non-null  float64
 8   g1           60000 non-null  float64
 9   g2           60000 non-null  float64
 10  g3           60000 non-null  float64
 11  g4           60000 non-null  float64
 12  stab         60000 non-null  float64
 13  stabf_encdd  60000 non-null  int64
dtypes: float64(13), int64(1)
memory usage: 6.4 MB

In [119]:
df.sample(5)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf_encdd
45983,1.537623,5.426635,8.979323,2.580879,3.582569,-1.461293,-0.507229,-1.614047,0.327954,0.441228,0.501684,0.230035,-0.021691,1
32375,9.261410,8.690981,2.572369,3.894008,3.173684,-1.072777,-1.290913,-0.809994,0.610548,0.734435,0.054113,0.795811,0.042597,0
7324,4.195109,8.568553,6.730599,1.507211,4.247137,-1.569459,-0.710049,-1.967628,0.185425,0.604485,0.140997,0.970799,-0.034237,1
48589,2.351825,1.116888,8.308583,5.549330,2.736650,-0.500426,-1.247225,-0.988999,0.086343,0.179911,0.845414,0.887799,0.033864,0
59426,9.928493,7.533663,2.445956,3.279859,3.721894,-1.549495,-1.323893,-0.848506,0.871339,0.128779,0.369453,0.879246,0.007258,0

#### Model training

In [120]:
x = df.drop('stabf_encdd', axis=1)
y = df['stabf_encdd']

In [121]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [122]:
model=LogisticRegression()

In [123]:
model

LogisticRegression()

In [124]:
model.fit(x_train, y_train)

c:\Users\mrcoo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [125]:
y_pred = model.predict(x_test)

In [126]:
y_pred

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [127]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[7480,  198],
       [ 217, 4105]], dtype=int64)

In [128]:
c_report = classification_report(y_test, y_pred)

In [129]:
print(c_report)

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7678
           1       0.95      0.95      0.95      4322

    accuracy                           0.97     12000
   macro avg       0.96      0.96      0.96     12000
weighted avg       0.97      0.97      0.97     12000