# Encoding

In [67]:
import pandas as pd
df=pd.read_csv('metadata_bundesliga_1415.csv')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          4 non-null      object
dtypes: float64(5), int64(10), object(4)
memory usage: 67.4+ KB

In [ ]:
#drop
#1 ustun boyicha

In [41]:
df.drop('Size',axis=1,inplace=True)

In [42]:
df.drop(columns=[['Size','id']])

KeyError: "[('Size', 'id')] not found in axis"

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          4 non-null      object
dtypes: float64(5), int64(10), object(4)
memory usage: 67.4+ KB

In [9]:
# dropni qator boyicha tashlab
df.dropna(inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4 non-null      int64
 1   player_name   4 non-null      object
 2   games         4 non-null      int64
 3   time          4 non-null      int64
 4   goals         4 non-null      int64
 5   xG            4 non-null      float64
 6   assists       4 non-null      int64
 7   xA            4 non-null      float64
 8   shots         4 non-null      int64
 9   key_passes    4 non-null      int64
 10  yellow_cards  4 non-null      int64
 11  red_cards     4 non-null      int64
 12  position      4 non-null      object
 13  team_title    4 non-null      object
 14  npg           4 non-null      int64
 15  npxG          4 non-null      float64
 16  xGChain       4 non-null      float64
 17  xGBuildup     4 non-null      float64
 18  Size          4 non-null      object
dtypes: float64(5), int64(10), object(4)
memory usage: 640.0+ bytes

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
dtypes: float64(5), int64(10), object(3)
memory usage: 63.8+ KB

In [19]:
df.isnull().sum()

id                0
player_name       0
games             0
time              0
goals             0
xG                0
assists           0
xA                0
shots             0
key_passes        0
yellow_cards      0
red_cards         0
position          0
team_title        0
npg               0
npxG              0
xGChain           0
xGBuildup         0
Size            449
dtype: int64

In [20]:
df['Size'].fillna(df['Size'].mode()[0],inplace=True)

In [21]:
df.nunique()

id              453
player_name     453
games            34
time            397
goals            17
xG              391
assists          13
xA              389
shots            76
key_passes       59
yellow_cards     12
red_cards         3
position         14
team_title       26
npg              16
npxG            391
xGChain         432
xGBuildup       419
Size              4
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
dtypes: float64(5), int64(10), object(3)
memory usage: 63.8+ KB

# One- Hot encoding

In [51]:
dummies=pd.get_dummies(df['player_name'],prefix='ustun',dtype=int)

In [52]:
dummies

,ustun_Aaron Hunt,ustun_Abdul Rahman Baba,ustun_Adam Hlousek,ustun_Adam Matuschyk,ustun_Admir Mehmedi,ustun_Adrián Ramos,ustun_Alban Meha,ustun_Alejandro Gálvez,ustun_Aleksandar Ignjovski,ustun_Alexander Esswein,...,ustun_Yannick Gerhardt,ustun_Yunus Malli,ustun_Yuya Osako,ustun_Zlatko Junuzovic,ustun_Zoltán Stieber,ustun_Ádám Szalai,ustun_Álvaro Domínguez,ustun_Änis Ben-Hatira,ustun_Ömer Toprak,ustun_Özkan Yildirim
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
449,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
450,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
df=pd.concat([df.drop(columns=['player_name']),dummies],axis=1)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Columns: 471 entries, id to ustun_Özkan Yildirim
dtypes: float64(5), int32(453), int64(10), object(3)
memory usage: 865.4+ KB

In [ ]:
df=pd.concat(df_1,df_2)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  ustun_2XL     453 non-null    int32
 19  ustun_MS      453 non-null    int32
 20  ustun_S       453 non-null    int32
 21  ustun_XL      453 non-null    int32
dtypes: float64(5), int32(4), int64(10), object(3)
memory usage: 70.9+ KB

In [31]:
df['Size']

0       XL
1        S
2       MS
3      2XL
4      2XL
      ...
448    2XL
449    2XL
450    2XL
451    2XL
452    2XL
Name: Size, Length: 453, dtype: object

# Label Encoding

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    object
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          4 non-null      object
dtypes: float64(5), int64(10), object(4)
memory usage: 67.4+ KB

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
encoder=LabelEncoder()

In [61]:
encoder

LabelEncoder()

In [73]:
df['player_name']=encoder.fit_transform(df['player_name'])

In [74]:
df['player_name']=encoder.transform(df['player_name'])

ValueError: y contains previously unseen labels: 12

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            453 non-null    int64
 1   player_name   453 non-null    int32
 2   games         453 non-null    int64
 3   time          453 non-null    int64
 4   goals         453 non-null    int64
 5   xG            453 non-null    float64
 6   assists       453 non-null    int64
 7   xA            453 non-null    float64
 8   shots         453 non-null    int64
 9   key_passes    453 non-null    int64
 10  yellow_cards  453 non-null    int64
 11  red_cards     453 non-null    int64
 12  position      453 non-null    object
 13  team_title    453 non-null    object
 14  npg           453 non-null    int64
 15  npxG          453 non-null    float64
 16  xGChain       453 non-null    float64
 17  xGBuildup     453 non-null    float64
 18  Size          4 non-null      object
dtypes: float64(5), int32(1), int64(10), object(3)
memory usage: 65.6+ KB

In [66]:
df.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,Size
0,356,12,26,2209,19,15.395941,2,1.268694,80,22,0,0,F M S,Eintracht Frankfurt,16,12.364834,12.408789,1.915658,XL
1,227,342,31,2493,17,17.722183,5,4.644013,104,32,0,0,F M S,Bayern Munich,16,16.964407,23.315430,4.924822,S
2,392,21,21,1681,17,10.364112,7,7.505970,88,50,0,0,D F M S,Bayern Munich,15,8.848720,20.820983,8.605793,MS
3,158,28,21,1532,16,11.341977,4,2.659186,43,15,1,0,F S,Wolfsburg,16,11.341977,15.911891,2.538306,2XL
4,318,326,33,2724,16,15.396760,6,6.378020,102,46,4,0,F M S,Borussia Dortmund,14,13.881207,20.852728,2.512650,NaN