In [21]:
import pandas as pd 
df=pd.read_csv('metadata_premier_league_1415.xls')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    int64
 1   player_name   531 non-null    object
 2   games         531 non-null    int64
 3   time          531 non-null    int64
 4   goals         531 non-null    int64
 5   xG            531 non-null    float64
 6   assists       531 non-null    int64
 7   xA            531 non-null    float64
 8   shots         531 non-null    int64
 9   key_passes    531 non-null    int64
 10  yellow_cards  531 non-null    int64
 11  red_cards     531 non-null    int64
 12  position      531 non-null    object
 13  team_title    531 non-null    object
 14  npg           531 non-null    int64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    int64
dtypes: float64(5), int64(11), object(3)
memory usage: 78.9+ KB

In [ ]:
id-
name--
games--- umumiy oyinlar

In [29]:
df.head(25

)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,...,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league_ratio,gpg,ypg
0,619,Sergio Aguero,33,2551,26,25.270160,8,5.568922,148,33,...,0,F S,Manchester City,21,20.703184,27.805155,6.878173,9,0.787879,0.121212
1,647,Harry Kane,34,2589,21,17.157292,4,3.922501,112,27,...,0,F M S,Tottenham,19,14.873823,16.488439,5.549699,9,0.617647,0.117647
2,802,Diego Costa,26,2111,20,15.219104,3,4.554671,76,41,...,0,F S,Chelsea,19,14.457935,21.365790,5.276973,9,0.769231,0.307692
3,848,Charlie Austin,35,3078,18,17.881850,5,2.548747,131,23,...,1,F,Queens Park Rangers,15,14.076043,13.718276,3.041321,9,0.514286,0.114286
4,498,Alexis S??nchez,35,2967,16,13.451750,8,8.494180,122,82,...,0,F M S,Arsenal,16,12.690581,27.157572,10.736753,9,0.457143,0.114286
5,502,Olivier Giroud,27,1871,14,8.846344,3,3.860136,70,29,...,1,F S,Arsenal,14,8.846344,13.639880,4.129247,9,0.518519,0.185185
6,701,Eden Hazard,38,3389,14,12.016092,9,11.238891,78,100,...,0,M,Chelsea,11,8.971417,31.840571,19.476321,9,0.368421,0.052632
7,811,Saido Berahino,38,2940,14,13.841753,1,1.961661,86,28,...,0,F M S,West Bromwich Albion,10,10.797115,11.907294,2.439558,9,0.368421,0.052632
8,606,Christian Benteke,29,2380,13,8.455074,2,2.921320,80,33,...,1,F S,Aston Villa,12,7.693905,8.725396,2.198609,9,0.448276,0.034483
9,617,David Silva,32,2682,12,9.096988,7,10.388413,66,92,...,0,M,Manchester City,12,9.096988,29.144278,16.633573,9,0.375000,0.250000
10,629,Wayne Rooney,33,2887,12,8.902107,5,3.983562,79,45,...,1,F M,Manchester United,11,7.379769,15.435743,7.295703,9,0.363636,0.151515
11,841,Graziano Pell??,38,3291,12,18.616503,2,4.481624,123,43,...,0,F S,Southampton,12,18.616503,24.785647,5.598169,9,0.315789,0.157895
12,622,Wilfried Bony,30,1604,11,10.454732,3,3.508294,89,26,...,1,F S,"Manchester City,Swansea",10,9.693564,14.252215,4.412425,9,0.366667,0.100000
13,648,Nacer Chadli,35,2423,11,6.865526,5,3.935560,54,41,...,0,M S,Tottenham,11,6.865526,15.642378,8.626995,9,0.314286,0.085714
14,756,Leonardo Ulloa,37,2434,11,8.923919,3,3.791995,49,36,...,0,F S,Leicester,9,7.401582,9.963017,2.509369,9,0.297297,0.081081
15,850,Papiss Demba Ciss??,22,1137,11,8.957139,1,0.334678,45,7,...,0,F S,Newcastle United,10,8.196007,7.444708,0.616738,9,0.500000,0.045455
16,868,Mame Biram Diouf,34,2451,11,11.646978,3,3.466141,55,28,...,0,F M S,Stoke,11,11.646978,13.599630,0.861984,9,0.323529,0.205882
17,986,Danny Ings,35,3048,11,12.289516,4,4.244326,97,35,...,0,F M,Burnley,10,11.528347,16.558704,2.825657,9,0.314286,0.171429
18,594,Romelu Lukaku,36,2880,10,12.430796,5,2.350206,105,37,...,0,F S,Everton,8,10.908533,15.743810,5.078923,9,0.277778,0.027778
19,646,Christian Eriksen,38,3160,10,7.389633,2,6.088787,97,84,...,0,M S,Tottenham,10,7.389633,21.318575,13.018118,9,0.263158,0.105263
20,656,Diafra Sakho,23,1765,10,9.070375,2,2.615856,66,23,...,0,F M S,West Ham,10,9.070375,9.083610,0.912818,9,0.434783,0.086957
21,838,Sadio Man??,30,2142,10,8.553970,3,3.982478,60,40,...,0,F M S,Southampton,10,8.553970,14.567276,4.032990,9,0.333333,0.166667
22,878,Yaya Tour??,29,2358,10,7.109345,1,3.243578,89,33,...,0,M S,Manchester City,8,5.587008,26.024328,20.903262,9,0.344828,0.172414
23,4387,Robin van Persie,27,2126,10,11.603472,2,2.986052,76,27,...,0,F S,Manchester United,9,10.081134,12.917514,1.688729,9,0.370370,0.185185
24,554,Juan Mata,33,2318,9,6.597756,4,4.968639,33,50,...,0,M S,Manchester United,8,5.836588,14.520849,7.047830,9,0.272727,0.060606

In [ ]:
#Xar bir oyin uchun o'rtacha gollar soni----- oyinchini stabilligini korish
self.self.df['gpg']=df['goals']/df['games']

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    int64
 1   player_name   531 non-null    object
 2   games         531 non-null    int64
 3   time          531 non-null    int64
 4   goals         531 non-null    int64
 5   xG            531 non-null    float64
 6   assists       531 non-null    int64
 7   xA            531 non-null    float64
 8   shots         531 non-null    int64
 9   key_passes    531 non-null    int64
 10  yellow_cards  531 non-null    int64
 11  red_cards     531 non-null    int64
 12  position      531 non-null    object
 13  team_title    531 non-null    object
 14  npg           531 non-null    int64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    int64
 19  gpg           531 non-null    float64
dtypes: float64(6), int64(11), object(3)
memory usage: 83.1+ KB

In [ ]:
df['ypg']=df['yellow_cards']/df['games']   #intizom boyucha

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    int64
 1   player_name   531 non-null    object
 2   games         531 non-null    int64
 3   time          531 non-null    int64
 4   goals         531 non-null    int64
 5   xG            531 non-null    float64
 6   assists       531 non-null    int64
 7   xA            531 non-null    float64
 8   shots         531 non-null    int64
 9   key_passes    531 non-null    int64
 10  yellow_cards  531 non-null    int64
 11  red_cards     531 non-null    int64
 12  position      531 non-null    object
 13  team_title    531 non-null    object
 14  npg           531 non-null    int64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    int64
 19  gpg           531 non-null    float64
 20  ypg           531 non-null    float64
dtypes: float64(7), int64(11), object(3)
memory usage: 87.2+ KB

In [30]:
df['XGDIFF']=df['xG']-df['goals']

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    int64
 1   player_name   531 non-null    object
 2   games         531 non-null    int64
 3   time          531 non-null    int64
 4   goals         531 non-null    int64
 5   xG            531 non-null    float64
 6   assists       531 non-null    int64
 7   xA            531 non-null    float64
 8   shots         531 non-null    int64
 9   key_passes    531 non-null    int64
 10  yellow_cards  531 non-null    int64
 11  red_cards     531 non-null    int64
 12  position      531 non-null    object
 13  team_title    531 non-null    object
 14  npg           531 non-null    int64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    int64
 19  gpg           531 non-null    float64
 20  ypg           531 non-null    float64
 21  XGDIFF        531 non-null    float64
dtypes: float64(8), int64(11), object(3)
memory usage: 91.4+ KB

# Classes

In [41]:
class Xisobla:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def add(self):
        return self.a+self.b
    def kop(self):
         return self.a*self.b
    def orta(self):
        return (self.a+self.b)/2

In [ ]:
class ozim:
    def __init__(self,name, height, weight, age, country):

In [42]:
natija=Xisobla(1,2)
natija.add()
natija.kop()
natija.orta()

1.5

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [32]:
#funksiya
def a_b_add(a,b):
    return a+b

In [33]:
a_b_add(1,2)

3

In [33]:
import pandas as pd
df=pd.read_csv('metadata_premier_league_1415.xls')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    int64
 1   player_name   531 non-null    object
 2   games         531 non-null    int64
 3   time          531 non-null    int64
 4   goals         531 non-null    int64
 5   xG            531 non-null    float64
 6   assists       531 non-null    int64
 7   xA            531 non-null    float64
 8   shots         531 non-null    int64
 9   key_passes    531 non-null    int64
 10  yellow_cards  531 non-null    int64
 11  red_cards     531 non-null    int64
 12  position      531 non-null    object
 13  team_title    531 non-null    object
 14  npg           531 non-null    int64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    int64
dtypes: float64(5), int64(11), object(3)
memory usage: 78.9+ KB

# Data Preprocessing ni Class orqali bajarish

In [35]:
# Classga oid misollar vazifa
#Talaba xaqida malumot beruvchi class yozing
#Machine learning bolimlari xaqida malumot beruvchi  class yozing
#Berilgan sonlarni o'rta arifmetigi, geomtetrigi, eng  kattasi, eng kichigini aniqlab beradigan class yozing

In [36]:
#Class
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
class DataPreprocessing:
    def __init__(self,df):
        self.df=df
    def tozala(self):
        for col in self.df.columns:
            if self.df[col].isnull().any():
                if self.df[col].dtype=='object':
                    self.df[col].fillna(self.df[col].mode()[0],inplace=True)                
                else:
                    self.df[col].fillna(self.df[col].mean(),inplace=True)
        return self
    def encodla(self):
        encoder=LabelEncoder()
        for col in self.df.columns:
            if self.df[col].dtype=='object':
                if self.df[col].nunique()<=5:
                    dummies=pd.get_dummies(self.df[col],prefix=col,dtype=int)
                    self.df=pd.concat([self.df.drop(columns=col),dummies],axis=1)
                else:
                    self.df[col]=encoder.fit_transform(self.df[col])
        return self
    def scale_qil(self):
        scaler=MinMaxScaler()
        for col in self.df.columns:
            num_col=self.df.select_dtypes(include=['int64','float64']).columns.drop('xG')
            self.df[num_col]=scaler.fit_transform(self.df[num_col])
        return self

In [37]:
dp=DataPreprocessing(df)
dp.tozala().encodla().scale_qil()
preprocessed_data=dp.df

In [38]:
preprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    float64
 1   player_name   531 non-null    float64
 2   games         531 non-null    float64
 3   time          531 non-null    float64
 4   goals         531 non-null    float64
 5   xG            531 non-null    float64
 6   assists       531 non-null    float64
 7   xA            531 non-null    float64
 8   shots         531 non-null    float64
 9   key_passes    531 non-null    float64
 10  yellow_cards  531 non-null    float64
 11  red_cards     531 non-null    float64
 12  position      531 non-null    float64
 13  team_title    531 non-null    float64
 14  npg           531 non-null    float64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    float64
dtypes: float64(19)
memory usage: 78.9 KB

# Feature Transformation

In [39]:
df=preprocessed_data

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    float64
 1   player_name   531 non-null    float64
 2   games         531 non-null    float64
 3   time          531 non-null    float64
 4   goals         531 non-null    float64
 5   xG            531 non-null    float64
 6   assists       531 non-null    float64
 7   xA            531 non-null    float64
 8   shots         531 non-null    float64
 9   key_passes    531 non-null    float64
 10  yellow_cards  531 non-null    float64
 11  red_cards     531 non-null    float64
 12  position      531 non-null    float64
 13  team_title    531 non-null    float64
 14  npg           531 non-null    float64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    float64
dtypes: float64(19)
memory usage: 78.9 KB

In [ ]:
#num_col ni aniqlang
num_col=df.select_dtypes(include=['float64'])

In [42]:
num_col

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league_ratio
0,0.119973,0.864151,0.864865,0.745832,1.000000,25.270160,0.444444,0.495505,1.000000,0.33,0.285714,0.0,0.615385,0.594595,1.000000,1.000000,0.873262,0.329048,0.0
1,0.126264,0.375472,0.891892,0.756946,0.807692,17.157292,0.222222,0.349011,0.756757,0.27,0.285714,0.0,0.538462,0.945946,0.904762,0.718432,0.517844,0.265494,0.0
2,0.161087,0.250943,0.675676,0.617140,0.769231,15.219104,0.166667,0.405260,0.513514,0.41,0.571429,0.0,0.615385,0.243243,0.904762,0.698344,0.671024,0.252447,0.0
3,0.171422,0.154717,0.918919,0.899971,0.692308,17.881850,0.277778,0.226779,0.885135,0.23,0.285714,0.5,0.384615,0.729730,0.714286,0.679898,0.430843,0.145495,0.0
4,0.092788,0.045283,0.918919,0.867505,0.615385,13.451750,0.444444,0.755785,0.824324,0.82,0.285714,0.0,0.538462,0.000000,0.761905,0.612977,0.852924,0.513640,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,0.998203,0.033962,0.027027,0.027201,0.000000,0.112558,0.000000,0.043241,0.020270,0.01,0.000000,0.0,0.923077,0.729730,0.000000,0.005437,0.001733,0.001078,0.0
527,0.998652,0.949057,0.000000,0.026031,0.000000,0.282559,0.000000,0.000000,0.006757,0.00,0.071429,0.0,0.000000,0.864865,0.000000,0.013648,0.000000,0.000000,0.0
528,0.998877,0.913208,0.027027,0.025446,0.000000,0.000000,0.000000,0.001775,0.000000,0.01,0.000000,0.0,0.923077,0.297297,0.000000,0.000000,0.000626,0.000954,0.0
529,0.999101,0.345283,0.000000,0.004387,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,1.000000,0.486486,0.000000,0.000000,0.000000,0.000000,0.0
530,1.000000,0.700000,0.000000,0.011699,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,1.000000,0.648649,0.000000,0.000000,0.002297,0.003499,0.0

In [ ]:
#num_col larni qiyshayish darajalarini aniqlang
num_col.skew()

id              1.242186
player_name     0.000000
games          -0.149453
time            0.244158
goals           3.105861
xG              3.173485
assists         2.779585
xA              2.287436
shots           2.047193
key_passes      2.002225
yellow_cards    1.150640
red_cards       2.747788
position       -0.290958
team_title     -0.334857
npg             2.886753
npxG            2.919380
xGChain         1.879047
xGBuildup       2.046251
league_ratio    0.000000
dtype: float64

In [ ]:
#1 skew<0.5 --- Transformation  kerak emas
#2 skew<0------- squared transformation
#3 skew>=0.5 ---- Log transformation, sqrt

In [45]:
import numpy as np

In [ ]:
#3filter qikish orqali logga tushadiganlarni ajarating
log_transformation=skewness[(skewness>=0.5)].index.tolist()

In [47]:
log_transformation

['id',
 'goals',
 'xG',
 'assists',
 'xA',
 'shots',
 'key_passes',
 'yellow_cards',
 'red_cards',
 'npg',
 'npxG',
 'xGChain',
 'xGBuildup']

In [48]:
#4  logni qollang
for col in log_transformation:
    df[col+'_log']=np.log1p(df[col])

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                531 non-null    float64
 1   player_name       531 non-null    float64
 2   games             531 non-null    float64
 3   time              531 non-null    float64
 4   goals             531 non-null    float64
 5   xG                531 non-null    float64
 6   assists           531 non-null    float64
 7   xA                531 non-null    float64
 8   shots             531 non-null    float64
 9   key_passes        531 non-null    float64
 10  yellow_cards      531 non-null    float64
 11  red_cards         531 non-null    float64
 12  position          531 non-null    float64
 13  team_title        531 non-null    float64
 14  npg               531 non-null    float64
 15  npxG              531 non-null    float64
 16  xGChain           531 non-null    float64
 17  xGBuildup         531 non-null    float64
 18  league_ratio      531 non-null    float64
 19  id_log            531 non-null    float64
 20  goals_log         531 non-null    float64
 21  xG_log            531 non-null    float64
 22  assists_log       531 non-null    float64
 23  xA_log            531 non-null    float64
 24  shots_log         531 non-null    float64
 25  key_passes_log    531 non-null    float64
 26  yellow_cards_log  531 non-null    float64
 27  red_cards_log     531 non-null    float64
 28  npg_log           531 non-null    float64
 29  npxG_log          531 non-null    float64
 30  xGChain_log       531 non-null    float64
 31  xGBuildup_log     531 non-null    float64
dtypes: float64(32)
memory usage: 132.9 KB

In [51]:
df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['id', 'player_name', 'games', 'time', 'goals', 'xG', 'assists', 'xA',
       'shots', 'key_passes', 'yellow_cards', 'red_cards', 'position',
       'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup', 'league_ratio',
       'id_log', 'goals_log', 'xG_log', 'assists_log', 'xA_log', 'shots_log',
       'key_passes_log', 'yellow_cards_log', 'red_cards_log', 'npg_log',
       'npxG_log', 'xGChain_log', 'xGBuildup_log'],
      dtype='object')>

In [52]:
df.skew()

id                  1.242186
player_name         0.000000
games              -0.149453
time                0.244158
goals               3.105861
xG                  3.173485
assists             2.779585
xA                  2.287436
shots               2.047193
key_passes          2.002225
yellow_cards        1.150640
red_cards           2.747788
position           -0.290958
team_title         -0.334857
npg                 2.886753
npxG                2.919380
xGChain             1.879047
xGBuildup           2.046251
league_ratio        0.000000
id_log              1.159530
goals_log           2.504852
xG_log              0.913173
assists_log         2.226035
xA_log              1.816995
shots_log           1.610166
key_passes_log      1.568657
yellow_cards_log    0.824063
red_cards_log       2.529201
npg_log             2.329106
npxG_log            2.317172
xGChain_log         1.394263
xGBuildup_log       1.489214
dtype: float64

In [ ]:
class DataPreprocessing:

In [ ]:
preprocessed_data.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league_ratio
0,0.119973,0.864151,0.864865,0.745832,1.000000,25.270160,0.444444,0.495505,1.000000,0.33,0.285714,0.0,0.615385,0.594595,1.000000,1.000000,0.873262,0.329048,0.0
1,0.126264,0.375472,0.891892,0.756946,0.807692,17.157292,0.222222,0.349011,0.756757,0.27,0.285714,0.0,0.538462,0.945946,0.904762,0.718432,0.517844,0.265494,0.0
2,0.161087,0.250943,0.675676,0.617140,0.769231,15.219104,0.166667,0.405260,0.513514,0.41,0.571429,0.0,0.615385,0.243243,0.904762,0.698344,0.671024,0.252447,0.0
3,0.171422,0.154717,0.918919,0.899971,0.692308,17.881850,0.277778,0.226779,0.885135,0.23,0.285714,0.5,0.384615,0.729730,0.714286,0.679898,0.430843,0.145495,0.0
4,0.092788,0.045283,0.918919,0.867505,0.615385,13.451750,0.444444,0.755785,0.824324,0.82,0.285714,0.0,0.538462,0.000000,0.761905,0.612977,0.852924,0.513640,0.0

:

In [13]:
#Missing qiymatlar 
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)                
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [ ]:
#Missing qiymatlar 
def tozala(self.df):
    for col in self.df.columns:
        if self.df[col].isnull().any():
            if self.df[col].dtype=='object':
                self.df[col].fillna(self.df[col].mode()[0],inplace=True)                
            else:
                self.df[col].fillna(self.df[col].mean(),inplace=True)
    return self.df

In [14]:
tozala(df)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league_ratio
0,619,Sergio Aguero,33,2551,26,25.270160,8,5.568922,148,33,4,0,F S,Manchester City,21,20.703184,27.805155,6.878173,9
1,647,Harry Kane,34,2589,21,17.157292,4,3.922501,112,27,4,0,F M S,Tottenham,19,14.873823,16.488439,5.549699,9
2,802,Diego Costa,26,2111,20,15.219104,3,4.554671,76,41,8,0,F S,Chelsea,19,14.457935,21.365790,5.276973,9
3,848,Charlie Austin,35,3078,18,17.881850,5,2.548747,131,23,4,1,F,Queens Park Rangers,15,14.076043,13.718276,3.041321,9
4,498,Alexis S??nchez,35,2967,16,13.451750,8,8.494180,122,82,4,0,F M S,Arsenal,16,12.690581,27.157572,10.736753,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,4528,Alejandro Faurlin,2,94,0,0.112558,0,0.485984,3,1,0,0,M S,Queens Park Rangers,0,0.112558,0.055192,0.022536,9
527,4530,Valentin Roberge,1,90,0,0.282559,0,0.000000,1,0,1,0,D,Sunderland,0,0.282559,0.000000,0.000000,9
528,4531,Stuart O&#039;Keefe,2,88,0,0.000000,0,0.019946,0,1,0,0,M S,Crystal Palace,0,0.000000,0.019946,0.019946,9
529,4532,Gary Taylor-Fletcher,1,16,0,0.000000,0,0.000000,0,0,0,0,S,Leicester,0,0.000000,0.000000,0.000000,9
530,4536,Nani,1,41,0,0.000000,0,0.000000,0,0,0,0,S,Manchester United,0,0.000000,0.073149,0.073149,9

In [15]:
# Encoding
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [16]:
df=encodla(df)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    int64
 1   player_name   531 non-null    int64
 2   games         531 non-null    int64
 3   time          531 non-null    int64
 4   goals         531 non-null    int64
 5   xG            531 non-null    float64
 6   assists       531 non-null    int64
 7   xA            531 non-null    float64
 8   shots         531 non-null    int64
 9   key_passes    531 non-null    int64
 10  yellow_cards  531 non-null    int64
 11  red_cards     531 non-null    int64
 12  position      531 non-null    int64
 13  team_title    531 non-null    int64
 14  npg           531 non-null    int64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    int64
dtypes: float64(5), int64(14)
memory usage: 78.9 KB

In [18]:
# Scaler
from sklearn.preprocessing import MinMaxScaler
def scale_qil(df):
    scaler=MinMaxScaler()
    for col in df.columns:
        num_col=df.select_dtypes(include=['int64','float64']).columns.drop('xG')
        df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [19]:
scale_qil(df)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league_ratio
0,0.119973,0.864151,0.864865,0.745832,1.000000,25.270160,0.444444,0.495505,1.000000,0.33,0.285714,0.0,0.615385,0.594595,1.000000,1.000000,0.873262,0.329048,0.0
1,0.126264,0.375472,0.891892,0.756946,0.807692,17.157292,0.222222,0.349011,0.756757,0.27,0.285714,0.0,0.538462,0.945946,0.904762,0.718432,0.517844,0.265494,0.0
2,0.161087,0.250943,0.675676,0.617140,0.769231,15.219104,0.166667,0.405260,0.513514,0.41,0.571429,0.0,0.615385,0.243243,0.904762,0.698344,0.671024,0.252447,0.0
3,0.171422,0.154717,0.918919,0.899971,0.692308,17.881850,0.277778,0.226779,0.885135,0.23,0.285714,0.5,0.384615,0.729730,0.714286,0.679898,0.430843,0.145495,0.0
4,0.092788,0.045283,0.918919,0.867505,0.615385,13.451750,0.444444,0.755785,0.824324,0.82,0.285714,0.0,0.538462,0.000000,0.761905,0.612977,0.852924,0.513640,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,0.998203,0.033962,0.027027,0.027201,0.000000,0.112558,0.000000,0.043241,0.020270,0.01,0.000000,0.0,0.923077,0.729730,0.000000,0.005437,0.001733,0.001078,0.0
527,0.998652,0.949057,0.000000,0.026031,0.000000,0.282559,0.000000,0.000000,0.006757,0.00,0.071429,0.0,0.000000,0.864865,0.000000,0.013648,0.000000,0.000000,0.0
528,0.998877,0.913208,0.027027,0.025446,0.000000,0.000000,0.000000,0.001775,0.000000,0.01,0.000000,0.0,0.923077,0.297297,0.000000,0.000000,0.000626,0.000954,0.0
529,0.999101,0.345283,0.000000,0.004387,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,1.000000,0.486486,0.000000,0.000000,0.000000,0.000000,0.0
530,1.000000,0.700000,0.000000,0.011699,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.0,1.000000,0.648649,0.000000,0.000000,0.002297,0.003499,0.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            531 non-null    float64
 1   player_name   531 non-null    float64
 2   games         531 non-null    float64
 3   time          531 non-null    float64
 4   goals         531 non-null    float64
 5   xG            531 non-null    float64
 6   assists       531 non-null    float64
 7   xA            531 non-null    float64
 8   shots         531 non-null    float64
 9   key_passes    531 non-null    float64
 10  yellow_cards  531 non-null    float64
 11  red_cards     531 non-null    float64
 12  position      531 non-null    float64
 13  team_title    531 non-null    float64
 14  npg           531 non-null    float64
 15  npxG          531 non-null    float64
 16  xGChain       531 non-null    float64
 17  xGBuildup     531 non-null    float64
 18  league_ratio  531 non-null    float64
dtypes: float64(19)
memory usage: 78.9 KB