In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("Social_media_impact_on_life.csv")

In [7]:
df.info(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   object
 3   Academic_Level                1705 non-null   object
 4   Country                       1705 non-null   object
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   object
 7   Affects_Academic_Performance  1705 non-null   object
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 146.7+ KB

In [8]:
df.sample(10)

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
393,436,19,Female,High School,Other,8.3,LinkedIn,Yes,5.0,4.5,Negative
1361,362,21,Male,Graduate,Denmark,3.6,Facebook,No,8.2,8.0,Positive
59,614,19,Male,High School,Other,2.7,Instagram,No,8.5,7.6,Positive
894,158,23,Female,Undergraduate,Other,1.8,LinkedIn,No,8.2,7.2,Positive
13,287,23,Female,Undergraduate,Other,6.2,LinkedIn,No,5.3,5.4,Negative
1344,345,19,Female,Undergraduate,Switzerland,3.7,Instagram,No,8.1,8.0,Positive
408,515,20,Female,Graduate,Other,6.4,Facebook,No,5.5,4.3,Negative
1456,457,19,Female,Undergraduate,USA,8.1,Instagram,Yes,4.2,5.0,Negative
1146,147,19,Male,Undergraduate,Bangladesh,4.5,TikTok,Yes,7.1,5.0,Negative
686,817,22,Female,High School,Other,5.2,TikTok,Yes,6.3,6.8,Neutral

## **Handling missing values**

In [9]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64

## **Encoding**

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
encoder = OrdinalEncoder(categories=[["High School", "Undergraduate", "Graduate"]])
df["Academic_Level_encoded"] = encoder.fit_transform(df[["Academic_Level"]]).astype(int)

In [12]:
df["Overall_Impact"].value_counts()

Overall_Impact
Negative    939
Positive    499
Neutral     267
Name: count, dtype: int64

In [13]:
encoder = OrdinalEncoder(categories=[["Negative", "Neutral", "Positive"]])
df['Overall_Impact_encoded'] = encoder.fit_transform(df[["Overall_Impact"]]).astype(int)

In [14]:
df.drop(columns=["Academic_Level", "Overall_Impact"], inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   object
 3   Country                       1705 non-null   object
 4   Avg_Daily_Usage_Hours         1705 non-null   float64
 5   Most_Used_Platform            1705 non-null   object
 6   Affects_Academic_Performance  1705 non-null   object
 7   Sleep_Hours_Per_Night         1705 non-null   float64
 8   Mental_Health_Score           1705 non-null   float64
 9   Academic_Level_encoded        1705 non-null   int32
 10  Overall_Impact_encoded        1705 non-null   int32
dtypes: float64(3), int32(2), int64(2), object(4)
memory usage: 133.3+ KB

In [16]:
from sklearn.preprocessing import LabelEncoder
def encoding(df):
    encoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype=="object":
            if df[col].nunique() <=5:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df = pd.concat([df.drop(columns=[col]),dummies], axis=1)
            else:
                df[col] = encoder.fit_transform(df[col])
    return df

In [17]:
df = encoding(df)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Student_ID                        1705 non-null   int64
 1   Age                               1705 non-null   int64
 2   Country                           1705 non-null   int32
 3   Avg_Daily_Usage_Hours             1705 non-null   float64
 4   Most_Used_Platform                1705 non-null   int32
 5   Sleep_Hours_Per_Night             1705 non-null   float64
 6   Mental_Health_Score               1705 non-null   float64
 7   Academic_Level_encoded            1705 non-null   int32
 8   Overall_Impact_encoded            1705 non-null   int32
 9   Gender_Female                     1705 non-null   int32
 10  Gender_Male                       1705 non-null   int32
 11  Affects_Academic_Performance_No   1705 non-null   int32
 12  Affects_Academic_Performance_Yes  1705 non-null   int32
dtypes: float64(3), int32(8), int64(2)
memory usage: 120.0 KB

In [19]:
df.sample(10)

,Student_ID,Age,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Academic_Level_encoded,Overall_Impact_encoded,Gender_Female,Gender_Male,Affects_Academic_Performance_No,Affects_Academic_Performance_Yes
329,453,21,39,7.8,6,5.0,4.5,2,0,0,1,0,1
570,747,20,73,5.0,6,7.4,6.7,2,1,1,0,0,1
1292,293,19,103,6.8,6,5.3,4.0,1,0,1,0,0,1
1270,271,20,5,4.5,1,7.3,7.0,1,2,1,0,1,0
1044,45,18,3,5.5,6,5.3,5.0,0,0,0,1,0,1
1150,151,19,92,4.9,6,4.9,6.0,1,0,0,1,0,1
1248,249,19,46,3.6,3,8.1,8.0,1,1,1,0,1,0
1444,445,19,94,2.7,1,9.1,8.0,1,2,1,0,1,0
1419,420,22,18,4.4,6,7.8,6.0,2,0,0,1,0,1
697,816,18,102,3.6,7,7.1,7.0,0,1,1,0,0,1

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
x = df.drop("Overall_Impact_encoded", axis=1)
y = df["Overall_Impact_encoded"]

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

rfc = RandomForestClassifier()

rfc.fit(x_train, y_train)

RandomForestClassifier()

In [28]:
y_pred = rfc.predict(x_test)

In [29]:
from sklearn.metrics import classification_report

cl_r = classification_report(y_test, y_pred)

print(cl_r)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       197
           1       1.00      0.96      0.98        51
           2       0.99      0.99      0.99        93

    accuracy                           0.99       341
   macro avg       0.99      0.98      0.99       341
weighted avg       0.99      0.99      0.99       341