# Model Building

In [156]:
import pandas as pd

In [157]:
df = pd.read_csv('ai_assistant_usage_student_life.csv')

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SessionID           10000 non-null  object
 1   StudentLevel        10000 non-null  object
 2   Discipline          10000 non-null  object
 3   SessionDate         10000 non-null  object
 4   SessionLengthMin    10000 non-null  float64
 5   TotalPrompts        9989 non-null   float64
 6   TaskType            10000 non-null  object
 7   AI_AssistanceLevel  10000 non-null  int64
 8   FinalOutcome        10000 non-null  object
 9   UsedAgain           10000 non-null  bool
 10  SatisfactionRating  10000 non-null  float64
dtypes: bool(1), float64(3), int64(1), object(6)
memory usage: 791.1+ KB

### filling missing values

In [159]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [160]:
df['TotalPrompts'].fillna(df['TotalPrompts'].mean(), inplace=True)

In [161]:
df.isnull().sum()

SessionID             0
StudentLevel          0
Discipline            0
SessionDate           0
SessionLengthMin      0
TotalPrompts          0
TaskType              0
AI_AssistanceLevel    0
FinalOutcome          0
UsedAgain             0
SatisfactionRating    0
dtype: int64

In [162]:
df['SessionID'].value_counts()

SessionID
SESSION00001    1
SESSION06671    1
SESSION06664    1
SESSION06665    1
SESSION06666    1
               ..
SESSION03334    1
SESSION03335    1
SESSION03336    1
SESSION03337    1
SESSION10000    1
Name: count, Length: 10000, dtype: int64

### dropping columns that are not meaningful features

In [163]:
df.drop(columns='SessionID', axis=1, inplace=True)
df.drop(columns='SessionDate', axis=1, inplace=True)

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   StudentLevel        10000 non-null  object
 1   Discipline          10000 non-null  object
 2   SessionLengthMin    10000 non-null  float64
 3   TotalPrompts        10000 non-null  float64
 4   TaskType            10000 non-null  object
 5   AI_AssistanceLevel  10000 non-null  int64
 6   FinalOutcome        10000 non-null  object
 7   UsedAgain           10000 non-null  bool
 8   SatisfactionRating  10000 non-null  float64
dtypes: bool(1), float64(3), int64(1), object(4)
memory usage: 634.9+ KB

In [165]:
df.sample(5)

,StudentLevel,Discipline,SessionLengthMin,TotalPrompts,TaskType,AI_AssistanceLevel,FinalOutcome,UsedAgain,SatisfactionRating
3643,High School,Computer Science,3.43,1.0,Coding,4,Confused,True,5.0
8945,Undergraduate,History,19.47,4.0,Writing,4,Confused,False,1.5
5041,Undergraduate,Biology,65.99,32.0,Writing,5,Assignment Completed,True,5.0
9323,High School,Business,8.76,2.0,Homework Help,4,Confused,False,3.5
7117,Undergraduate,History,10.23,3.0,Writing,4,Idea Drafted,True,4.1

In [166]:
df['StudentLevel'].value_counts()

StudentLevel
Undergraduate    5978
High School      2027
Graduate         1995
Name: count, dtype: int64

### ORDINAL ENCODING

In [167]:
custom_mapping_dict = {
    'Undergraduate':0,
    'High School':1,
    'Graduate':2}

df['StudentLevel_Ordinal'] = df['StudentLevel'].map(custom_mapping_dict)

df.drop(columns='StudentLevel', axis=1, inplace=True)

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Discipline            10000 non-null  object
 1   SessionLengthMin      10000 non-null  float64
 2   TotalPrompts          10000 non-null  float64
 3   TaskType              10000 non-null  object
 4   AI_AssistanceLevel    10000 non-null  int64
 5   FinalOutcome          10000 non-null  object
 6   UsedAgain             10000 non-null  bool
 7   SatisfactionRating    10000 non-null  float64
 8   StudentLevel_Ordinal  10000 non-null  int64
dtypes: bool(1), float64(3), int64(2), object(3)
memory usage: 634.9+ KB

### FREQUENCY ENCODING

In [169]:
df['Discipline'].value_counts()

Discipline
Biology             1458
Computer Science    1445
Engineering         1430
Math                1422
Psychology          1418
History             1417
Business            1410
Name: count, dtype: int64

In [170]:
df['Discipline_frequency'] = df['Discipline'].map(df['Discipline'].value_counts())
df['TaskType_frequency'] = df['TaskType'].map(df['TaskType'].value_counts())
df['FinalOutcome_frequency'] = df['FinalOutcome'].map(df['FinalOutcome'].value_counts())

In [171]:
df.drop(columns='Discipline', axis=1, inplace=True)
df.drop(columns='TaskType', axis=1, inplace=True)
df.drop(columns='FinalOutcome', axis=1, inplace=True)

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SessionLengthMin        10000 non-null  float64
 1   TotalPrompts            10000 non-null  float64
 2   AI_AssistanceLevel      10000 non-null  int64
 3   UsedAgain               10000 non-null  bool
 4   SatisfactionRating      10000 non-null  float64
 5   StudentLevel_Ordinal    10000 non-null  int64
 6   Discipline_frequency    10000 non-null  int64
 7   TaskType_frequency      10000 non-null  int64
 8   FinalOutcome_frequency  10000 non-null  int64
dtypes: bool(1), float64(3), int64(5)
memory usage: 634.9 KB

### BOOLEAN TO INT

In [173]:
df['UsedAgain'] = df['UsedAgain'].astype(int)

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SessionLengthMin        10000 non-null  float64
 1   TotalPrompts            10000 non-null  float64
 2   AI_AssistanceLevel      10000 non-null  int64
 3   UsedAgain               10000 non-null  int32
 4   SatisfactionRating      10000 non-null  float64
 5   StudentLevel_Ordinal    10000 non-null  int64
 6   Discipline_frequency    10000 non-null  int64
 7   TaskType_frequency      10000 non-null  int64
 8   FinalOutcome_frequency  10000 non-null  int64
dtypes: float64(3), int32(1), int64(5)
memory usage: 664.2 KB

In [175]:
df.sample(5)

,SessionLengthMin,TotalPrompts,AI_AssistanceLevel,UsedAgain,SatisfactionRating,StudentLevel_Ordinal,Discipline_frequency,TaskType_frequency,FinalOutcome_frequency
4007,48.55,14.0,4,0,4.1,0,1422,3101,2866
2295,31.27,7.0,4,1,4.5,1,1458,1959,4768
2320,31.30,7.0,1,1,1.0,0,1422,2040,4768
4651,11.84,3.0,4,0,3.5,0,1445,1948,4768
9371,27.78,10.0,4,0,4.7,0,1430,476,4768

In [176]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler, LabelEncoder
standart=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [177]:
num_col=df.select_dtypes(include=['int64','float64','int32']).columns.tolist()

In [178]:
num_col

['SessionLengthMin',
 'TotalPrompts',
 'AI_AssistanceLevel',
 'UsedAgain',
 'SatisfactionRating',
 'StudentLevel_Ordinal',
 'Discipline_frequency',
 'TaskType_frequency',
 'FinalOutcome_frequency']

In [179]:
robust_cols = ['SessionLengthMin', 'Discipline_frequency', 'TaskType_frequency', 'FinalOutcome_frequency']
standard_cols = ['TotalPrompts']
minmax_cols = ['SatisfactionRating']

# Apply scalers
robust_scaler = RobustScaler()
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

df[robust_cols] = robust_scaler.fit_transform(df[robust_cols])
df[standard_cols] = standard_scaler.fit_transform(df[standard_cols])
df[minmax_cols] = minmax_scaler.fit_transform(df[minmax_cols])

In [180]:
df.sample(5)

,SessionLengthMin,TotalPrompts,AI_AssistanceLevel,UsedAgain,SatisfactionRating,StudentLevel_Ordinal,Discipline_frequency,TaskType_frequency,FinalOutcome_frequency
5293,-0.042840,-0.561114,2,1,0.35,2,-0.142857,-0.070252,0.00000
7939,2.316901,3.960063,2,0,0.20,0,-0.142857,-1.356461,-0.65878
4585,-0.628521,-0.991702,3,0,0.60,0,-0.428571,-0.070252,-0.65878
6450,-0.379108,-0.561114,4,1,0.80,0,0.285714,0.920208,1.00000
9840,-0.553404,-0.776408,3,0,0.25,0,0.821429,0.920208,0.00000

# MODEL TRAINING

In [181]:
x = df.drop('UsedAgain', axis=1)

In [182]:
x

,SessionLengthMin,TotalPrompts,AI_AssistanceLevel,SatisfactionRating,StudentLevel_Ordinal,Discipline_frequency,TaskType_frequency,FinalOutcome_frequency
0,0.853873,1.161239,2,0.000,0,0.821429,0.000000,1.0
1,-0.208920,0.084768,3,0.250,0,-0.142857,0.000000,1.0
2,0.150822,-0.130526,3,0.575,0,-0.428571,-0.079792,1.0
3,-0.759977,-0.991702,3,0.625,0,0.821429,-0.079792,1.0
4,0.673122,0.730651,3,0.475,0,-0.142857,0.920208,1.0
...,...,...,...,...,...,...,...,...
9995,0.690141,-0.130526,3,0.800,0,-0.142857,0.000000,1.0
9996,-0.156690,0.084768,5,1.000,1,-0.428571,0.920208,1.0
9997,-0.344484,-0.776408,3,0.625,0,1.285714,0.000000,0.0
9998,0.835094,0.300063,3,0.825,0,-0.428571,0.920208,1.0
9999,-0.340376,-0.561114,4,0.975,0,0.000000,0.920208,1.0

In [183]:
y = df['UsedAgain']

In [184]:
y

0       1
1       1
2       1
3       1
4       1
       ..
9995    1
9996    1
9997    1
9998    0
9999    1
Name: UsedAgain, Length: 10000, dtype: int32

### SPLITTING DATA INTO TRAINING AND TESTING

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [187]:
from sklearn.linear_model import LogisticRegression

In [188]:
model=LogisticRegression()

In [189]:
model

LogisticRegression()

In [190]:
model.fit(x_train, y_train)

LogisticRegression()

In [191]:
y_prediction = model.predict(x_test)

In [192]:
y_prediction

array([1, 1, 1, ..., 1, 1, 1])

In [193]:
from sklearn.metrics import accuracy_score

In [194]:
accuracy = accuracy_score(y_test, y_prediction)

In [195]:
print(f'Accuracy is {accuracy*100}%')

Accuracy is 70.1%